'use client';


import {ReplaySpeed} from '@/components/replay-speed';
import {useReplaySpeed} from '@/hooks/use-replay-speed';
import {schedulePlaybackTick} from '@/lib/replay-playback';
import {GameHeader} from '@/components/game-header';
import { useEffect, useMemo, useRef, useState, type CSSProperties } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronDown, Clock3, History, LockKeyhole, Plus, Shuffle, Play, Pause, SkipForward, RotateCcw, Search, Shield, Trophy, X } from 'lucide-react';
import { athletesFor, athleteFor, POSITIONS, LINEUP_SLOTS, lineupSlots, eligibleForSlot, historicalTeamLabel, statLine, scoringBreakdown, type Athlete, type LineupSlot, type Position } from '@/lib/game-model';
import { DRAFT_ERAS, filterDraftAthletes, poolAvailability } from '@/lib/era-catalog';
import {matchesPlayableEra,type PlayerBrowsePosition} from '@/lib/player-filters';
import { BroadcastBoard } from '@/components/broadcast-board';
import { draftStorageKey, readStagedDraft, fillOpenSlots } from '@/lib/draft-tools';
import {ScoringPicker,DraftAssistant,QueueButton,useDraftQueue,useDraftRankings} from '@/components/draft-assistant';
import {ScoringContractSummary} from '@/components/scoring-mode-picker';
import {scoringFor,scoringContractLabel,type ScoringRules} from '@/lib/scoring-rules';
import { DraftDetails } from '@/components/draft-details';
import {historicalDrawLabel} from '@/lib/fantasy-replay';
import { EraLibrary } from '@/components/era-library';
import { Rules } from '@/components/game-rules';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import type { Draw, League, Lineup, Round } from '@/lib/game-engine';

type WebTool = {name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
type ModelDocument = Document & {modelContext?:{registerTool:(tool:WebTool,options:{signal:AbortSignal})=>void|Promise<void>}};
type Tab = 'team' | 'matchup' | 'players' | 'results' | 'rules';
const teamNames = ['Home team', 'Away team'];
const positionNames: Record<PlayerBrowsePosition,string> = {ALL:'All players',K:'Kickers',QB:'Quarterbacks',RB:'Running backs',WR:'Wide receivers',TE:'Tight ends',DEF:'Franchise defenses',FLEX:'Flex players (RB, WR, TE)'};
const PAGE_SIZE = 10;
const EMPTY_USED: string[] = [];
function PlayerMark({athlete}:{athlete:Athlete}) {return <span className="ff-player-mark" style={{'--player-color':athlete.color} as CSSProperties}>{athlete.position==='DEF'?<Shield size={19}/>:athlete.number||athlete.name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span>;}

export default function Home() {
 const [league,setLeague]=useState<League|null>(null),[tab,setTab]=useState<Tab>('team'),[position,setPosition]=useState<LineupSlot>('QB');
 const [draft,setDraft]=useState<Lineup>({}),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[signin,setSignin]=useState(false);
 const [handoff,setHandoff]=useState(false),[confirmLock,setConfirmLock]=useState(false),[showGames,setShowGames]=useState(false),[browsePosition,setBrowsePosition]=useState<PlayerBrowsePosition>('ALL'),[browseEra,setBrowseEra]=useState(0),[page,setPage]=useState(0),[sort,setSort]=useState('name');
 const [detail,setDetail]=useState<Athlete|null>(null),[mobilePanel,setMobilePanel]=useState<'roster'|'pool'>('pool'),[notice,setNotice]=useState(''),[historyNumber,setHistoryNumber]=useState<number|null>(null);
 const queue=useDraftQueue(league?`quick:${league.id}:${league.turn}`:'');
 const rankings=useDraftRankings(league?'/api/game':'',league?.revision??0);
 const [libraryBrowse,setLibraryBrowse]=useState({era:0,position:'ALL' as Position|'ALL',visit:0});
 const working=useRef(false),poolRef=useRef<HTMLElement>(null);
 const lineupVersion=league?.lineupVersion;
 const scoring=scoringFor(league),catalog=useMemo(()=>athletesFor(scoring),[scoring]);
 const poolCountLabel=`${catalog.filter(a=>a.position!=='DEF'&&a.position!=='K').length} players + ${catalog.filter(a=>a.position==='DEF').length} defenses`;
 const poolYears=catalog.flatMap(a=>a.seasons),poolYearLabel=poolYears.length?`${Math.min(...poolYears)}–${Math.max(...poolYears)}`:'no';
 const stateRef=useRef({league,draft}); useEffect(()=>{stateRef.current={league,draft};},[league,draft]);
 async function load(){setLoading(true);setError('');try{const response=await fetch('/api/game',{cache:'no-store'});const data=await response.json() as {league:League;error:string;signin?:boolean};if(!response.ok){setSignin(!!data.signin);throw new Error(data.error);}setLeague(data.league);setDraft(readStagedDraft(data.league));setShowGames(data.league.status==='reveal');if(data.league.status==='reveal')setTab('matchup');}catch(e){setError(e instanceof Error?e.message:'Could not load your saved matchup.');}finally{setLoading(false);}}
 useEffect(()=>{const controller=new AbortController();fetch('/api/game',{cache:'no-store',signal:controller.signal}).then(async response=>{const data=await response.json() as {league:League;error:string;signin?:boolean};if(!response.ok){setSignin(!!data.signin);throw new Error(data.error);}setLeague(data.league);setDraft(readStagedDraft(data.league));setShowGames(data.league.status==='reveal');if(data.league.status==='reveal')setTab('matchup');}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Could not load your saved matchup.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[]);
 useEffect(()=>{if(league?.status==='draft'){try{localStorage.setItem(draftStorageKey(league),JSON.stringify(draft));}catch{/* Local draft recovery is optional; server saves still work. */}}},[league,draft]);
 useEffect(()=>{const context=(document as ModelDocument).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools:WebTool[]=[{name:'read_matchup',description:'Read the current private matchup, saved results and staged lineup without drawing or locking.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>stateRef.current},{name:'stage_lineup',description:'Stage distinct player IDs in every current lineup slot, including FLEX (RB/WR/TE), without locking or drawing games.',inputSchema:{type:'object',properties:{QB:{type:'string'},RB:{type:'string'},WR:{type:'string'},TE:{type:'string'},DEF:{type:'string'},FLEX:{type:'string'}},required:lineupSlots({lineupVersion:lineupVersion??2}),additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const current=stateRef.current.league;if(!current||current.status!=='draft')throw new Error('No active draft.');const value=input as Lineup;if(!value||typeof value!=='object'||Object.keys(value).length!==lineupSlots(current).length)throw new Error('Supply every current lineup slot.');if(new Set(Object.values(value)).size!==lineupSlots(current).length)throw new Error('Every starter must be different.');for(const pos of lineupSlots(current)){const a=athleteFor(value[pos],scoringFor(current));if(!eligibleForSlot(a,pos)||!a||!poolAvailability(a,current.used,scoringFor(current)).count)throw new Error('Invalid or exhausted player.');}const staged={...value};setDraft(staged);setTab('team');setMobilePanel('roster');stateRef.current={...stateRef.current,draft:staged};return {staged,locked:false};}}];for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();},[lineupVersion]);
 async function act(action:string,extra:Record<string,unknown>={}){
  if(!league||working.current)return;working.current=true;setBusy(true);setError('');
  try{const response=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,revision:league.revision,turn:league.turn,...extra})});const data=await response.json() as {league:League;error:string;signin?:boolean};if(data.league){setLeague(data.league);if(!response.ok&&(data.league.turn!==league.turn||data.league.round!==league.round||data.league.status!==league.status)){setDraft(readStagedDraft(data.league));setShowGames(data.league.status==='reveal');setTab(data.league.status==='reveal'?'matchup':'team');}}if(!response.ok)throw new Error(data.error);
   if(action==='rules'&&extra.scoringMode!==undefined){setDraft(previous=>Object.fromEntries(Object.entries(previous).filter(([slot,id])=>lineupSlots(data.league).includes(slot as LineupSlot)&&eligibleForSlot(athleteFor(id,scoringFor(data.league)),slot as LineupSlot)&&!!poolAvailability(athleteFor(id,scoringFor(data.league))!,data.league.used,scoringFor(data.league)).count)));setDetail(null);setNotice('Scoring mode saved. Eligible staged picks are kept; unavailable picks were cleared.');}
   if(action==='lock'){try{localStorage.removeItem(draftStorageKey(league));}catch{}setDraft({});setPosition('QB');setBrowsePosition('ALL');setSearch('');setPage(0);setBrowseEra(0);setConfirmLock(false);setHandoff(data.league.status==='draft');setShowGames(false);setNotice('');setMobilePanel('pool');setTab(data.league.status==='reveal'?'matchup':'team');}
   if(action==='next'){setDraft({});setPosition('QB');setBrowsePosition('ALL');setSearch('');setPage(0);setBrowseEra(0);setShowGames(false);setNotice('');setTab('team');setMobilePanel('pool');}
  }catch(e){setConfirmLock(false);setError(e instanceof Error?e.message:'Could not save. Your saved matchup is unchanged.');}finally{working.current=false;setBusy(false);}
 }
 function changePosition(pos:LineupSlot,scroll=false){setPosition(pos);setBrowsePosition(pos);if(browseEra&&!filterDraftAthletes({position:pos,era:browseEra,rules:scoring}).length)setBrowseEra(0);setSearch('');setPage(0);setMobilePanel('pool');if(scroll)requestAnimationFrame(()=>poolRef.current?.scrollIntoView({behavior:'smooth',block:'nearest'}));}
 function quickFill(){if(!league||working.current)return;try{setDraft(fillOpenSlots(league,draft));setNotice('Your open slots are filled. Review your team, then lock when ready.');setMobilePanel('roster');}catch(e){setNotice(e instanceof Error?e.message:'Choose the remaining players yourself.');}}
 function choose(athlete:Athlete){if(athlete.position==='K')return;if(!athleteFor(athlete.id,scoring)){setNotice('This player is not eligible under the saved scoring mode.');return;}if(!league||league.status!=='draft'||working.current)return;const slot=browsePosition==='ALL'?lineupSlots(league).find(p=>!draft[p]&&eligibleForSlot(athlete,p))??(eligibleForSlot(athlete,position)?position:athlete.position):eligibleForSlot(athlete,position)?position:athlete.position;if(Object.entries(draft).some(([p,id])=>p!==slot&&id===athlete.id)){setNotice(`${athlete.name} is already selected. Each starter must be different.`);return;}const updated={...draft,[slot]:athlete.id};setDraft(updated);setNotice(`${athlete.name} added at ${slot}`);const next=lineupSlots(league).find(p=>!updated[p]);if(next){setPosition(next);if(browsePosition!=='ALL'){setBrowsePosition(next);if(browseEra&&!filterDraftAthletes({position:next,era:browseEra,rules:scoring}).length)setBrowseEra(0);}}else setMobilePanel('roster');setSearch('');setPage(0);}
 function remove(pos:LineupSlot){if(working.current)return;const updated={...draft};delete updated[pos];setDraft(updated);setNotice(`${pos} cleared`);setPosition(pos);}
 function openCollection(era=0,collection:Position|'ALL'='ALL'){setLibraryBrowse(previous=>({era,position:collection,visit:previous.visit+1}));setTab('players');}
 const slots=useMemo(()=>league?lineupSlots(league):LINEUP_SLOTS,[league]);
 const picked=slots.filter(p=>draft[p]).length,used=league?.used??EMPTY_USED,round=league?.history.at(-1);
 const players=useMemo(()=>filterDraftAthletes({position:browsePosition,era:browseEra,search,rules:scoring}).filter(a=>slots.some(p=>eligibleForSlot(a,p))&&poolAvailability(a,used,scoring).count>0&&matchesPlayableEra(a,browseEra,used,scoring)).sort((a,b)=>sort==='average'?(rankings.get(b.id)??-Infinity)-(rankings.get(a.id)??-Infinity):sort==='games'?poolAvailability(b,used,scoring).count-poolAvailability(a,used,scoring).count:a.name.localeCompare(b.name)),[browsePosition,browseEra,search,sort,used,rankings,scoring,slots]);
 const missingFifties=scoring.mode==='historical'&&browseEra===1950;
 const profileOnlyEra=!!browseEra&&!filterDraftAthletes({position:browsePosition,era:browseEra,rules:scoring}).some(a=>slots.some(p=>eligibleForSlot(a,p)));
 const pages=Math.max(1,Math.ceil(players.length/PAGE_SIZE)),safePage=Math.min(page,pages-1),visible=players.slice(safePage*PAGE_SIZE,(safePage+1)*PAGE_SIZE);
 const historicRound=league?.history.find(r=>r.number===historyNumber)||round;
 return <div className="site-shell fantasy-app">
  <GameHeader active="quick"/>
  <div className="broadcast-wrap"><BroadcastBoard league={league} picked={picked} total={slots.length} showGames={showGames}/></div>
  <Tabs value={tab} onValueChange={v=>setTab(v as Tab)} className="ff-tabs"><div className="ff-nav-wrap"><TabsList className="ff-tabs-list" aria-label="Quick matchup navigation"><TabsTrigger value="team">Draft room</TabsTrigger><TabsTrigger value="matchup">Matchup{league?.status==='reveal'&&<span className="ff-nav-dot"/>}</TabsTrigger><TabsTrigger value="players">All-time archive</TabsTrigger><TabsTrigger value="results">Results</TabsTrigger><TabsTrigger value="rules">Rules & scoring</TabsTrigger></TabsList></div>
  <main className="ff-main">
   {league&&<ScoringContractSummary rules={scoringFor(league)} lockNotice={league.scoring?.version===5&&league.round===1&&league.turn===0&&league.status==='draft'?'Reception scoring locks with the first lineup':'Scoring is locked for this matchup'}/>}
   <div className="ff-round-strip"><span><Clock3 size={14}/> Round {league?.round??1}</span><ol aria-label="Round progress"><li className={league?.turn===0&&league?.status==='draft'?'current':'complete'}>{league?.turn===1||league?.status==='reveal'?<Check size={13}/>:<span>1</span>} Home {league?.turn===1||league?.status==='reveal'?'locked':'lineup'}</li><li className={league?.status==='reveal'?'complete':league?.turn===1?'current':''}>{league?.status==='reveal'?<Check size={13}/>:<span>2</span>} Away {league?.status==='reveal'?'locked':'lineup'}</li><li className={league?.status==='reveal'?'current':''}><span>3</span> {league?.status==='reveal'&&showGames?'Final result':'Historical draw'}</li></ol></div>
   {error&&<div className="error-banner" role="alert"><span>{error}</span>{signin?<a href="/signin-with-chatgpt?return_to=/matchup" target="_top">Sign in to play</a>:<button onClick={()=>void load()}>Reload saved game</button>}</div>}
   <TabsContent value="team">
    {loading?<div className="loading-panel" role="status"><span className="spinner"/>Loading your team…</div>:league?.status==='reveal'&&round?<><div className="ff-page-title"><div><h2>Both lineups are locked</h2><p>Your round is saved. Open the matchup to see the historical draw.</p></div><button className="primary-button" onClick={()=>setTab('matchup')}>View matchup</button></div><Matchup key={`current:${round.number}`} round={round} showGames={showGames} onReveal={()=>setShowGames(true)} onNext={()=>void act('next')} busy={busy}/></>:league?<>
    <div className="ff-page-title"><div><span className="sports-kicker">{league.turn===0?'HOME':'AWAY'} ON THE CLOCK</span><h2>Build your starting lineup</h2><p>{slots.length===6?'Pick six starters. FLEX takes an extra RB, WR or TE.':'This round keeps its original five slots because a lineup is already locked. FLEX starts next round.'} Year and game are drawn after both teams lock.</p></div><button className="secondary-button quick-fill" disabled={busy||picked===slots.length} onClick={quickFill}><Shuffle size={16}/>Fill open slots</button></div>
    <div className="ff-mobile-switch" role="group" aria-label="Draft view"><button className={mobilePanel==='roster'?'active':''} onClick={()=>setMobilePanel('roster')}>My roster <span>{picked}/{slots.length}</span></button><button className={mobilePanel==='pool'?'active':''} onClick={()=>setMobilePanel('pool')}>Available players</button></div>
    <div className={`ff-draft-grid mobile-${mobilePanel}`}>
     <section className="ff-roster ff-panel" aria-label={`${teamNames[league.turn]} roster`}><div className="ff-panel-title"><h3>{teamNames[league.turn]}</h3><span>{picked} / {slots.length}</span></div>
      <div className="ff-roster-label"><span>POS</span><span>PLAYER</span></div>
      {slots.map(pos=>{const a=athleteFor(draft[pos],scoring);return <div className={`ff-roster-row ${position===pos?'focused':''}`} key={pos}><span className="ff-position">{pos}</span>{a?<><button className="ff-roster-player" onClick={()=>setDetail(a)}><PlayerMark athlete={a}/><span><b>{a.name}</b><small>{a.club} · {a.position}{a.legend?' · HOF':''}</small></span></button><div className="ff-roster-actions"><button onClick={()=>changePosition(pos,true)} aria-label={`Change ${pos}`}>Change</button><button className="ff-remove" onClick={()=>remove(pos)} aria-label={`Remove ${a.name}`}><X size={14}/></button></div></>:<button className="ff-empty-slot" onClick={()=>changePosition(pos,true)}><span>Select {pos==='DEF'?'defense':pos==='FLEX'?'FLEX · RB / WR / TE':pos}</span><Plus size={18}/></button>}</div>;})}
      <div className="ff-lineup-footer"><div className="ff-progress" aria-label={`${picked} of ${slots.length} starters selected`}>{slots.map(p=><span key={p} className={draft[p]?'filled':''}/>)}</div><button className="primary-button ff-lock" disabled={busy||picked!==slots.length} onClick={()=>setConfirmLock(true)}><LockKeyhole size={15}/>{busy?'Saving…':`Lock ${league.turn===0?'home':'away'} lineup`}</button><p>{picked===slots.length?'Ready to lock. Picks cannot change afterward.':`Select ${slots.length-picked} more ${slots.length-picked===1?'starter':'starters'} to lock your lineup.`}</p></div>
      <div className="ff-opponent"><LockKeyhole size={15}/><span>{league.turn===1?'Home lineup locked and hidden':'Away drafts after you lock'}</span><button onClick={()=>setTab('matchup')}>Matchup</button></div>
     </section>
     <section className="ff-pool ff-panel" ref={poolRef} aria-label="Available players"><div className="ff-panel-title"><h3>{browsePosition==='ALL'?'All available players':`Draft a ${browsePosition==='DEF'?'defense':browsePosition==='FLEX'?'FLEX':browsePosition}`}</h3><button className="ff-text-button" onClick={()=>openCollection()}>Player profiles</button></div><div className="ff-position-tabs" style={{gridTemplateColumns:`repeat(${slots.length+1},minmax(0,1fr))`}} role="group" aria-label="Choose position"><button className={browsePosition==='ALL'?'active':''} aria-pressed={browsePosition==='ALL'} onClick={()=>{setBrowsePosition('ALL');setPage(0);setMobilePanel('pool');}}>All</button>{slots.map(pos=><button key={pos} className={browsePosition===pos?'active':''} aria-pressed={browsePosition===pos} onClick={()=>changePosition(pos)}>{pos}{draft[pos]&&<Check size={12}/>}</button>)}</div>
      <div className="ff-pool-tools"><label className="ff-search"><Search size={16}/><input aria-label="Search available players" placeholder={`Search ${positionNames[browsePosition].toLowerCase()}`} value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/>{search&&<button aria-label="Clear player search" onClick={()=>{setSearch('');setPage(0);}}><X size={15}/></button>}</label><label className="ff-era-filter"><span>Verified game era</span><select aria-label="Verified game era" aria-describedby="draft-era-coverage" value={browseEra} onChange={e=>{setBrowseEra(Number(e.target.value));setPage(0);}}><option value={0}>All playable players</option>{DRAFT_ERAS.map(({era})=>{const available=filterDraftAthletes({position:browsePosition,era,rules:scoring}).some(a=>matchesPlayableEra(a,era,used,scoring));return <option key={era} value={era} >{era}s{available?'':' · no playable games'}</option>;})}</select></label><select aria-label="Sort available players" value={sort} onChange={e=>{setSort(e.target.value);setPage(0);}}><option value="name">Name A–Z</option><option value="games">Most games</option><option value="average">Best draw average</option></select></div>
      <div id="draft-era-coverage" className="ff-era-coverage"><p><Shield size={14}/>{browseEra?`${browseEra}s verified game years · Browsing only: draws still use each player’s full eligible game pool.`:`${poolCountLabel} · Real ${poolYearLabel} ${scoring.mode==='historical'?'regular-season ':''}games`}</p><button className="ff-text-button" onClick={()=>openCollection(browseEra||1950,browsePosition==='FLEX'?'ALL':browsePosition)}>Read-only player profiles</button></div>
      <Table className="ff-player-table"><TableHeader><TableRow><TableHead>Player</TableHead><TableHead className="ff-years-col">Loaded years</TableHead><TableHead className="ff-number">Games left</TableHead><TableHead><span className="sr-only">Action</span></TableHead></TableRow></TableHeader><TableBody>{visible.map(a=>{const av=poolAvailability(a,used,scoring),selected=Object.values(draft).includes(a.id);return <TableRow key={a.id} data-position={a.position} data-player-id={a.id} className={selected?'ff-selected-row':''}><TableCell><button className="ff-player-name" onClick={()=>setDetail(a)}><PlayerMark athlete={a}/><span><b>{a.name}{a.legend&&<span className="hof-badge">HOF</span>}</b><small>{a.club} · {a.position}{rankings.has(a.id)?` · ${rankings.get(a.id)!.toFixed(1)} avg`:''}</small><span className="ff-mobile-loaded">{av.seasons[0]}–{av.seasons.at(-1)} games</span></span></button></TableCell><TableCell className="ff-years-col">{av.seasons.length?`${av.seasons[0]}–${av.seasons.at(-1)}`:'Exhausted'}</TableCell><TableCell className="ff-number">{av.count}</TableCell><TableCell className="ff-action-cell"><QueueButton queue={queue} athlete={a}/><button className={`ff-add ${selected?'selected':''}`} aria-label={`${selected?'Selected':'Add'} ${a.name}`} disabled={busy||!av.count||selected} onClick={()=>choose(a)}>{selected?<Check size={16}/>:<Plus size={16}/>}<span>{selected?'Added':'Add'}</span></button></TableCell></TableRow>;})}</TableBody></Table>
      {!players.length&&<div className="ff-empty-search"><Search size={24}/><h3>{missingFifties?'1950s game logs need more verified stats':scoring.mode==='historical'?'No available players match these filters':profileOnlyEra?`No playable ${positionNames[browsePosition].toLowerCase()} from the ${browseEra}s yet`:'No playable players with these filters'}</h3><p>{missingFifties?'The 1950s logs do not record return touchdowns, which these rules score. Unknown stats cannot count as zero. These games will become playable when that gap is verified.':scoring.mode==='historical'?'No unused verified games meet this saved contract and the current filters. Try another name, team or era.':profileOnlyEra?'Explore the profiles above, or clear filters to return to the verified game pool.':'Try another name, team or era. Historical profiles are also available in the collection above.'}</p><button className="secondary-button" onClick={()=>{setBrowsePosition('ALL');setSearch('');setBrowseEra(0);setPage(0);}}>Clear filters</button></div>}
      <button className="ff-text-button" onClick={()=>{setBrowsePosition('ALL');setSearch('');setBrowseEra(0);setPage(0);}}>Clear player filters</button><div className="ff-pagination"><span>{players.length?`${safePage*PAGE_SIZE+1}–${Math.min((safePage+1)*PAGE_SIZE,players.length)} of ${players.length}`:'0 players'}</span><div><button aria-label="Previous player page" disabled={!safePage} onClick={()=>setPage(safePage-1)}><ArrowLeft size={15}/></button><span>{safePage+1} / {pages}</span><button aria-label="Next player page" disabled={safePage+1>=pages} onClick={()=>setPage(safePage+1)}><ArrowRight size={15}/></button></div></div><p className="ff-pool-note">Browse by verified game era; career profiles never grant game eligibility. Tap a name for stats. Era filters never restrict the random draw.</p>
     </section>
    </div>
    <DraftAssistant queue={queue} unavailable={Object.values(draft)} onDetails={setDetail} myTurn={!busy} turnKey={`${league.round}:${league.turn}`} nextText="BUILD YOUR SHORTLIST" scoring={scoringFor(league)}/><div className="ff-draft-bottom"><details className="ff-settings"><summary>Matchup settings <ChevronDown size={15}/></summary><ScoringPicker rules={scoringFor(league)} value={scoringFor(league).receptionPoints} disabled={busy||league.round!==1||league.turn!==0||!league.scoring} onChange={receptionPoints=>void act('rules',{receptionPoints})}/>{!league.scoring&&<p>This saved matchup keeps its original Full PPR scoring.</p>}</details><p><Shield size={15}/> {poolCountLabel} · {poolYearLabel} {scoring.mode==='historical'?'regular-season':'verified'} games</p></div>
    <div className="ff-mobile-lock"><span>{teamNames[league.turn]} <b>{picked}/{slots.length} selected</b></span><button className="primary-button" disabled={busy||picked!==slots.length} onClick={()=>{setMobilePanel('roster');setConfirmLock(true);}}><LockKeyhole size={14}/>Lock lineup</button></div>
    </>:null}
   </TabsContent>
   <TabsContent value="matchup"><div className="ff-page-title"><div><h2>Round {league?.round??1} matchup</h2><p>{league?.status==='reveal'?'Head-to-head results from real historical games.':'Both teams lock before any year or game is drawn.'}</p></div><div className="matchup-title-actions"><span className="ff-status-pill">{league?.status==='reveal'?(showGames?'Final':'Ready to reveal'):'Pre-draw'}</span>{league?.status==='reveal'&&showGames&&<button className="primary-button" disabled={busy} onClick={()=>void act('next')}><RotateCcw size={16}/>{busy?'Opening…':`Play round ${league.round+1}`}</button>}</div></div>{round&&league?.status==='reveal'?<Matchup key={`current:${round.number}`} round={round} showGames={showGames} onReveal={()=>setShowGames(true)} onNext={()=>void act('next')} busy={busy}/>:<PendingMatchup league={league} draft={draft} onTeam={()=>setTab('team')}/>}</TabsContent>
   <TabsContent value="players"><p className="season-pool-note">These player profiles are read-only. Draft eligible players directly from the main board; use its optional era filter to browse verified game years.</p><EraLibrary key={libraryBrowse.visit} initialEra={libraryBrowse.era} initialPosition={libraryBrowse.position} used={used} canDraft={false} onDraft={()=>{}}/></TabsContent>
   <TabsContent value="results"><div className="ff-page-title"><div><h2>Round results</h2><p>Saved scores, source records and every consumed performance.</p></div>{league?.history.length?<select aria-label="Choose completed round" value={historicRound?.number} onChange={e=>setHistoryNumber(Number(e.target.value))}>{league.history.toReversed().map(r=><option key={r.number} value={r.number}>Round {r.number} · {r.winner===null?'Tie':`${r.winner===0?'Home':'Away'} won`}</option>)}</select>:null}</div>{historicRound?<Matchup key={`history:${historicRound.number}`} round={historicRound} showGames/>:<div className="ff-empty-state"><History size={35}/><h3>No completed rounds yet</h3><p>Build both lineups to record your first result.</p><button className="primary-button" onClick={()=>setTab('team')}>Build your team</button></div>}</TabsContent>
   <TabsContent value="rules"><Rules scoring={league?scoringFor(league):undefined}/></TabsContent>
   <footer className="ff-footer"><span>FANTASY FOOTBALL OF THE PAST</span><span>Free to play · Independent fan project · No NFL affiliation</span><button onClick={()=>setTab('rules')}>Data & scoring</button></footer>
  </main></Tabs>
  <div className={`ff-announcement ${notice?'visible':''}`} role="status" aria-live="polite">{notice&&<><Check size={17}/><span>{notice}</span><button aria-label="Dismiss update" onClick={()=>setNotice('')}><X size={15}/></button></>}</div>
  <Dialog open={handoff} onOpenChange={setHandoff}><DialogContent className="ff-modal" showCloseButton={false}><div className="ff-modal-icon"><LockKeyhole size={28}/></div><DialogTitle>Home lineup locked</DialogTitle><DialogDescription>Your six are sealed. Pass the device to Away to build the opposing team. No games have been drawn yet.</DialogDescription><button className="primary-button" onClick={()=>setHandoff(false)}>Away is ready</button></DialogContent></Dialog>
  <Dialog open={confirmLock} onOpenChange={open=>{if(!busy)setConfirmLock(open);}}><DialogContent className="ff-modal"><DialogTitle>Lock {league?.turn===0?'home':'away'} lineup?</DialogTitle><DialogDescription>{league?.turn===0?`These ${slots.length} picks cannot be changed. Away chooses next; no games are drawn yet.`:'Both lineups will be locked and the historical games drawn. This cannot be rerolled.'}</DialogDescription>{league&&<ScoringContractSummary rules={scoringFor(league)} lockNotice="This choice stays fixed for the matchup"/>}<ul className="ff-lock-review">{slots.map(pos=><li key={pos}><span>{pos}</span><b>{athleteFor(draft[pos],scoring)?.name}</b></li>)}</ul><div className="ff-modal-actions"><button className="secondary-button" disabled={busy} onClick={()=>setConfirmLock(false)}>Keep editing</button><button className="primary-button" disabled={busy} onClick={()=>void act('lock',{lineup:draft})}>{busy?'Saving…':'Confirm & lock'} <LockKeyhole size={14}/></button></div></DialogContent></Dialog>
  {detail&&league&&<DraftDetails key={`${detail.id}:${league.revision}`} athlete={detail} revision={league.revision} canDraft={league.status==='draft'&&!busy&&!Object.values(draft).includes(detail.id)} onClose={()=>setDetail(null)} onDraft={()=>{choose(detail);setDetail(null);}}/>}
 </div>;
}

function PendingMatchup({league,draft,onTeam}:{league:League|null;draft:Lineup;onTeam:()=>void}){const slots=league?lineupSlots(league):LINEUP_SLOTS,scoring=scoringFor(league);return <section className="ff-matchup ff-panel"><div className="ff-matchup-teams"><div><span className="ff-team-icon">H</span><h3>Home team</h3><span>{league?.turn===1?'Locked · picks hidden':'Building lineup'}</span></div><div className="ff-matchup-vs">VS<small>ROUND {league?.round??1}</small></div><div><span className="ff-team-icon away">A</span><h3>Away team</h3><span>{league?.turn===1?'Building lineup':'Waiting for Home'}</span></div></div><div className="ff-matchup-row ff-matchup-label"><span>HOME ROSTER</span><span>POS</span><span>AWAY ROSTER</span></div>{slots.map(pos=><div key={pos} className="ff-matchup-row"><span>{league?.turn===0?athleteFor(draft[pos],scoring)?.name||'Empty slot':<><LockKeyhole size={13}/> Locked</>}</span><b className="ff-position">{pos}</b><span>{league?.turn===1?athleteFor(draft[pos],scoring)?.name||'Empty slot':'Not selected'}</span></div>)}<div className="ff-matchup-footer"><p>Scores appear after both lineups are locked.</p><button className="primary-button" onClick={onTeam}>Edit {league?.turn===1?'away':'home'} lineup</button></div></section>;}

function Matchup({round,showGames,onReveal,onNext,busy=false}:{round:Round;showGames:boolean;onReveal?:()=>void;onNext?:()=>void;busy?:boolean}){
 const count=round.draws[0].length;
 const {speed,changeSpeed}=useReplaySpeed();
 const [revealing,setRevealing]=useState(false),[running,setRunning]=useState(false),[step,setStep]=useState(0);
 const completed=useRef(false),onRevealRef=useRef(onReveal);
 useEffect(()=>{onRevealRef.current=onReveal;},[onReveal]);
 const isShown=showGames||revealing,visible=showGames?count:revealing?step:0,complete=isShown&&visible===count;
 useEffect(()=>{if(!running||complete)return;return schedulePlaybackTick(()=>setStep(s=>Math.min(s+1,count)),1200,speed);},[running,step,count,complete,speed]);
 useEffect(()=>{if(!revealing||!complete||completed.current)return;completed.current=true;setRunning(false);onRevealRef.current?.();},[revealing,complete]);
 const scores=round.draws.map(team=>team.slice(0,visible).reduce((total,draw)=>total+draw.points,0));
 function reveal(){setStep(0);setRevealing(true);setRunning(!(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches||document.documentElement.dataset.reduceMotion==='true'));}
 return <section className={`ff-matchup ff-panel ${complete?'game-final':''}`}><div className="ff-matchup-teams"><div><span className="ff-team-icon">H</span><h3>Home team</h3><strong className={round.winner===0&&complete?'winner':''}>{isShown?scores[0].toFixed(2):'—'}</strong><span>{isShown?'Fantasy points':'Lineup locked'}</span></div><div className="ff-matchup-vs">{complete?<Trophy size={30}/>:<LockKeyhole size={24}/>}<b>{complete?(round.winner===null?'Tie game':`${round.winner===0?'Home':'Away'} wins`):revealing?'Game on':'Ready to reveal'}</b><small>ROUND {round.number} · {scoringContractLabel(scoringFor(round))}</small>{complete&&round.winner!==null&&<span className="victory-margin">+{Math.abs(round.totals[0]-round.totals[1]).toFixed(2)} MARGIN</span>}</div><div><span className="ff-team-icon away">A</span><h3>Away team</h3><strong className={round.winner===1&&complete?'winner':''}>{isShown?scores[1].toFixed(2):'—'}</strong><span>{isShown?'Fantasy points':'Lineup locked'}</span></div></div>
 <ScoringContractSummary rules={scoringFor(round)} lockNotice="Saved with this round"/>
 {!isShown&&<div className="ff-reveal"><div><span className="sports-kicker">THE MATCHUP IS SET</span><h3>Let history decide.</h3><p>Six positions. Twelve real performances. One winner.</p></div><button className="primary-button" onClick={reveal}><Play size={18}/>Reveal the matchup</button></div>}
 {!complete&&<div className="quick-playback-controls"><ReplaySpeed speed={speed} onChange={changeSpeed} baseMs={1200}/>{revealing&&<><button className="secondary-button" onClick={()=>setRunning(r=>!r)}>{running?<Pause size={16}/>:<Play size={16}/>} {running?'Pause':'Resume'}</button><button className="secondary-button" onClick={()=>{setRunning(false);setStep(s=>Math.min(s+1,count));}}>Next highlight</button><button className="secondary-button" onClick={()=>{setRunning(false);setStep(count);}}><SkipForward size={16}/>Skip to final</button></>}</div>}
 {revealing&&!complete&&<div className="reveal-progress" role="status"><span>{running?'Revealing':'Paused'} · {visible} of {count} positions</span><div><i style={{width:`${visible/count*100}%`}}/></div></div>}
 <div className="ff-matchup-row ff-matchup-label"><span>HOME <i>{showGames?'PTS':'YEAR'}</i></span><span>POS</span><span>AWAY <i>{showGames?'PTS':'YEAR'}</i></span></div>
 {round.draws[0].map((draw,index)=>{const pos=draw.slot||POSITIONS[index]||'FLEX';return <div className={`ff-matchup-row ff-result-row ${index<visible?'revealed':''}`} key={pos}><DrawCell draw={round.draws[0][index]} showGames={index<visible} scoring={scoringFor(round)}/><span className="ff-position">{pos}</span><DrawCell draw={round.draws[1][index]} showGames={index<visible} scoring={scoringFor(round)}/></div>;})}
 <div className="ff-matchup-footer"><p>{complete?<><Check size={14}/> All {round.draws.reduce((total,team)=>total+team.length,0)} performances removed from this matchup’s pool</>:'No rerolls. These historical performances are already saved.'}</p>{complete&&onNext&&<button className="primary-button" disabled={busy} onClick={onNext}><RotateCcw size={16}/>{busy?'Opening…':`Play round ${round.number+1}`}</button>}</div>
 </section>;
}
function DrawCell({draw,showGames,scoring}:{draw:Draw;showGames:boolean;scoring:ScoringRules}){const athlete=athleteFor(draw.athleteId,scoring)!;const p=draw.performance;return <div className="ff-draw"><div className="ff-draw-top"><PlayerMark athlete={athlete}/><div><h4>{athlete.name}</h4><p>{athlete.position} · {showGames?historicalDrawLabel(p):`${p.season} season`}</p></div><strong>{showGames?draw.points.toFixed(2):<LockKeyhole size={15}/>}</strong></div>{showGames?<><p className="ff-game-line">{historicalTeamLabel(p,p.teamAtTime)} vs {historicalTeamLabel(p,p.opponent)} · {p.date}</p><details className="ff-score-detail"><summary>Game & scoring <ChevronDown size={13}/></summary><p>{statLine(p)}</p><dl>{scoringBreakdown(p.stats,athlete.position,scoring).map(row=><div key={row.label}><dt>{row.label}<small>{row.calculation}</small></dt><dd>{row.points.toFixed(2)}</dd></div>)}<div className="ff-score-total"><dt>Total</dt><dd>{draw.points.toFixed(2)}</dd></div></dl><a href={p.sourceUrl} target="_blank" rel="noreferrer">View source record ↗</a></details></>:<p className="ff-game-line">Historical game sealed</p>}</div>;}
