import {scoringFor} from '@/lib/scoring-rules';
import {publicSeason,seasonAction,SeasonRuleError} from '@/lib/season-engine';
import {draftInsights,draftRankings} from '@/lib/draft-insights';
import {seasonReply,seasonIdentity,checkSeasonOrigin,makeInviteCode,seasonRow,commitSeason} from '@/lib/season-store';
type Context={params:Promise<{id:string}>};
async function authorized(request:Request,context:Context){const userId=seasonIdentity(request);if(!userId)return {response:seasonReply({error:'Sign in to open your league.',signin:true},401)};const {id}=await context.params;const saved=await seasonRow(id);if(!saved)return {response:seasonReply({error:'League not found.'},404)};const s=saved.season;if(!s.teams.some(t=>t.userId===userId))return {response:seasonReply({error:'League not found. Join with your invitation code first.'},404)};return {userId,league:s,records:saved.records};}
export async function GET(request:Request,context:Context){try{const found=await authorized(request,context);if(found.response)return found.response;const params=new URL(request.url).searchParams;if(params.has('rankings'))return seasonReply({rankings:draftRankings(found.league!.used,scoringFor(found.league)),scoring:scoringFor(found.league),revision:found.league!.revision});const athlete=params.get('athlete');if(athlete){const insights=draftInsights(athlete,found.league!.used,scoringFor(found.league));return insights?seasonReply({insights,revision:found.league!.revision}):seasonReply({error:'Player not found.'},404);}return seasonReply({league:publicSeason(found.league!,found.userId!)});}catch{return seasonReply({error:'The league could not load. Try again.'},503);}}
export async function POST(request:Request,context:Context){
 try{checkSeasonOrigin(request);}catch{return seasonReply({error:'This request did not come from the league.'},403);}
 try{const found=await authorized(request,context);if(found.response)return found.response;const s=found.league!,userId=found.userId!;const body=await request.json().catch(()=>null) as Record<string,unknown>;if(!body||typeof body!=='object'||Array.isArray(body))return seasonReply({error:'Supply a valid league action.'},400);if(body.revision!==s.revision)return seasonReply({error:'The league changed. Review the updated state and try again.',league:publicSeason(s,userId)},409);if(body.scoringMode!==undefined&&body.action!=='rules')throw new SeasonRuleError('Scoring is fixed when the draft starts. Use the lobby scoring settings before then.');if(body.action==='rotateInvite'||body.action==='removeManager')body.inviteCode=makeInviteCode();const next=seasonAction(s,userId,body);return await commitSeason(s,next,userId,found.records!);
 }catch(e){if(e instanceof SeasonRuleError)return seasonReply({error:e.message},400);return seasonReply({error:'The action could not be saved. Try again.'},503);}
}
