import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {registerHooks} from 'node:module';import test from 'node:test';
registerHooks({load(url,c,n){if(url.startsWith('file:')&&url.endsWith('.json'))return {format:'module',shortCircuit:true,source:`export default ${readFileSync(new URL(url),'utf8')}`};return n(url,c);},resolve(id,c,n){try{return n(id,c);}catch(e){if(id.startsWith('.')&&!/\.[a-z]+$/i.test(id))return n(`${id}.ts`,c);throw e;}}});
const {newSeason,joinSeason,seasonAction,publicSeason}=await import('../lib/season-engine');const {PERFORMANCES,ATHLETES,score}=await import('../lib/historical-data');const {scoringFor}=await import('../lib/scoring-rules');
// Original-archive exhaustion fixtures keep the saved Strict contract.
function active(capacity=2,playoffTeams=4){let s=newSeason('a',{name:'Bench QA',teamName:'A',capacity,format:'seventeen',playoffTeams,hallCap:0,scoringMode:'strict'},'test');for(let i=1;i<capacity;i++)s=joinSeason(s,`u${i}`,`Team ${i}`);s=seasonAction(s,'a',{action:'startDraft'});while(s.status==='draft')s=seasonAction(s,'a',{action:'autopick'});return s;}
const seed=active();
test('whole frozen roster draws once, no free agents, only starters affect scores, bench receipts withheld per manager',()=>{let s=structuredClone(seed);const before=JSON.stringify(s);s=seasonAction(s,'a',{action:'lock',lineup:s.teams[0].lineup});assert.equal(s.used.length,0);const bench=s.teams[0].roster.find(id=>!Object.values(s.teams[0].lineup).includes(id))!;assert.throws(()=>seasonAction(s,'a',{action:'swap',drop:bench,add:bench}),/locked/);s=seasonAction(s,'u1',{action:'lock',lineup:s.teams[1].lineup});const r=s.history[0];assert.equal(s.used.length,20);assert.equal(new Set(s.used).size,20);for(const t of s.teams){assert.deepEqual(r.rosterSnapshots![t.id],t.roster);assert.equal(r.benchDraws![t.id].length,4);assert.deepEqual(new Set([...r.draws[t.id],...r.benchDraws![t.id]].map(d=>d.athleteId)),new Set(t.roster));}assert.equal(r.matches[0].homeScore,Math.round(r.draws[r.matches[0].home].reduce((a,d)=>a+d.points,0)*100)/100);const hidden=publicSeason(s,'a');assert.equal(hidden.history[0].benchDraws,undefined);for(const d of Object.values(r.benchDraws!).flat()){assert.ok(s.used.includes(d.performance.id!));assert.ok(!JSON.stringify(hidden).includes(d.performance.id!));assert.equal(d.points,score(d.performance.stats!,ATHLETES.find(a=>a.id===d.athleteId)!.position,scoringFor(s)));}const history=JSON.stringify(s.history),used=[...s.used];for(let n=0;n<3;n++)s=seasonAction(JSON.parse(JSON.stringify(s)),'a',{action:'revealReplay',round:1});assert.equal(JSON.stringify(s.history),history);assert.deepEqual(s.used,used);assert.deepEqual(publicSeason(s,'a').history[0].benchDraws,r.benchDraws);assert.equal(publicSeason(s,'u1').history[0].benchDraws,undefined);assert.throws(()=>seasonAction(s,'a',{action:'closeRound'}));assert.equal(JSON.stringify(seed),before);});
test('bench bye is zero/no draw; exhausted pool is unavailable, never fabricated zero',()=>{const s=structuredClone(seed);s.round=5;for(const id of Object.keys(s.byes!.weeks))s.byes!.weeks[id]=6;const t=s.teams[0],bench=t.roster.filter(id=>!Object.values(t.lineup).includes(id));s.byes!.weeks[bench[0]]=5;s.used=PERFORMANCES.filter(p=>p.athleteId===bench[1]).map(p=>p.id);const prior=s.used.length,r=seasonAction(s,'a',{action:'closeRound'});const b=r.history[0].benchDraws![t.id];assert.equal(b[0].points,0);assert.equal(b[0].simulatedBye,true);assert.equal(b[1].points,null);assert.equal(b[1].unavailable,'exhausted');assert.equal(r.used.length-prior,18);});
test('old results are not backfilled; later roster moves and reveals cannot rewrite snapshot',()=>{let s=seasonAction(seed,'a',{action:'closeRound'});delete s.history[0].benchDraws;delete s.history[0].rosterSnapshots;const old=JSON.stringify(s.history),used=[...s.used];s=seasonAction(s,'a',{action:'revealReplay',round:1});assert.equal(publicSeason(s,'a').history[0].benchDraws,undefined);assert.equal(JSON.stringify(s.history),old);assert.deepEqual(s.used,used);s=seasonAction(s,'a',{action:'next'});s=seasonAction(s,'a',{action:'closeRound'});assert.ok(s.history[1].benchDraws);assert.equal(JSON.stringify(s.history[0]),JSON.parse(old).map((r:unknown)=>JSON.stringify(r))[0]);});
test('both online playoff formats resolve all 17 weeks, only playing teams consume, no repeat IDs',()=>{for(const playoffTeams of [4,6]){let s=active(6,playoffTeams);for(let week=1;week<=17;week++){s=seasonAction(s,'a',{action:'closeRound'});const r=s.history.at(-1)!;assert.equal(Object.keys(r.benchDraws!).length,r.matches.length*2);assert.equal(new Set(s.used).size,s.used.length);const all=s.history.flatMap(r=>[...Object.values(r.draws).flat(),...Object.values(r.benchDraws!).flat()]);assert.equal(s.used.length,all.filter(d=>d.performance.id).length);if(week<17)s=seasonAction(s,'a',{action:'next'});}assert.equal(s.status,'complete');}});

test('real negative fractional bench performance is consumed exactly once and keeps its actual score',()=>{const s=structuredClone(seed),t=s.teams[0],bench=t.roster.filter(id=>!Object.values(t.lineup).includes(id));const p=PERFORMANCES.find(p=>!s.teams.some(t=>t.roster.includes(p.athleteId))&&score(p.stats,ATHLETES.find(a=>a.id===p.athleteId)!.position,scoringFor(s))<0&&score(p.stats,ATHLETES.find(a=>a.id===p.athleteId)!.position,scoringFor(s))%1!==0);assert.ok(p,'Archive includes a negative fractional bench game');t.roster[t.roster.indexOf(bench[0])]=p.athleteId;s.used=PERFORMANCES.filter(g=>g.athleteId===p.athleteId&&g.id!==p.id).map(g=>g.id);const result=seasonAction(s,'a',{action:'closeRound'}),d=result.history[0].benchDraws![t.id].find(d=>d.athleteId===p.athleteId)!;assert.equal(d.performance.id,p.id);assert.equal(d.points,score(p.stats,ATHLETES.find(a=>a.id===p.athleteId)!.position,scoringFor(s)));assert.equal(result.used.filter(id=>id===p.id).length,1);});

test('bench card identity has explicit readable colors inside dark replay and mobile stacking',()=>{const css=readFileSync(new URL('../app/globals.css',import.meta.url),'utf8');assert.match(css,/\.bench-points \.bench-player-card \{ background:#f7f9f1; color:#182b2b;/);assert.match(css,/\.bench-points \.bench-player-name \{ color:#182b2b;/);assert.match(css,/\.bench-points \.bench-player-card \.bench-player-position \{ color:#354b40;/);assert.match(css,/@media\(max-width:600px\)\{\s*\.bench-points \.season-team-rosters \{ grid-template-columns:minmax\(0,1fr\);/);const component=readFileSync(new URL('../components/bench-points.tsx',import.meta.url),'utf8');assert.ok(component.includes('Player name unavailable'));assert.ok(component.includes('Position unavailable'));assert.ok(component.includes('bench-player-name'));assert.ok(!component.includes('?.name||d.athleteId'));});
