import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {registerHooks} from 'node:module';
import {DatabaseSync,type SQLInputValue} from 'node:sqlite';
import test from 'node:test';
import type {DemoDraft} from '../lib/demo-draft-model';
const root=new URL('../',import.meta.url);
type AuditGlobal=typeof globalThis&{__demoDatabase?:ReturnType<typeof memoryDatabase>};
const audit=globalThis as AuditGlobal;
registerHooks({
 load(url,context,next){if(url.startsWith('file:')&&url.endsWith('.json'))return {format:'module',shortCircuit:true,source:`export default ${readFileSync(new URL(url),'utf8')}`};return next(url,context);},
 resolve(id,context,next){if(id==='@/db')return {url:`data:text/javascript,${encodeURIComponent('export function database(){return globalThis.__demoDatabase;}')}`,shortCircuit:true};if(id.startsWith('@/'))return next(new URL(`${id.slice(2)}.ts`,root).href,context);try{return next(id,context);}catch(e){if(id.startsWith('.')&&!/\.[a-z]+$/i.test(id))return next(`${id}.ts`,context);throw e;}}
});
const {newDemoDraft,demoDraftAction}=await import('../lib/demo-draft-engine');
const {demoCurrentTeam,demoPickReason,demoLineup}=await import('../lib/demo-draft-model');
const {ATHLETES,ALL_ATHLETES,LINEUP_SLOTS,eligibleForSlot}=await import('../lib/game-model');
const api=await import('../app/api/demo/route');
const {withBatch}=await import('./helpers/memory-d1-batch');
const {savedDemo}=await import('./helpers/saved-state');
function memoryDatabase(){const sql=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('drizzle/',root)).filter(f=>f.endsWith('.sql')))sql.exec(readFileSync(new URL(`drizzle/${file}`,root),'utf8'));return {sql,failWrites:false,prepare(query:string){let args:SQLInputValue[]=[];return {bind(...values:unknown[]){args=values as SQLInputValue[];return this;},async first(){return sql.prepare(query).get(...args)||null;},async all(){return {results:sql.prepare(query).all(...args)};},async run(){if(audit.__demoDatabase?.failWrites)throw new Error('PRIVATE STORAGE SECRET');return {meta:{changes:Number(sql.prepare(query).run(...args).changes)}};}};}};}
function fresh(){audit.__demoDatabase=withBatch(memoryDatabase(),{fail:()=>!!audit.__demoDatabase?.failWrites});return audit.__demoDatabase;}
function request(body?:Record<string,unknown>,user='owner',origin='https://demo.test'){return new Request('https://demo.test/api/demo',{method:body?'POST':'GET',headers:{...(user?{'oai-authenticated-user-id':user}:{}),...(origin?{origin}:{}),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});}
async function json(r:Response){return r.json() as Promise<{demo:DemoDraft|null;error?:string}>;}
function nextPlayer(s:DemoDraft,offset=0){return ATHLETES.filter(a=>!demoPickReason(s,s.humanTeamId,a.id))[offset];}

test('creates eight teams with seven computer picks and pauses on human seat eight',()=>{const s=newDemoDraft('Jonathan');assert.equal(s.scoring!.mode,'historical');assert.equal(s.teams.length,8);assert.equal(s.teams.filter(t=>t.control==='computer').length,7);assert.equal(s.order[7],s.humanTeamId);assert.equal(s.pick,7);assert.equal(demoCurrentTeam(s),s.humanTeamId);assert.equal(s.teams[7].roster.length,0);assert.ok(s.picks.every(p=>p.control==='computer'));});
test('human owns picks 8,9,24,25,40,41; all 48 picks and full valid rosters persist',()=>{let s=newDemoDraft('Human');const humanPicks:number[]=[];while(s.status==='draft'){const previous=structuredClone(s);humanPicks.push(s.pick+1);s=demoDraftAction(s,{action:'draft',athleteId:nextPlayer(s).id});assert.deepEqual(s.picks.slice(0,previous.picks.length),previous.picks);assert.equal(previous.teams[7].roster.length,humanPicks.length-1);}assert.deepEqual(humanPicks,[8,9,24,25,40,41]);assert.equal(s.pick,48);assert.equal(s.picks.length,48);assert.equal(new Set(s.picks.map(p=>p.athleteId)).size,48);assert.equal(s.picks.filter(p=>p.control==='human').length,6);for(const t of s.teams){assert.equal(t.roster.length,6);const lineup=demoLineup(t.roster);assert.equal(new Set(Object.values(lineup)).size,6);assert.ok(LINEUP_SLOTS.every(slot=>eligibleForSlot(ALL_ATHLETES.find(a=>a.id===lineup[slot]),slot)));}assert.throws(()=>demoDraftAction(s,{action:'draft',athleteId:ATHLETES[0].id}),/turn/);assert.throws(()=>demoDraftAction(s,{action:'restart'}),/cannot be restarted/);});
test('rejects duplicate ownership, double QBs, invalid FLEX without mutations',()=>{let s=newDemoDraft('Human');const untouched=JSON.stringify(s);assert.throws(()=>demoDraftAction(s,{action:'draft',athleteId:s.teams[0].roster[0]}),/Already drafted/);assert.equal(JSON.stringify(s),untouched);const qb=ATHLETES.find(a=>a.position==='QB'&&!demoPickReason(s,s.humanTeamId,a.id))!;s=demoDraftAction(s,{action:'draft',athleteId:qb.id});const otherQb=ATHLETES.find(a=>a.position==='QB'&&a.id!==qb.id&&!s.teams.some(t=>t.roster.includes(a.id)))!;assert.match(demoPickReason(s,s.humanTeamId,otherQb.id)!,/Keep room/);const illegal=structuredClone(s);const available=ATHLETES.filter(a=>a.legend&&!s.teams.some(t=>t.roster.includes(a.id)));const hall=['QB','RB','WR'].map(p=>available.find(a=>a.position===p)!);illegal.teams[7].roster=hall.slice(0,2).map(a=>a.id);assert.equal(demoPickReason(illegal,illegal.humanTeamId,hall[2].id),null);});
test('different legal human strategies all finish without stranding any computer roster',()=>{for(let n=0;n<10;n++){let s=newDemoDraft('Variation');while(s.status==='draft'){const choices=ATHLETES.filter(a=>!demoPickReason(s,s.humanTeamId,a.id));s=demoDraftAction(s,{action:'draft',athleteId:choices[(n*17+s.pick)%choices.length].id});}assert.equal(s.pick,48);}});
test('auth and origin checks; new draft only through the signed-in user context',async()=>{fresh();assert.equal((await api.GET(request(undefined,''))).status,401);assert.equal((await api.POST(request({action:'create',teamName:'Human'},''))).status,401);assert.equal((await api.POST(request({action:'create',teamName:'Human'},'owner','https://evil.test'))).status,403);assert.equal((await json(await api.GET(request()))).demo,null);const result=await api.POST(request({action:'create',teamName:'Human'}));assert.equal(result.status,201);assert.equal(demoCurrentTeam((await json(result)).demo!),((await json(await api.GET(request()))).demo!).humanTeamId);assert.equal((await json(await api.GET(request(undefined,'outsider')))).demo,null);});
test('simultaneous starts and repeat create resume exactly one saved demo; no restart',async()=>{const db=fresh();const responses=await Promise.all(['One','Two'].map(teamName=>api.POST(request({action:'create',teamName}))));const states=await Promise.all(responses.map(json));assert.equal(states[0].demo!.id,states[1].demo!.id);assert.equal(Number(db.sql.prepare('SELECT COUNT(*) AS count FROM demo_drafts').get()!.count),1);const saved=states[0].demo!;const again=(await json(await api.POST(request({action:'create',teamName:'Overwrite attempt'})))).demo!;assert.deepEqual(again,saved);assert.equal((await api.POST(request({action:'restart',revision:0}))).status,400);assert.deepEqual((await json(await api.GET(request()))).demo,saved);});
test('concurrent picks commit one human pick; stale requests return latest saved state',async()=>{fresh();const s=(await json(await api.POST(request({action:'create',teamName:'Human'})))).demo!;const responses=await Promise.all([0,1].map(offset=>api.POST(request({action:'draft',revision:0,athleteId:nextPlayer(s,offset).id}))));assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);const current=(await json(await api.GET(request()))).demo!;assert.equal(current.picks.filter(p=>p.control==='human').length,1);assert.equal(current.teams[7].roster.length,1);assert.equal(current.revision,1);assert.equal(current.picks.filter(p=>p.control==='human').length,1);const stale=await api.POST(request({action:'draft',revision:0,athleteId:nextPlayer(current).id}));assert.equal(stale.status,409);assert.deepEqual((await json(stale)).demo,current);});
test('refresh preserves exact picks and failure leaves history and other modes untouched',async()=>{const db=fresh();db.sql.prepare('INSERT INTO leagues (owner_id,state,revision,updated_at) VALUES (?,?,?,?)').run('owner','{"keep":"quick game"}',9,'now');db.sql.prepare('INSERT INTO season_leagues (id,owner_id,invite_hash,state,revision,updated_at) VALUES (?,?,?,?,?,?)').run('existing','owner','hash','{"keep":"online season"}',5,'now');let s=(await json(await api.POST(request({action:'create',teamName:'Human'})))).demo!;for(let i=0;i<2;i++){s=(await json(await api.POST(request({action:'draft',revision:s.revision,athleteId:nextPlayer(s).id})))).demo!;assert.deepEqual((await json(await api.GET(request()))).demo,s);}assert.equal(s.picks.filter(p=>p.control==='human').length,2);const frozen=JSON.stringify(s);db.failWrites=true;const r=await api.POST(request({action:'draft',revision:s.revision,athleteId:nextPlayer(s).id}));assert.equal(r.status,503);assert.ok(!(await r.text()).includes('SECRET'));assert.equal(JSON.stringify((await json(await api.GET(request()))).demo),frozen);assert.equal(db.sql.prepare('SELECT state FROM leagues').get()!.state,'{"keep":"quick game"}');assert.equal(db.sql.prepare('SELECT state FROM season_leagues').get()!.state,'{"keep":"online season"}');});

test('modern season API survives all 17 reloads and racing locks without touching another account',async()=>{const db=fresh();let s=newDemoDraft('Season owner',1,{modern:true,capacity:4,playoffTeams:4});while(s.status==='draft')s=demoDraftAction(s,{action:'draft',athleteId:nextPlayer(s).id});db.sql.prepare('INSERT INTO demo_drafts (owner_id,id,state,revision,updated_at) VALUES (?,?,?,?,?)').run('owner',s.id,JSON.stringify(s),0,'now');let response=await api.POST(request({action:'startSeason',revision:0}));assert.equal(response.status,200);for(let week=1;week<=17;week++){const current=(await savedDemo(db.sql,'owner'))!;const season=current.season!;const {currentPairs}=await import('../lib/season-view');const human=season.teams.find(t=>t.id===current.humanTeamId)!;const body=currentPairs(season).flat().includes(human.id)?{action:'lock',lineup:human.lineup,acceptBye:true}:{action:'simulate'};const responses=await Promise.all([api.POST(request({...body,revision:current.revision})),api.POST(request({...body,revision:current.revision}))]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);const saved=await(await api.GET(request())).json() as {demo:DemoDraft;league:{history:unknown[];round:number;status:string;teams:{id:string;lineup:unknown}[]}};assert.equal(saved.league.history.length,week);assert.ok(saved.league.teams.filter(t=>t.id!==current.humanTeamId).every(t=>JSON.stringify(t.lineup)==='{}'));assert.deepEqual(await(await api.GET(request())).json(),saved);if(week<17){response=await api.POST(request({action:'next',revision:saved.demo.revision}));assert.equal(response.status,200);}else assert.equal(saved.league.status,'complete');}assert.equal((await json(await api.GET(request(undefined,'other')))).demo,null);});

test('solo replay final disclosure persists independently of immutable scoring and survives navigation/reload',async()=>{const db=fresh();let s=newDemoDraft('Solo reveal',1,{modern:true,capacity:2,playoffTeams:4});while(s.status==='draft')s=demoDraftAction(s,{action:'draft',athleteId:nextPlayer(s).id});s=demoDraftAction(s,{action:'startSeason'});const human=s.season!.teams.find(t=>t.id===s.humanTeamId)!;s=demoDraftAction(s,{action:'lock',lineup:human.lineup,acceptBye:true});db.sql.prepare('INSERT INTO demo_drafts (owner_id,id,state,revision,updated_at) VALUES (?,?,?,?,?)').run('owner',s.id,JSON.stringify(s),s.revision,'now');const history=JSON.stringify(s.season!.history),used=JSON.stringify(s.season!.used);const hidden=await(await api.GET(request())).json() as {demo:DemoDraft;league:import('../lib/season-model').PublicSeason};assert.equal(hidden.league.history[0].receiptsHidden,true);assert.ok(Object.values(hidden.league.history[0].draws).flat().every(d=>Object.keys(d.performance).join()==='season'));const response=await api.POST(request({action:'revealReplay',round:1,revision:hidden.demo.revision}));assert.equal(response.status,200);const revealed=await response.json() as typeof hidden;assert.equal(revealed.league.history[0].receiptsHidden,false);assert.deepEqual(revealed.league.history[0].draws,s.season!.history[0].draws);assert.deepEqual(await(await api.GET(request())).json(),revealed);const canonical=(await savedDemo(db.sql,'owner'))!;assert.equal(JSON.stringify(canonical.season!.history),history);assert.equal(JSON.stringify(canonical.season!.used),used);assert.equal((await api.POST(request({action:'lineup',lineup:human.lineup,revision:revealed.demo.revision}))).status,400);assert.equal((await api.POST(request({action:'lock',lineup:human.lineup,revision:revealed.demo.revision}))).status,400);});

test('solo trades are owner-scoped and racing CPU offers save one response with no duplicate exchange',async()=>{const db=fresh();const {newSeason,joinSeason,seasonAction,tradePreview}=await import('../lib/season-engine');const {cpuTradeDecision}=await import('../lib/demo-draft-engine');let season=newSeason('a',{name:'Trade API',teamName:'A',capacity:2,format:'seventeen'},'test');season=joinSeason(season,'b','B');season=seasonAction(season,'a',{action:'startDraft'});while(season.status==='draft')season=seasonAction(season,'a',{action:'autopick'});const [a,b]=season.teams;season.ownerId=a.id;season.teams.forEach(t=>t.userId=t.id);const d:DemoDraft={id:season.id,revision:0,createdAt:season.createdAt,status:'complete',rosterSize:10,teams:season.teams.map((t,i)=>({id:t.id,name:t.name,control:i?'computer':'human',strategy:i?0:null,roster:t.roster})),order:season.draftOrder,pick:20,picks:[],humanTeamId:a.id,season};db.sql.prepare('INSERT INTO demo_drafts (owner_id,id,state,revision,updated_at) VALUES (?,?,?,?,?)').run('owner',d.id,JSON.stringify(d),0,d.createdAt);let pair:{give:string;receive:string}|undefined;for(const give of a.roster)for(const receive of b.roster){try{tradePreview(season,a,b,give,receive);if(cpuTradeDecision(season,b.id,give,receive).accepted)pair={give,receive};}catch{}}assert.ok(pair);const body={action:'offer',to:b.id,...pair,revision:0};assert.equal((await api.POST(request(body,'outsider'))).status,404);const responses=await Promise.all([api.POST(request(body)),api.POST(request(body))]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);const saved=JSON.parse(String(db.sql.prepare('SELECT state FROM demo_drafts WHERE owner_id=?').get('owner')!.state)) as DemoDraft;assert.equal(saved.revision,1);assert.equal(saved.season!.trades.length,1);assert.equal(saved.season!.trades[0].status,'accepted');assert.equal(new Set(saved.season!.teams.flatMap(t=>t.roster)).size,20);assert.equal((await api.POST(request({...body,revision:1}))).status,400);assert.equal(JSON.parse(String(db.sql.prepare('SELECT state FROM demo_drafts WHERE owner_id=?').get('owner')!.state)).season.trades.length,1);});

test('explicit reset atomically archives only this solo season; retries, restore and stale tabs are safe',async()=>{
 const db=fresh();let s=(await json(await api.POST(request({action:'create',teamName:'Reset owner',capacity:2})))).demo!;
 const original=String(db.sql.prepare('SELECT state FROM demo_drafts WHERE owner_id=?').get('owner')!.state);
 await api.POST(request({action:'create',teamName:'Other owner',capacity:2},'other'));
 const other=String(db.sql.prepare('SELECT state FROM demo_drafts WHERE owner_id=?').get('other')!.state);
 db.sql.prepare('INSERT INTO user_profiles VALUES (?,?,?,?)').run('owner','{"keep":"profile"}',3,'now');
 db.sql.prepare('INSERT INTO leagues VALUES (?,?,?,?)').run('owner','{"keep":"quick"}',5,'now');
 const reset={action:'reset',seasonId:s.id,revision:s.revision,confirm:true};
 assert.equal((await api.POST(request({...reset,confirm:false}))).status,400);assert.equal((await api.POST(request(reset,'other'))).status,409);
 assert.equal((await api.POST(request({...reset,revision:999}))).status,409);
 db.failWrites=true;assert.equal((await api.POST(request(reset))).status,503);db.failWrites=false;assert.equal(String(db.sql.prepare('SELECT state FROM demo_drafts WHERE owner_id=?').get('owner')!.state),original);
 const response=await api.POST(request(reset));assert.equal(response.status,200);assert.equal((await json(response)).demo,null);assert.equal(db.sql.prepare('SELECT state FROM demo_archives WHERE id=?').get(s.id)!.state,original);
 assert.equal((await api.POST(request(reset))).status,200);assert.equal((await json(await api.GET(request()))).demo,null);
 assert.equal((await api.POST(request({action:'restore',archiveId:s.id},'outsider'))).status,409);
 const restored=(await json(await api.POST(request({action:'restore',archiveId:s.id})))).demo!;assert.equal(restored.id,s.id);assert.ok(restored.revision>s.revision);assert.deepEqual(restored.picks,s.picks);assert.equal((await api.POST(request(reset))).status,409);
 s=restored;assert.equal((await api.POST(request({...reset,revision:s.revision}))).status,200);
 const freshDraft=(await json(await api.POST(request({action:'create',teamName:'New team',capacity:4,names:['A','B','C'],playoffTeams:4,receptionPoints:0,opening:true,orderMode:'manual',orderIndexes:[0,3,2,1]})))).demo!;
 assert.notEqual(freshDraft.id,s.id);assert.ok(freshDraft.revision>s.revision);assert.equal(freshDraft.pick,0);assert.equal(freshDraft.orderRevealPending,true);assert.deepEqual(freshDraft.order.map(id=>freshDraft.teams.find(t=>t.id===id)!.name),['New team','C','B','A']);
 assert.equal((await api.POST(request({action:'draft',revision:0,athleteId:ATHLETES[0].id}))).status,409);
 assert.equal((await api.POST(request(reset))).status,409);assert.equal((await api.POST(request({action:'restore',archiveId:s.id}))).status,409);
 assert.equal(String(db.sql.prepare('SELECT state FROM demo_drafts WHERE owner_id=?').get('other')!.state),other);assert.equal(db.sql.prepare('SELECT state FROM user_profiles').get()!.state,'{"keep":"profile"}');assert.equal(db.sql.prepare('SELECT state FROM leagues').get()!.state,'{"keep":"quick"}');
});

test('lottery order is saved before any picks, manually assigned order is exact, and opening cannot reroll',()=>{
 for(const capacity of [2,4,6,8,10,12,14,16]){
  const s=newDemoDraft('Human',1,{modern:true,capacity,playoffTeams:capacity<6?4:6,opening:true});assert.equal(s.pick,0);assert.equal(s.picks.length,0);assert.equal(new Set(s.order).size,capacity);const original=JSON.stringify(s.order);assert.throws(()=>demoDraftAction(s,{action:'draft',athleteId:ATHLETES[0].id}),/reveal/);
  const opened=demoDraftAction(JSON.parse(JSON.stringify(s)),{action:'beginDraft'});assert.equal(JSON.stringify(opened.order),original);assert.equal(demoCurrentTeam(opened),opened.humanTeamId);assert.deepEqual(demoDraftAction(opened,{action:'beginDraft'}),opened);
 }
 for(const orderIndexes of [[0,0],[0],[1,2],[0,1,2],[-1,1],[.5,1]])assert.throws(()=>newDemoDraft('Human',1,{modern:true,capacity:2,orderMode:'manual',orderIndexes}),/exactly one/);
 const s=newDemoDraft('Human',1,{modern:true,capacity:4,names:['One','Two','Three'],orderMode:'manual',orderIndexes:[2,0,3,1],opening:true});assert.deepEqual(s.order.map(id=>s.teams.find(t=>t.id===id)!.name),['Two','Human','Three','One']);
 const opened=demoDraftAction(s,{action:'beginDraft'});assert.equal(opened.pick,1);assert.throws(()=>demoDraftAction(opened,{action:'order',orderIndexes:[0,1,2,3]}));
});

test('racing resets archive once and a failed archive write cannot delete the active season',async()=>{
 const db=fresh(),s=(await json(await api.POST(request({action:'create',teamName:'Race',capacity:2})))).demo!,body={action:'reset',seasonId:s.id,revision:s.revision,confirm:true};
 const results=await Promise.all([api.POST(request(body)),api.POST(request(body))]);assert.ok(results.every(r=>[200,409].includes(r.status)));assert.equal(db.sql.prepare('SELECT COUNT(*) AS n FROM demo_archives').get()!.n,1);assert.equal((await json(await api.GET(request()))).demo,null);
 const next=(await json(await api.POST(request({action:'create',teamName:'Keep me',capacity:2})))).demo!;
 db.sql.exec("CREATE TRIGGER deny_archive BEFORE INSERT ON demo_archives BEGIN SELECT RAISE(ABORT,'test archive failure'); END;");
 assert.equal((await api.POST(request({action:'reset',seasonId:next.id,revision:next.revision,confirm:true}))).status,503);assert.equal((await json(await api.GET(request()))).demo!.id,next.id);
});

test('all prior backups remain discoverable and restorable after another fresh season is reset',async()=>{
 fresh();const a=(await json(await api.POST(request({action:'create',teamName:'Archive A',capacity:2,opening:true})))).demo!;
 await api.POST(request({action:'reset',seasonId:a.id,revision:a.revision,confirm:true}));
 const b=(await json(await api.POST(request({action:'create',teamName:'Archive B',capacity:2,opening:true})))).demo!;
 await api.POST(request({action:'reset',seasonId:b.id,revision:b.revision,confirm:true}));
 const empty=await(await api.GET(request())).json() as {demo:null;archives:{id:string;name:string}[]};assert.equal(empty.demo,null);assert.equal(empty.archives.length,2);assert.ok(empty.archives.some(x=>x.id===a.id&&x.name==='Archive A'));assert.ok(empty.archives.some(x=>x.id===b.id));
 const restored=(await json(await api.POST(request({action:'restore',archiveId:a.id})))).demo!;assert.equal(restored.id,a.id);assert.deepEqual(restored.order,a.order);assert.equal(restored.pick,0);assert.ok(restored.revision>b.revision);
});

test('solo saved drafts, finished drafts, lottery opening and Week 1 gameplay share the bye-free repair',async()=>{
 const {demoReply}=await import('../lib/demo-draft-engine');let s=newDemoDraft('Week one',1,{modern:true,capacity:2,opening:true});for(const id of Object.keys(s.byes!.weeks))s.byes!.weeks[id]=1;
 const old=JSON.stringify(s);const reply=demoReply(s);assert.ok(Object.values(reply.demo!.byes!.weeks).every(w=>w>1));assert.equal(JSON.stringify(s),old);
 s=demoDraftAction(s,{action:'beginDraft'});assert.ok(Object.values(s.byes!.weeks).every(w=>w>1));while(s.status==='draft')s=demoDraftAction(s,{action:'draft',athleteId:nextPlayer(s).id});for(const id of Object.keys(s.byes!.weeks))s.byes!.weeks[id]=1;assert.ok(Object.values(demoReply(s).demo!.byes!.weeks).every(w=>w>1));
 s=demoDraftAction(s,{action:'startSeason'});assert.ok(Object.values(s.season!.byes!.weeks).every(w=>w>1));const human=s.season!.teams.find(t=>t.id===s.humanTeamId)!;s=demoDraftAction(s,{action:'lock',lineup:human.lineup});const round=s.season!.history[0];assert.ok([...Object.values(round.draws).flat(),...Object.values(round.benchDraws||{}).flat()].every(d=>!d.simulatedBye));assert.equal(s.season!.used.length,20);
});
