import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {registerHooks} from 'node:module';
import {DatabaseSync,type SQLInputValue} from 'node:sqlite';
import test from 'node:test';
const root=new URL('../',import.meta.url);
type Audit=typeof globalThis&{__preferencesDB?:ReturnType<typeof memoryDatabase>};const audit=globalThis as Audit;
registerHooks({load(url,context,next){if(url.startsWith('file:')&&url.endsWith('.json'))return {format:'module',shortCircuit:true,source:`export default ${readFileSync(new URL(url),'utf8')}`};return next(url,context);},resolve(id,context,next){if(id==='@/db')return {url:`data:text/javascript,${encodeURIComponent('export function database(){return globalThis.__preferencesDB;}')}`,shortCircuit:true};if(id.startsWith('@/'))return next(new URL(`${id.slice(2)}.ts`,root).href,context);try{return next(id,context);}catch(e){if(id.startsWith('.')&&!/\.[a-z]+$/i.test(id))return next(`${id}.ts`,context);throw e;}}});
const api=await import('../app/api/draft-preferences/route');
const {ATHLETES}=await import('../lib/game-model');
const {emptyPreferences,updatePreferences}=await import('../lib/draft-preferences');
function memoryDatabase(){const sql=new DatabaseSync(':memory:');for(const file of readdirSync(new URL('drizzle/',root)).filter(f=>f.endsWith('.sql')))sql.exec(readFileSync(new URL(`drizzle/${file}`,root),'utf8'));return {sql,failWrites:false,prepare(query:string){let args:SQLInputValue[]=[];return {bind(...values:unknown[]){args=values as SQLInputValue[];return this;},async first(){return sql.prepare(query).get(...args)||null;},async run(){if(audit.__preferencesDB?.failWrites)throw new Error('PRIVATE SECRET');return {meta:{changes:Number(sql.prepare(query).run(...args).changes)}};}};}};}
function fresh(){const db=memoryDatabase();audit.__preferencesDB=db;db.sql.prepare('INSERT INTO demo_drafts (owner_id,id,state,revision,updated_at) VALUES (?,?,?,?,?)').run('owner','demo-id','{"pick":7}',0,'now');db.sql.prepare('INSERT INTO leagues (owner_id,state,revision,updated_at) VALUES (?,?,?,?)').run('owner','{"id":"quick-id","turn":0}',0,'now');db.sql.prepare('INSERT INTO season_leagues (id,owner_id,invite_hash,state,revision,updated_at) VALUES (?,?,?,?,?,?)').run('season-id','owner','hash','{"teams":[{"userId":"owner"},{"userId":"manager"}]}',0,'now');return db;}
function request(scope='demo:demo-id',body?:Record<string,unknown>,user='owner',origin='https://test.site'){return new Request(`https://test.site/api/draft-preferences?scope=${encodeURIComponent(scope)}`,{method:body?'POST':'GET',headers:{...(user?{'oai-authenticated-user-id':user}:{}),origin,'Content-Type':'application/json'},body:body?JSON.stringify({...body,scope}):undefined});}
async function payload(r:Response){return r.json() as Promise<{preferences:ReturnType<typeof emptyPreferences>;error?:string}>;}
const ids=ATHLETES.slice(0,2).map(a=>a.id);
test('queue reads require authenticated draft ownership and do not create or mutate picks',async()=>{const db=fresh();assert.equal((await api.GET(request('demo:demo-id',undefined,''))).status,401);assert.equal((await api.GET(request('demo:demo-id',undefined,'outsider'))).status,404);assert.equal((await api.GET(request('season:season-id',undefined,'manager'))).status,200);assert.deepEqual((await payload(await api.GET(request()))).preferences,emptyPreferences());assert.equal(db.sql.prepare('SELECT COUNT(*) n FROM draft_preferences').get()!.n,0);assert.equal(db.sql.prepare('SELECT state FROM demo_drafts').get()!.state,'{"pick":7}');});
test('private queues persist, reorder, survive refresh and reject stale or cross-origin changes',async()=>{fresh();assert.equal((await api.POST(request('demo:demo-id',{action:'toggle',athleteId:ids[0],revision:0},'owner','https://other.site'))).status,403);let p=(await payload(await api.POST(request('demo:demo-id',{action:'toggle',athleteId:ids[0],revision:0})))).preferences;assert.deepEqual(p.queue,[ids[0]]);assert.equal(p.revision,1);const conflict=await api.POST(request('demo:demo-id',{action:'toggle',athleteId:ids[1],revision:0}));assert.equal(conflict.status,409);assert.deepEqual((await payload(conflict)).preferences,p);p=(await payload(await api.POST(request('demo:demo-id',{action:'toggle',athleteId:ids[1],revision:1})))).preferences;p=(await payload(await api.POST(request('demo:demo-id',{action:'move',athleteId:ids[1],direction:-1,revision:2})))).preferences;assert.deepEqual(p.queue,[ids[1],ids[0]]);assert.deepEqual((await payload(await api.GET(request()))).preferences,p);assert.deepEqual((await payload(await api.GET(request('quick:quick-id:0')))).preferences.queue,[]);});
test('league members cannot see each other’s personal queues',async()=>{fresh();await api.POST(request('season:season-id',{action:'toggle',athleteId:ids[0],revision:0}));assert.deepEqual((await payload(await api.GET(request('season:season-id',undefined,'manager')))).preferences.queue,[]);assert.deepEqual((await payload(await api.GET(request('season:season-id')))).preferences.queue,[ids[0]]);});
test('timer settings and queue changes never modify demo, match, or league state; failures are safe',async()=>{const db=fresh();const before=['demo_drafts','leagues','season_leagues'].map(table=>db.sql.prepare(`SELECT state FROM ${table}`).get()!.state);for(const [index,seconds] of [60,90,120,0].entries()){const r=await api.POST(request('demo:demo-id',{action:'timer',seconds,revision:index}));assert.equal(r.status,200);assert.equal((await payload(r)).preferences.timerSeconds,seconds);}assert.deepEqual(['demo_drafts','leagues','season_leagues'].map(table=>db.sql.prepare(`SELECT state FROM ${table}`).get()!.state),before);db.failWrites=true;const failed=await api.POST(request('demo:demo-id',{action:'toggle',athleteId:ids[0],revision:4}));assert.equal(failed.status,503);assert.ok(!(await failed.text()).includes('SECRET'));assert.deepEqual((await payload(await api.GET(request()))).preferences.queue,[]);assert.throws(()=>updatePreferences(emptyPreferences(),{action:'timer',seconds:1}),/timer/);assert.throws(()=>updatePreferences(emptyPreferences(),{action:'toggle',athleteId:'bogus'}),/verified/);});
