import assert from 'node:assert/strict';
import test from 'node:test';
import {registerHooks} from 'node:module';
registerHooks({resolve(id,context,next){try{return next(id,context);}catch(e){if(id.startsWith('.')&&!/\.[a-z]+$/i.test(id))return next(`${id}.ts`,context);throw e;}}});
const {fantasyReplay,replayScore,cents}=await import('../lib/fantasy-replay');
import type {SeasonRound,Match} from '../lib/season-model';
const points=[21.37,-2.3,0,7.01,4.5,15.99];
const draws=(team:string)=>points.map((points,i)=>({athleteId:`${team}-${i}`,points,slot:['QB','RB','WR','TE','DEF','FLEX'][i],performance:{id:`p-${team}-${i}`}}));
const total=points.reduce((s,p)=>s+cents(p),0)/100;
const match:Match={home:'h',away:'a',homeScore:total,awayScore:total,winner:null};
const round={number:2,phase:'regular',resolvedAt:'saved',matches:[match],draws:{h:draws('h'),a:draws('a')}} as unknown as SeasonRound;
test('four deterministic fictional quarters reconcile all fractional, zero and negative player contributions',()=>{const before=JSON.stringify(round),events=fantasyReplay(round,match);assert.deepEqual([...new Set(events.map(e=>e.quarter))],[1,2,3,4]);assert.equal(events.length,24);for(const team of ['h','a']){assert.equal(replayScore(events,events.length,team),total);for(const d of round.draws[team])assert.equal(events.filter(e=>e.athleteId===d.athleteId).reduce((s,e)=>s+e.delta,0),cents(d.points));}assert.ok(events.some(e=>e.delta<0));assert.equal(JSON.stringify(round),before);});
test('watch, skip, replay, reload, and repeated actions always converge to exact saved score without mutations',()=>{const before=JSON.stringify(round);for(let i=0;i<12;i++){const reloaded=JSON.parse(before),events=fantasyReplay(reloaded,reloaded.matches[0]);for(let s=0;s<=events.length;s++){assert.ok(Number.isFinite(replayScore(events,s,'h')));assert.equal(replayScore(events,s,'h'),replayScore(fantasyReplay(round,match),s,'h'));}assert.equal(replayScore(events,10000,'a'),match.awayScore);assert.equal(replayScore(events,0,'h'),0);}assert.equal(JSON.stringify(round),before);});
test('saved winner and legacy total discrepancies are not recalculated',()=>{const m={...match,awayScore:total+.01,winner:'a'};const events=fantasyReplay(round,m);assert.equal(events.at(-1)?.label,'Saved-total reconciliation');assert.equal(replayScore(events,events.length,'a'),m.awayScore);assert.equal(m.winner,'a');});

test('actual historical year and NFL week stay attached to every replay event and survive reload',async()=>{const {historicalDrawLabel}=await import('../lib/fantasy-replay');const saved=structuredClone(round);saved.draws.h[0].performance={...saved.draws.h[0].performance,season:2004,week:8,seasonType:'REG'};saved.draws.a[0].performance={...saved.draws.a[0].performance,season:1999,week:20,seasonType:'POST'};const original=JSON.stringify(saved),events=fantasyReplay(saved,match);assert.equal(saved.number,2);assert.ok(events.filter(e=>e.athleteId==='h-0').every(e=>e.historicalGame==='2004 season · NFL Week 8'));assert.ok(events.filter(e=>e.athleteId==='a-0').every(e=>e.historicalGame==='1999 season · NFL Week 20 · Playoffs'));assert.deepEqual(fantasyReplay(JSON.parse(original),match),events);assert.equal(historicalDrawLabel(null),'Historical game unavailable');assert.equal(historicalDrawLabel({season:1972}),'1972 season · NFL week unavailable');assert.equal(historicalDrawLabel({week:0}),'Season unavailable · NFL week unavailable');assert.equal(JSON.stringify(saved),original);assert.equal(replayScore(events,events.length,'h'),match.homeScore);});
