import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {registerHooks} from 'node:module';
import test from 'node:test';
registerHooks({load(url,c,n){if(url.startsWith('file:')&&url.endsWith('.json'))return {format:'module',shortCircuit:true,source:`export default ${readFileSync(new URL(url),'utf8')}`};return n(url,c);},resolve(id,c,n){try{return n(id,c);}catch(e){if(id.startsWith('.')&&!/\.[a-z]+$/i.test(id))return n(`${id}.ts`,c);throw e;}}});
const {ATHLETES,PERFORMANCES,athletesFor,score,scoringBreakdown,lineupSlots,statLine}=await import('../lib/historical-data');const {newScoring,LEGACY_SCORING}=await import('../lib/scoring-rules');const {newSeason,joinSeason,seasonAction,publicSeason}=await import('../lib/season-engine');const {newDemoDraft,demoDraftAction,demoReply}=await import('../lib/demo-draft-engine');const {demoPickReason,demoRosterSize}=await import('../lib/demo-draft-model');const {seasonRosterSize}=await import('../lib/season-model');const {draftRankings}=await import('../lib/draft-insights');
const kickers=ATHLETES.filter(a=>a.position==='K'),ids=new Set(kickers.map(a=>a.id)),games=PERFORMANCES.filter(p=>ids.has(p.athleteId)),rules=newScoring(1,true);
function drafted(kickersEnabled:boolean){let s=newSeason('a',{name:'K test',teamName:'A',capacity:2,format:'seventeen',kickers:kickersEnabled},'CODE');s=joinSeason(s,'b','B');s=seasonAction(s,'a',{action:'startDraft'});while(s.status==='draft')s=seasonAction(s,'a',{action:'autopick'});return s;}
test('verified K extension preserves 60,166 old rows and adds exactly 40 identities / 8,353 real complete performances',()=>{assert.equal(kickers.length,40);assert.equal(games.length,8353);assert.equal(new Set(games.map(g=>g.id)).size,8353);assert.equal(PERFORMANCES.filter(p=>!ids.has(p.athleteId)).length,60166);assert.ok(kickers.every(a=>a.gameCount>=17));const oldIds=new Set(PERFORMANCES.filter(p=>!ids.has(p.athleteId)).map(p=>p.gameId));for(const g of games){assert.ok(oldIds.has(g.gameId));assert.equal(g.fictional,false);assert.ok(g.season>=1999&&g.season<=2026);assert.ok(g.date<='2026-09-28');assert.ok([g.stats.fieldGoalsShort,g.stats.fieldGoals40,g.stats.fieldGoals50,g.stats.fieldGoalsMissed,g.stats.fieldGoalsBlocked,g.stats.extraPointsMade,g.stats.extraPointsMissed,g.stats.extraPointsBlocked].every(n=>typeof n==='number'&&Number.isFinite(n)&&n>=0));const total=scoringBreakdown(g.stats,'K',rules).reduce((s,i)=>s+i.points,0);assert.equal(Math.round(total*100)/100,score(g.stats,'K',rules));}assert.ok(games.some(g=>g.stats.extraPointsMade===0&&g.stats.fieldGoalsShort===0&&g.stats.fieldGoals40===0&&g.stats.fieldGoals50===0));});
test('approved kicking tiers, unsuccessful blocks, and real fake-kick offense score exactly once',()=>{const base={...games[0].stats,passingYards:0,passingTD:0,interceptions:0,rushingYards:0,rushingTD:0,receptions:0,receivingYards:0,receivingTD:0,fumblesLost:0,twoPoint:0,returnTD:0,fumbleRecoveryTD:0,fieldGoalsShort:1,fieldGoals40:1,fieldGoals50:1,fieldGoalsMissed:1,fieldGoalsBlocked:1,extraPointsMade:1,extraPointsMissed:1,extraPointsBlocked:1};assert.equal(score(base,'K',rules),9);assert.throws(()=>score(base,'K',LEGACY_SCORING),/not enabled/);assert.throws(()=>score({...base,fieldGoals40:undefined},'K',rules),/Complete verified/);const fake=games.find(g=>g.athleteId==='00-0016919'&&g.gameId==='2004_09_NE_STL')!;assert.equal(fake.stats.passingYards,4);assert.equal(fake.stats.passingTD,1);assert.ok(statLine(fake).includes('pass TD'));assert.equal(Math.round((score(fake.stats,'K',rules)-score({...fake.stats,passingYards:0,passingTD:0},'K',rules))*100)/100,4.16);const tucker=games.find(g=>g.gameId==='2021_03_BAL_DET'&&ATHLETES.find(a=>a.id===g.athleteId)?.name==='Justin Tucker')!;assert.equal(tucker.stats.fieldGoalsShort,2);assert.equal(tucker.stats.fieldGoals50,2);assert.equal(score(tucker.stats,'K',rules),16);});
test('new solo K season drafts eleven, keeps seven starters and four bench, and survives every week with frozen rules',()=>{let d=newDemoDraft('My kicker team',.5,{modern:true,capacity:2,playoffTeams:4,kickers:true,opening:true});assert.equal(demoRosterSize(d),11);assert.equal(d.scoring!.version,5);d=demoDraftAction(d,{action:'beginDraft'});while(d.status==='draft'){const p=ATHLETES.find(a=>!demoPickReason(d,d.humanTeamId,a.id))!;d=demoDraftAction(d,{action:'draft',athleteId:p.id});}assert.equal(d.pick,22);assert.ok(d.teams.every(t=>t.roster.length===11&&t.roster.some(id=>ids.has(id))));d=demoDraftAction(d,{action:'startSeason'});const originalScoring=JSON.stringify(d.season!.scoring);for(let week=1;week<=17;week++){const s=d.season!,me=s.teams.find(t=>t.id===d.humanTeamId)!;assert.equal(s.lineupVersion,3);assert.equal(lineupSlots(s).length,7);assert.equal(Object.values(me.lineup).length,7);assert.equal(s.teams.every(t=>t.roster.length===11),true);assert.equal(JSON.stringify(s.scoring),originalScoring);d=demoDraftAction(d,{action:'lock',lineup:me.lineup,acceptBye:true});const round=d.season!.history.at(-1)!;assert.ok(Object.values(round.draws).every(draws=>draws.length===7&&draws.some(x=>x.slot==='K')));assert.ok(Object.values(round.benchDraws!).every(draws=>draws.length===4));assert.equal(round.lineupVersion,3);assert.equal(round.scoring!.version,5);assert.equal(new Set(d.season!.used).size,d.season!.used.length);{const pub=demoReply(d);assert.ok('league' in pub);assert.equal(pub.league!.history.at(-1)!.receiptsHidden,true);};if(week<17)d=demoDraftAction(d,{action:'next'});}assert.equal(d.season!.status,'complete');});
test('legacy contracts reject K picks and swaps, keep six starters/ten rosters, and legacy rankings skip K scores',()=>{let s=drafted(false);const snapshot=JSON.stringify(s);assert.equal(seasonRosterSize(s),10);assert.equal(lineupSlots(s).length,6);assert.throws(()=>seasonAction(s,'a',{action:'swap',drop:s.teams[0].roster[0],add:kickers[0].id}),/new 11-player/);assert.equal(JSON.stringify(s),snapshot);s=seasonAction(s,'a',{action:'closeRound'});s=seasonAction(s,'a',{action:'next'});assert.equal(s.lineupVersion,2);assert.equal(s.scoring!.version,5);const d=newDemoDraft('Legacy draft',1,{modern:true,capacity:2});assert.match(demoPickReason(d,d.humanTeamId,kickers[0].id)!,/new 11-player/);assert.ok(draftRankings([],LEGACY_SCORING).filter(r=>ids.has(r.athleteId)).every(r=>r.average===null));});
test('online K lobby edits preserve approved scoring; K trades/free agents and byes retain identities and contracts',()=>{let s=newSeason('a',{name:'K lobby',teamName:'A',capacity:2,format:'seventeen',kickers:true},'CODE');s=joinSeason(s,'b','B');s=seasonAction(s,'a',{action:'rules',receptionPoints:0});assert.equal(s.scoring!.version,5);assert.equal(s.scoring!.kicking!.unsuccessful,-1);s=seasonAction(s,'a',{action:'startDraft'});while(s.status==='draft')s=seasonAction(s,'a',{action:'autopick'});assert.equal(s.lineupVersion,3);const [a,b]=s.teams,ka=a.lineup.K,kb=b.lineup.K,byes=JSON.stringify(s.byes);s=seasonAction(s,'a',{action:'offer',to:b.id,give:ka,receive:kb});s=seasonAction(s,'b',{action:'accept',tradeId:s.trades[0].id});assert.ok(s.teams[0].roster.includes(kb));assert.ok(s.teams[1].roster.includes(ka));const free=kickers.find(k=>!s.teams.some(t=>t.roster.includes(k.id)))!;s=seasonAction(s,'a',{action:'swap',drop:kb,add:free.id});assert.equal(JSON.stringify(s.byes),byes);assert.ok(Object.values(s.byes!.weeks).every(w=>w>1&&w<s.regularRounds));assert.equal(s.used.length,0);const pub=publicSeason(s,'b');assert.deepEqual(pub.teams.find(t=>t.id===a.id)!.lineup,{});});
test('sixteen-team draft reserves a unique kicker for every team and completes eleven rounds',()=>{let s=newSeason('owner',{name:'Sixteen K teams',teamName:'Team 0',capacity:16,format:'seventeen',playoffTeams:6,kickers:true},'CODE');for(let i=1;i<16;i++)s=joinSeason(s,`u${i}`,`Team ${i}`);s=seasonAction(s,'owner',{action:'startDraft',orderMode:'manual',orderIndexes:Array.from({length:16},(_,i)=>i)});while(s.status==='draft')s=seasonAction(s,'owner',{action:'autopick'});assert.equal(s.pick,176);assert.equal(s.lineupVersion,3);assert.ok(s.teams.every(t=>t.roster.length===11&&ids.has(t.lineup.K)));assert.equal(new Set(s.teams.flatMap(t=>t.roster)).size,176);});

test('both draft engines reject the backup-K pick that would strand another team',()=>{
 const allAthletes=[...ATHLETES];ATHLETES.splice(0,ATHLETES.length,...allAthletes.filter(a=>a.position!=='K'||kickers.slice(0,20).some(k=>k.id===a.id)));try{
 let s=newSeason('owner',{name:'K reserve',teamName:'Team 0',capacity:16,format:'seventeen',kickers:true,scoringMode:'strict'},'CODE');for(let i=1;i<16;i++)s=joinSeason(s,`u${i}`,`Team ${i}`);s=seasonAction(s,'owner',{action:'startDraft',orderMode:'manual',orderIndexes:Array.from({length:16},(_,i)=>i)});for(let i=0;i<4;i++)s.teams[i].roster=[kickers[i*2].id,kickers[i*2+1].id];s.teams[4].roster=[kickers[8].id];s.pick=4;const before=JSON.stringify(s);assert.throws(()=>seasonAction(s,'u4',{action:'draft',athleteId:kickers[9].id}),/Keep a kicker available/);assert.equal(JSON.stringify(s),before);
 const d=newDemoDraft('Human',1,{modern:true,capacity:16,kickers:true,opening:true,scoringMode:'strict'});const others=d.teams.filter(t=>t.id!==d.humanTeamId);for(let i=0;i<4;i++)others[i].roster=[kickers[i*2].id,kickers[i*2+1].id];d.teams.find(t=>t.id===d.humanTeamId)!.roster=[kickers[8].id];assert.match(demoPickReason(d,d.humanTeamId,kickers[9].id)!,/Keep a kicker available/);
 }finally{ATHLETES.splice(0,ATHLETES.length,...allAthletes);}
});

test('legacy K scouting is explicitly unsupported, not a numeric zero or a formatting crash',async()=>{const {draftInsights}=await import('../lib/draft-insights');const legacy=draftInsights(kickers[0].id,[],LEGACY_SCORING)!;assert.equal(legacy.scoringSupported,false);assert.equal(legacy.count,kickers[0].gameCount);assert.equal(legacy.average,null);assert.equal(legacy.gameAverage,null);const enabled=draftInsights(kickers[0].id,[],rules)!;assert.ok(Number.isFinite(enabled.average));assert.ok(Number.isFinite(enabled.low));});

test('40-K pool covers every bye ownership split with at least three healthy free agents at the two-K roster limit',()=>{
 const teams=16,kickersPerTeam=2,maximumOwned=teams*kickersPerTeam;
 assert.equal(kickers.length,40);assert.ok(kickers.every(k=>k.gameCount-17>=17));
 let minimumHealthyBaseline=Infinity;
 for(const mode of ['strict','historical'] as const)for(const qualifiers of [4,6] as const){
  const modeKickers=athletesFor(newScoring(1,true,mode)).filter(a=>a.position==='K');assert.deepEqual(new Set(modeKickers.map(a=>a.id)),ids);
  const season=newSeason('owner',{name:'Coverage proof',teamName:'Owner',capacity:teams,format:'seventeen',playoffTeams:qualifiers,kickers:true,scoringMode:mode},'CODE');
  for(let week=1;week<=17;week++){
   const resting=modeKickers.filter(k=>season.byes!.weeks[k.id]===week),healthy=modeKickers.filter(k=>season.byes!.weeks[k.id]!==week),byeCount=resting.length;
   if(week<=4||week>=season.regularRounds)assert.equal(byeCount,0);
   const baseline=modeKickers.length-maximumOwned-byeCount;minimumHealthyBaseline=Math.min(minimumHealthyBaseline,baseline);assert.ok(baseline>=3);
   // Use actual scheduled kicker identities. Pairing owned bye kickers together
   // gives the greatest possible number of teams with both rostered kickers out.
   for(let rosteredBye=0;rosteredBye<=byeCount;rosteredBye++){
    const owned=[...resting.slice(0,rosteredBye),...healthy.slice(0,maximumOwned-rosteredBye)],ownedIds=new Set(owned.map(k=>k.id));
    assert.equal(ownedIds.size,maximumOwned);
    const rosters=Array.from({length:teams},(_,index)=>owned.slice(index*kickersPerTeam,(index+1)*kickersPerTeam));
    const needsReplacement=rosters.filter(roster=>roster.every(k=>season.byes!.weeks[k.id]===week));
    const free=modeKickers.filter(k=>!ownedIds.has(k.id)),healthyFree=free.filter(k=>season.byes!.weeks[k.id]!==week);
    assert.equal(free.length,8);assert.equal(healthyFree.length,8-(byeCount-rosteredBye));assert.equal(needsReplacement.length,Math.floor(rosteredBye/2));
    assert.ok(healthyFree.length>=needsReplacement.length,`${mode}, ${qualifiers} playoffs, Week ${week}, ${rosteredBye} owned bye kickers`);
    const replacements=healthyFree.slice(0,needsReplacement.length);assert.equal(new Set(replacements.map(k=>k.id)).size,needsReplacement.length);
    assert.ok(replacements.every(k=>!ownedIds.has(k.id)&&season.byes!.weeks[k.id]!==week));
   }
  }
 }
 assert.equal(minimumHealthyBaseline,3,'The nine-week bye window reduces the previous four-player padding to three');
});
