import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {registerHooks} from 'node:module';
import {DatabaseSync,type SQLInputValue} from 'node:sqlite';
import test from 'node:test';
// Migration 0008 against rows saved by the previous app version (tests/fixtures/pre-0008-saved-rows.json,
// regenerated by scripts/qa/generate-pre-0008-fixture.mts). It must rename only game IDs and source fields,
// keep every name, score, consumed game and revision, change nothing on a second run, and leave the saves
// playable by the current code with their stored revisions.
const root=new URL('../',import.meta.url);
type MigrationGlobal=typeof globalThis&{__migrationDatabase?:unknown};
registerHooks({
 load(url,context,next){if(url.startsWith('file:')&&url.endsWith('.json'))return {format:'module',shortCircuit:true,source:`export default ${readFileSync(new URL(url),'utf8')}`};return next(url,context);},
 resolve(id,context,next){if(id==='@/db')return {url:`data:text/javascript,${encodeURIComponent('export function database(){return globalThis.__migrationDatabase;}')}`,shortCircuit:true};if(id.startsWith('@/'))return next(new URL(`${id.slice(2)}.ts`,root).href,context);try{return next(id,context);}catch(e){if(id.startsWith('.')&&!/\.[a-z]+$/i.test(id))return next(`${id}.ts`,context);throw e;}}
});
const {performancePool}=await import('../lib/historical-data');
const {LEGACY_SCORING}=await import('../lib/scoring-rules');
const quick=await import('../app/api/game/route');
const leagueRoute=await import('../app/api/leagues/[id]/route');
const demo=await import('../app/api/demo/route');

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Json=any;
type Row=Record<string,SQLInputValue>;
const fixture=JSON.parse(readFileSync(new URL('tests/fixtures/pre-0008-saved-rows.json',root),'utf8')) as {meta:{appCommit:string;names:Record<string,string>};tables:Record<string,Row[]>};
const TABLES=['leagues','season_leagues','demo_drafts','demo_archives','demo_scoring_backups'];
const HISTORICAL={...LEGACY_SCORING,mode:'historical' as const};
const MIGRATION=readFileSync(new URL('drizzle/0008_rename_historical_performance_ids.sql',root),'utf8').split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean);
const OLD_BLOB='https://github.com/Jonathan94110/prime-rushmore/blob/';
const OLD_SHEET=/^https:\/\/github\.com\/Jonathan94110\/prime-rushmore\/blob\/([0-9a-f]{40})\/fantasy-legends\/data\/sheets\/([^/#]+\.csv)#L(\d+)$/;
const OLD_REPORT=/^https:\/\/github\.com\/Jonathan94110\/prime-rushmore\/blob\/[0-9a-f]{40}\/fantasy-legends\/VALIDATION_REPORT\.md$/;

function seeded(rows=fixture.tables){
 const sql=new DatabaseSync(':memory:');
 for(const file of readdirSync(new URL('drizzle/',root)).filter(f=>/^000[0-7]_.*\.sql$/.test(f)).sort())sql.exec(readFileSync(new URL(`drizzle/${file}`,root),'utf8'));
 for(const table of TABLES)for(const row of rows[table]??[]){const cols=Object.keys(row);sql.prepare(`INSERT INTO ${table} (${cols.join(',')}) VALUES (${cols.map(()=>'?').join(',')})`).run(...cols.map(c=>row[c]));}
 return sql;
}
/** Runs 0008 statement by statement, as the D1 migrators do, and returns each statement's row changes. */
const migrate=(sql:DatabaseSync)=>MIGRATION.map(statement=>Number(sql.prepare(statement).run().changes));
const dump=(sql:DatabaseSync)=>Object.fromEntries(TABLES.map(t=>[t,sql.prepare(`SELECT * FROM ${t} ORDER BY rowid`).all() as Row[]]));
const parse=(row:Row):Json=>JSON.parse(String(row.state));
const seasonOf=(table:string,state:Json):Json=>table.startsWith('demo_')?state.season:state;

// The expected result, written independently of the SQL: change exactly performance.id, performance.sourceUrl,
// performance.sourceUrls and the entries of `used`, at the paths the engines write them (lib/game-engine.ts
// and lib/season-engine.ts), keeping key order. Old forms follow commit 63d6379 lib/historical-data.ts.
const renameId=(id:Json)=>typeof id==='string'&&id.startsWith('prime-rushmore:')?`historical:${id.slice('prime-rushmore:'.length)}`:id;
function renameUrl(url:Json){if(typeof url!=='string')return url;if(OLD_REPORT.test(url))return '/historical-coverage.json';const m=OLD_SHEET.exec(url);return m?`/historical-coverage.json#${m[1]}/${m[2]}:L${m[3]}`:url;}
const renamePerformance=(p:Json)=>p&&typeof p.id==='string'?{...p,id:renameId(p.id),...('sourceUrl' in p?{sourceUrl:renameUrl(p.sourceUrl)}:{}),...(Array.isArray(p.sourceUrls)?{sourceUrls:p.sourceUrls.map(renameUrl)}:{})}:p;
const renameDraws=(draws:Json)=>draws&&Object.fromEntries(Object.entries(draws).map(([k,list])=>[k,(list as Json[]).map(d=>d&&d.performance?{...d,performance:renamePerformance(d.performance)}:d)]));
function renameGames(s:Json){if(!s)return s;const out={...s};if(Array.isArray(s.used))out.used=s.used.map(renameId);if(Array.isArray(s.history))out.history=s.history.map((r:Json)=>({...r,...(r.draws?{draws:Array.isArray(r.draws)?r.draws.map((list:Json[])=>list.map(d=>d&&d.performance?{...d,performance:renamePerformance(d.performance)}:d)):renameDraws(r.draws)}:{}),...(r.benchDraws?{benchDraws:renameDraws(r.benchDraws)}:{})}));return out;}
function expected(table:string,state:Json){if(table==='demo_scoring_backups')return state;return table.startsWith('demo_')?(state.season?{...state,season:renameGames(state.season)}:state):renameGames(state);}

// Every user-typed or name-derived string the state can hold (league, team and season names; activity text).
function userText(state:Json){const s=(x:Json)=>x&&[x.name,(x.teams??[]).map((t:Json)=>t.name),(x.activity??[]).map((a:Json)=>a.text)];return JSON.stringify([s(state),s(state.season)]);}
function withoutUserText(state:Json){const copy=structuredClone(state);for(const x of [copy,copy.season].filter(Boolean)){delete x.name;for(const t of x.teams??[])delete t.name;for(const a of x.activity??[])delete a.text;}return copy;}
function performances(s:Json):Json[]{const out:Json[]=[];for(const r of s?.history??[])for(const draws of [r.draws,r.benchDraws])for(const list of Object.values(draws??{}))for(const d of list as Json[])if(d?.performance?.id)out.push(d.performance);return out;}
/** The 0008 replacements before this change, applied to all text: kept only to show the fixture would catch them. */
const blanket=(text:string)=>text.replaceAll('"prime-rushmore:','"historical:').replaceAll(`${OLD_BLOB}bbfc22cc51b0f0a80aff2c1d6d7f4d32b219d356/fantasy-legends/VALIDATION_REPORT.md`,'/historical-coverage.json').replaceAll(`${OLD_BLOB}bbfc22cc51b0f0a80aff2c1d6d7f4d32b219d356/fantasy-legends/data/sheets/`,'/historical-coverage.json#bbfc22cc51b0f0a80aff2c1d6d7f4d32b219d356/').replaceAll('.csv#L','.csv:L');
const hasGames=(table:string,row:Row)=>table!=='demo_scoring_backups'&&String(row.state).includes('"id":"prime-rushmore:');

test('fixture holds pre-0008 saves: old IDs and links, consumed games, scores, revisions and risky names',()=>{
 assert.equal(fixture.meta.appCommit,'63d6379');
 for(const table of TABLES)assert.ok(fixture.tables[table].length>0,`${table} has rows`);
 let played=0;
 for(const table of TABLES)for(const row of fixture.tables[table]){
  const state=parse(row);
  assert.equal(row[table==='demo_scoring_backups'?'source_revision':'revision'],state.revision,`${table}: revision column matches state.revision`);
  if(!hasGames(table,row))continue;
  played++;
  const s=seasonOf(table,state);
  assert.ok(row.revision as number>0,`${table}: revision bumped by the API`);
  assert.equal(String(row.state),JSON.stringify(state),`${table}: saved as compact JSON.stringify output`);
  assert.ok(s.used[0].startsWith('prime-rushmore:')||s.used.some((id:string)=>id.startsWith('prime-rushmore:')),`${table}: consumed historical games`);
  assert.ok(s.history.some((r:Json)=>(r.matches??[]).length||r.totals),`${table}: scored rounds`);
  const old=performances(s).filter(p=>p.id.startsWith('prime-rushmore:'));
  assert.ok(old.length>0&&old.every(p=>OLD_SHEET.test(p.sourceUrl)&&OLD_SHEET.test(p.sourceUrls[0])&&OLD_REPORT.test(p.sourceUrls[1])),`${table}: old source links`);
  assert.deepEqual(new Set(s.used),new Set(performances(s).map(p=>p.id)),`${table}: used matches the games in history`);
 }
 assert.equal(played,4,'quick game, online season, solo season and its archive');
 assert.ok(fixture.tables.season_leagues.some(r=>!hasGames('season_leagues',r)&&parse(r).history.length>0),'a played strict season with no historical games');
 assert.ok(String(fixture.tables.demo_scoring_backups[0].state).startsWith('{\n'),'a pretty-printed raw backup');
 // Negative control: the replacements this change removes would alter names in four of the five tables.
 for(const table of ['season_leagues','demo_drafts','demo_archives','demo_scoring_backups'])assert.ok(fixture.tables[table].some(row=>userText(parse(row))!==userText(JSON.parse(blanket(String(row.state))))),`${table}: a blanket replacement would change a name`);
});

test('0008 renames only game IDs and source fields; names, scores, other columns and backups stay exact',()=>{
 const sql=seeded(),before=dump(sql),changes=migrate(sql),after=dump(sql);
 let migrated=0,modern=0;
 for(const table of TABLES)before[table].forEach((row,i)=>{
  const out=after[table][i],state=parse(row);
  for(const col of Object.keys(row))if(col!=='state')assert.equal(out[col],row[col],`${table}.${col} unchanged`);
  const now=parse(out);
  assert.equal(userText(now),userText(state),`${table}[${i}]: names and activity text unchanged`);
  const want=expected(table,state);
  if(JSON.stringify(want)===JSON.stringify(state))assert.equal(out.state,row.state,`${table}[${i}]: untouched rows stay byte-identical`);
  else assert.equal(out.state,JSON.stringify(want),`${table}[${i}]: exactly the expected game-ID and source-field changes`);
  assert.equal(now.revision,out[table==='demo_scoring_backups'?'source_revision':'revision'],`${table}[${i}]: revision column still matches state.revision`);
  assert.ok(!JSON.stringify(withoutUserText(now)).includes('prime-rushmore'),`${table}[${i}]: only typed names may still say prime-rushmore`);
  const s=seasonOf(table,now);if(!s?.history)return;
  const priorPerformances=new Map(performances(seasonOf(table,state)).map(p=>[renameId(p.id),p]));
  for(const p of performances(s)){
   if(p.id.startsWith('nflverse:')){assert.deepEqual(p,priorPerformances.get(p.id),'modern records unchanged');modern++;continue;}
   const current=performancePool(p.athleteId,HISTORICAL).find(c=>c.id===p.id);
   assert.ok(current,`${p.id} resolves in the current pool`);
   assert.deepEqual(p,JSON.parse(JSON.stringify(current)),`${p.id} equals the current record`);
   migrated++;
  }
  assert.deepEqual(new Set(s.used),new Set(performances(s).map(p=>p.id)),`${table}[${i}]: used still matches the games in history`);
  assert.equal(new Set(s.used).size,s.used.length,`${table}[${i}]: no duplicate consumed games`);
 });
 assert.deepEqual(changes,[1,1,1,1],'one row per table with historical games; strict, lobby, unplayed and backup rows are not written');
 assert.ok(migrated>=20,`migrated historical records checked (${migrated})`);
 assert.ok(modern>0,'saves mix in unchanged modern records');
 assert.deepEqual(after.demo_scoring_backups,before.demo_scoring_backups,'backups untouched; the 0006/0007 triggers did not fire');
});

test('running 0008 a second time changes nothing',()=>{
 const sql=seeded();migrate(sql);const once=dump(sql);
 assert.deepEqual(migrate(sql),[0,0,0,0]);
 assert.deepEqual(dump(sql),once);
});

test('every reachable historical source file maps to its current provenance link',()=>{
 // One old-format record per source file (63d6379 lib/historical-data.ts: id prefix, blob URL, report URL).
 const rows=JSON.parse(readFileSync(new URL('data/historical-mode/records.json',root),'utf8')) as [string,number,unknown,string,...unknown[]][];
 const byFile=new Map<number,[string,number,unknown,string,...unknown[]]>();for(const r of rows)if(r[1]<1999&&!byFile.has(r[8] as number))byFile.set(r[8] as number,r);
 const records=[...byFile.values()].map(r=>performancePool(r[0],HISTORICAL).find(p=>p.id===`historical:${r[0]}:${r[1]}:${r[3]}`)).filter(Boolean) as Json[];
 assert.ok(records.length>=20,`records from ${records.length} source files`);
 const toOld=(p:Json)=>{const url=`${OLD_BLOB}${p.sourceRevision}/${p.sourceFile}#L${p.sourceLine}`;return {...p,id:`prime-rushmore:${p.id.slice('historical:'.length)}`,sourceUrl:url,sourceUrls:[url,`${OLD_BLOB}${p.sourceRevision}/fantasy-legends/VALIDATION_REPORT.md`]};};
 const league=(list:Json[])=>({used:list.map(p=>p.id),history:[{number:1,draws:[list.map(p=>({athleteId:p.athleteId,performance:p}))]}],revision:3});
 const sql=seeded({leagues:[{owner_id:'files',state:JSON.stringify(league(records.map(toOld))),revision:3,updated_at:'2026-10-01T00:00:00.000Z'}]});
 assert.deepEqual(migrate(sql),[1,0,0,0]);
 assert.equal(String((sql.prepare('SELECT state FROM leagues').get() as Row).state),JSON.stringify(league(JSON.parse(JSON.stringify(records)))));
});

test('migrated saves keep playing with their stored revisions and never redraw a consumed game',async()=>{
 const sql=seeded();migrate(sql);
 (globalThis as MigrationGlobal).__migrationDatabase={prepare(query:string){let args:SQLInputValue[]=[];return {bind(...values:unknown[]){args=values as SQLInputValue[];return this;},async first(){return sql.prepare(query).get(...args)||null;},async all(){return {results:sql.prepare(query).all(...args)};},async run(){return {meta:{changes:Number(sql.prepare(query).run(...args).changes)}};}};}};
 const req=(path:string,user:string,body:unknown)=>new Request(`https://migration.test/api/${path}`,{method:'POST',headers:{'oai-authenticated-user-id':user,origin:'https://migration.test','Content-Type':'application/json'},body:JSON.stringify(body)});
 const read=(query:string,...args:SQLInputValue[])=>JSON.parse(String((sql.prepare(query).get(...args) as Row).state));
 function noRedraw(before:Json,after:Json){
  const old=new Set(before.used);
  assert.equal(new Set(after.used).size,after.used.length,'no duplicate consumed games');
  assert.ok(before.used.every((id:string)=>after.used.includes(id)),'consumed games stay consumed');
  const fresh=after.used.filter((id:string)=>!old.has(id));
  assert.ok(fresh.length>0&&fresh.every((id:string)=>!old.has(id)),'new games were drawn, none previously consumed');
 }
 // Online season: the commissioner scores the open week.
 const season=read("SELECT state FROM season_leagues WHERE owner_id='owner'");
 let r=await leagueRoute.POST(req('leagues','owner',{action:'closeRound',revision:season.revision}),{params:Promise.resolve({id:season.id})});
 assert.equal(r.status,200,await r.clone().text());
 const scored=read("SELECT state FROM season_leagues WHERE owner_id='owner'");
 assert.equal(scored.revision,season.revision+1);noRedraw(season,scored);
 // Quick game: the second player locks the partly locked round.
 const quickBefore=read("SELECT state FROM leagues WHERE owner_id='quick-owner'");
 const lineup=quickBefore.lineups[0];
 r=await quick.POST(req('game','quick-owner',{action:'lock',revision:quickBefore.revision,turn:1,lineup}));
 assert.equal(r.status,200,await r.clone().text());noRedraw(quickBefore,read("SELECT state FROM leagues WHERE owner_id='quick-owner'"));
 // Solo: lock the open week, then reset and restore the migrated archive and play it on.
 const solo=read("SELECT state FROM demo_drafts WHERE owner_id='solo-owner'");
 const me=solo.season.teams.find((t:Json)=>t.id===solo.humanTeamId);
 r=await demo.POST(req('demo','solo-owner',{action:'lock',seasonId:solo.id,revision:solo.revision,lineup:me.lineup,acceptBye:true}));
 assert.equal(r.status,200,await r.clone().text());
 const locked=read("SELECT state FROM demo_drafts WHERE owner_id='solo-owner'");noRedraw(solo.season,locked.season);
 const archive=fixture.tables.demo_archives[0];
 r=await demo.POST(req('demo','solo-owner',{action:'reset',confirm:true,seasonId:locked.id,revision:locked.revision}));assert.equal(r.status,200,await r.clone().text());
 r=await demo.POST(req('demo','solo-owner',{action:'restore',archiveId:archive.id}));assert.equal(r.status,200,await r.clone().text());
 const restored=read("SELECT state FROM demo_drafts WHERE owner_id='solo-owner'");
 assert.equal(restored.id,archive.id);assert.ok(restored.season.used.every((id:string)=>!id.startsWith('prime-rushmore:')));
 const restoredMe=restored.season.teams.find((t:Json)=>t.id===restored.humanTeamId);
 r=await demo.POST(req('demo','solo-owner',{action:'lock',seasonId:restored.id,revision:restored.revision,lineup:restoredMe.lineup,acceptBye:true}));
 assert.equal(r.status,200,await r.clone().text());noRedraw(restored.season,read("SELECT state FROM demo_drafts WHERE owner_id='solo-owner'").season);
});
