import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {registerHooks} from 'node:module';
import test from 'node:test';
import type {DemoDraft} from '../lib/demo-draft-model';
registerHooks({load(url,context,next){if(url.startsWith('file:')&&url.endsWith('.json'))return {format:'module',shortCircuit:true,source:`export default ${readFileSync(new URL(url),'utf8')}`};return next(url,context);},resolve(id,context,next){try{return next(id,context);}catch(e){if(id.startsWith('.')&&!/\.[a-z]+$/i.test(id))return next(`${id}.ts`,context);throw e;}}});
const {newDemoDraft,demoDraftAction,demoReply}=await import('../lib/demo-draft-engine');
const {demoPickReason}=await import('../lib/demo-draft-model');
const {ATHLETES}=await import('../lib/game-model');
const {currentPairs,seasonLength,standings}=await import('../lib/season-view');
const {newSeason,seasonAction}=await import('../lib/season-engine');
function finish(s:DemoDraft){while(s.status==='draft'){const options=ATHLETES.filter(a=>!demoPickReason(s,s.humanTeamId,a.id));assert.ok(options.length,'An eligible human pick remains');s=demoDraftAction(s,{action:'draft',athleteId:options[0].id});}return s;}
// Saved Strict drafts retain the original archive and exhaustion ledger.
const modern=(capacity=8,playoffTeams=6)=>newDemoDraft('My team',1,{modern:true,capacity,playoffTeams,scoringMode:'strict'});
const frozen=finish(modern());

test('modern draft persists randomized full order, distinct ten-player rosters and every human choice',()=>{assert.equal(frozen.pick,80);assert.equal(frozen.order.length,8);assert.equal(new Set(frozen.order).size,8);assert.equal(new Set(frozen.teams.flatMap(t=>t.roster)).size,80);assert.equal(frozen.picks.filter(p=>p.control==='human').length,10);for(const t of frozen.teams)assert.equal(t.roster.length,10);for(const p of frozen.picks){const offset=(p.number-1)%8,round=Math.floor((p.number-1)/8);assert.equal(p.teamId,frozen.order[round%2?7-offset:offset]);}assert.throws(()=>demoDraftAction(frozen,{action:'reshuffle'}));});
test('17 weeks retain rosters, records and consumed performances; six playoffs have byes and fixed bracket',()=>{let d=demoDraftAction(frozen,{action:'startSeason'});const roster=d.season!.teams.map(t=>[...t.roster]);const order=[...d.order];for(let week=1;week<=17;week++){const s=d.season!;assert.equal(s.round,week);assert.equal(seasonLength(s),17);assert.deepEqual(s.teams.find(t=>t.id===d.humanTeamId)!.roster,roster[d.season!.teams.findIndex(t=>t.id===d.humanTeamId)]);const human=s.teams.find(t=>t.id===d.humanTeamId)!;const body=currentPairs(s).flat().includes(human.id)?{action:'lock',lineup:human.lineup,acceptBye:true}:{action:'simulate'};const saved=structuredClone(s.history);d=demoDraftAction(d,body);assert.deepEqual(d.season!.history.slice(0,-1),saved);assert.equal(d.season!.history.length,week);assert.deepEqual(d.order,order);assert.equal(new Set(d.season!.used).size,d.season!.used.length);assert.deepEqual(JSON.parse(JSON.stringify(d)),d);assert.throws(()=>demoDraftAction(d,body));if(week===15){assert.equal(d.season!.history.at(-1)!.phase,'quarterfinal');assert.ok(d.season!.history.at(-1)!.matches.every(m=>!d.season!.playoffSeeds.slice(0,2).some(id=>id===m.home||id===m.away)));}if(week<17)d=demoDraftAction(d,{action:'next'});}assert.equal(d.season!.status,'complete');assert.ok(d.season!.champion);assert.equal(d.season!.used.length,d.season!.history.flatMap(r=>[...Object.values(r.draws).flat(),...Object.values(r.benchDraws||{}).flat()]).filter(d=>!d.simulatedBye).length);assert.ok(standings(d.season!).every(t=>t.wins+t.losses+t.ties===14));assert.throws(()=>demoDraftAction(d,{action:'next'}));assert.throws(()=>demoDraftAction(d,{action:'swap'}));assert.deepEqual(demoDraftAction(d,{action:'startSeason'}),d);});
test('bench substitutions and free agents cannot steal players, duplicate slots, reroll or reset usage',()=>{let d=demoDraftAction(frozen,{action:'startSeason'});const s=d.season!;let human=s.teams.find(t=>t.id===d.humanTeamId)!;const bench=human.roster.find(id=>!Object.values(human.lineup).includes(id))!,p=ATHLETES.find(a=>a.id===bench)!.position;d=demoDraftAction(d,{action:'lineup',lineup:{...human.lineup,[p]:bench}});assert.equal(d.season!.teams.find(t=>t.id===d.humanTeamId)!.lineup[p],bench);assert.throws(()=>demoDraftAction(d,{action:'lineup',lineup:{...human.lineup,QB:s.teams.find(t=>t.id!==human.id)!.lineup.QB}}),/own roster/);assert.throws(()=>demoDraftAction(d,{action:'swap',drop:human.roster[0],add:s.teams.find(t=>t.id!==human.id)!.roster[0]}),/unowned/);human=d.season!.teams.find(t=>t.id===d.humanTeamId)!;d=demoDraftAction(d,{action:'lock',lineup:human.lineup,acceptBye:true});const history=structuredClone(d.season!.history),used=[...d.season!.used];const drop=human.lineup.QB,add=ATHLETES.find(a=>a.position==='QB'&&!a.legend&&a.gameCount>=17&&!d.season!.teams.some(t=>t.roster.includes(a.id)))!.id;d=demoDraftAction(d,{action:'swap',drop,add});d=demoDraftAction(d,{action:'swap',drop:add,add:drop});assert.deepEqual(d.season!.used,used);assert.deepEqual(d.season!.history,history);assert.equal(d.season!.teams.find(t=>t.id===human.id)!.roster.length,10);assert.throws(()=>demoDraftAction(d,{action:'offer'}),/computer team/);});
test('four qualifiers also finish in Week 17; all allowed league sizes can fill rosters up to 16 teams',()=>{for(const capacity of [2,4,6,10,12,14,16]){const d=finish(modern(capacity,4));assert.equal(d.pick,capacity*10);assert.equal(new Set(d.teams.flatMap(t=>t.roster)).size,capacity*10);const s=demoDraftAction(d,{action:'startSeason'}).season!;assert.equal(seasonLength(s),17);assert.equal(s.regularRounds,capacity===2?16:15);for(const week of s.schedule){assert.equal(week.length,capacity/2);assert.equal(new Set(week.flat()).size,capacity);}if(capacity===16)assert.equal(s.teams.flatMap(t=>t.roster).filter(id=>ATHLETES.find(a=>a.id===id)!.position==='DEF').length<=32,true);}});
test('legacy completed six-pick demo remains unchanged until explicit bench continuation',()=>{const legacy=finish(newDemoDraft('Legacy',1,{scoringMode:'strict'}));const snapshot=JSON.stringify(legacy);assert.equal(legacy.pick,48);assert.equal(demoReply(legacy).demo!.pick,48);assert.equal(JSON.stringify(legacy),snapshot);assert.throws(()=>demoDraftAction(legacy,{action:'startSeason'}),/ten roster/);let d=demoDraftAction(legacy,{action:'completeBench',playoffTeams:4});assert.deepEqual(d.picks.slice(0,48),legacy.picks);assert.deepEqual(d.order,legacy.order);assert.equal(d.teams.find(t=>t.id===d.humanTeamId)!.roster.length,6);d=finish(d);assert.equal(d.pick,80);for(const t of legacy.teams)assert.deepEqual(d.teams.find(team=>team.id===t.id)!.roster.slice(0,6),t.roster);assert.equal(demoDraftAction(d,{action:'startSeason'}).season!.regularRounds,15);assert.equal(JSON.stringify(legacy),snapshot);});
test('settings validate playoff count and lock at draft start; unavailable pools fail atomically',()=>{assert.throws(()=>modern(18));assert.throws(()=>modern(4,6));assert.throws(()=>newDemoDraft('Same',1,{modern:true,capacity:4,names:['Same','Two','Three'],playoffTeams:4}),/different name/);let s=newSeason('owner',{name:'Rules',teamName:'Owner',capacity:8,format:'seventeen',playoffTeams:4},'test');s=seasonAction(s,'owner',{action:'rules',playoffTeams:6});assert.equal(s.regularRounds,14);s.status='active';assert.throws(()=>seasonAction(s,'owner',{action:'rules',playoffTeams:4}),/fixed/);});


test('exhausted starters can be replenished over multiple atomic swaps; used records cannot return',async()=>{const {PERFORMANCES}=await import('../lib/historical-data');let d=demoDraftAction(frozen,{action:'startSeason'});const me=d.season!.teams.find(t=>t.id===d.humanTeamId)!;const exhausted=me.roster.filter(id=>['QB','TE'].includes(ATHLETES.find(a=>a.id===id)!.position));d.season!.used=PERFORMANCES.filter(p=>exhausted.includes(p.athleteId)).map(p=>p.id);const used=[...d.season!.used];const untouched=JSON.stringify(d);assert.throws(()=>demoDraftAction(d,{action:'lock',lineup:me.lineup}),/unused/);assert.equal(JSON.stringify(d),untouched);for(const pos of ['QB','TE']){const drop=me.lineup[pos],add=ATHLETES.find(a=>a.position===pos&&!a.legend&&a.gameCount>=17&&!d.season!.teams.some(t=>t.roster.includes(a.id)))!.id;d=demoDraftAction(d,{action:'swap',drop,add});assert.equal(d.season!.teams.find(t=>t.id===me.id)!.roster.length,10);assert.deepEqual(d.season!.used,used);}const human=d.season!.teams.find(t=>t.id===me.id)!;const {repairLineup}=await import('../lib/season-engine');const lineup=repairLineup(d.season!,human);d=demoDraftAction(d,{action:'lock',lineup});assert.equal(d.season!.history.length,1);assert.ok(d.season!.used.length>used.length);});

test('computer exhaustion replenishes only that roster and unrecoverable pools leave the week unchanged',async()=>{const {PERFORMANCES}=await import('../lib/historical-data');let d=demoDraftAction(frozen,{action:'startSeason'});const computer=d.season!.teams.find(t=>t.id!==d.humanTeamId)!;const exhausted=computer.roster.filter(id=>ATHLETES.find(a=>a.id===id)!.position==='QB');d.season!.used=PERFORMANCES.filter(p=>exhausted.includes(p.athleteId)).map(p=>p.id);const human=d.season!.teams.find(t=>t.id===d.humanTeamId)!,roster=[...human.roster];d=demoDraftAction(d,{action:'lock',lineup:human.lineup,acceptBye:true});assert.equal(d.season!.history.length,1);assert.deepEqual(d.season!.teams.find(t=>t.id===human.id)!.roster,roster);assert.ok(d.season!.activity.some(a=>a.text.includes('added')));const blocked=demoDraftAction(frozen,{action:'startSeason'});blocked.season!.used=PERFORMANCES.map(p=>p.id);const before=JSON.stringify(blocked);assert.throws(()=>demoDraftAction(blocked,{action:'lock',lineup:blocked.season!.teams.find(t=>t.id===blocked.humanTeamId)!.lineup}),/unused/);assert.equal(JSON.stringify(blocked),before);});

test('four-team playoffs run exactly 17 weeks and old online schedules retain their format',()=>{let d=demoDraftAction(finish(modern(4,4)),{action:'startSeason'});while(d.season!.status!=='complete'){const s=d.season!,human=s.teams.find(t=>t.id===d.humanTeamId)!;d=demoDraftAction(d,currentPairs(s).flat().includes(human.id)?{action:'lock',lineup:human.lineup,acceptBye:true}:{action:'simulate'});if(String(d.season!.status)!=='complete')d=demoDraftAction(d,{action:'next'});}assert.equal(d.season!.history.length,17);assert.equal(d.season!.history[15].phase,'semifinal');assert.equal(d.season!.history[16].phase,'final');const old=newSeason('old',{name:'Legacy',teamName:'Original',capacity:8,regularRounds:14},'old');assert.equal(seasonLength(old),16);assert.equal(old.format,undefined);});

test('regular ties count fairly, playoff ties advance higher seeds, and fixed brackets do not reshuffle',async()=>{const {matchResult}=await import('../lib/season-engine');const seeds=['one','two','three','four','five','six'];assert.equal(matchResult('one','two',100,100,'regular',seeds).winner,null);for(const phase of ['quarterfinal','semifinal','final'] as const){assert.equal(matchResult('six','three',100,100,phase,seeds).winner,'three');assert.equal(matchResult('six','three',100,100,phase,seeds).tiebreak,'Higher regular-season seed');}const s=demoDraftAction(frozen,{action:'startSeason'}).season!;s.playoffSeeds=s.teams.slice(0,6).map(t=>t.id);s.round=15;const quarters=currentPairs(s);s.history=[{number:15,phase:'quarterfinal',matches:quarters.map(([home,away])=>matchResult(home,away,99,100,'quarterfinal',s.playoffSeeds)),draws:{},resolvedAt:'test'}];s.round=16;assert.deepEqual(currentPairs(s),[[s.playoffSeeds[0],s.playoffSeeds[4]],[s.playoffSeeds[1],s.playoffSeeds[5]]]);});

test('16 real-manager teams can complete the modern online draft without duplicate ownership',async()=>{const {joinSeason}=await import('../lib/season-engine');let s=newSeason('owner',{name:'Sixteen teams',teamName:'Owner',capacity:16,format:'seventeen',playoffTeams:6},'test');for(let i=1;i<16;i++)s=joinSeason(s,`manager-${i}`,`Team ${i}`);s=seasonAction(s,'owner',{action:'startDraft'});const order=[...s.draftOrder];while(s.status==='draft')s=seasonAction(s,'owner',{action:'autopick'});assert.equal(s.pick,160);assert.equal(s.teams.every(t=>t.roster.length===10),true);assert.equal(new Set(s.teams.flatMap(t=>t.roster)).size,160);assert.deepEqual(s.draftOrder,order);assert.equal(s.schedule.length,14);for(const t of s.teams){const opponents=s.schedule.flatMap(week=>week.filter(pair=>pair.includes(t.id)).map(pair=>pair.find(id=>id!==t.id)!));assert.equal(new Set(opponents).size,14);}assert.throws(()=>seasonAction(s,'owner',{action:'startDraft'}));});
