import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {registerHooks} from 'node:module';
import {DatabaseSync,type SQLInputValue} from 'node:sqlite';
import test from 'node:test';
import type {Profile} from '../lib/profile-model';
const root=new URL('../',import.meta.url);
const shared=globalThis as typeof globalThis&{__profileDB?:ReturnType<typeof memoryDatabase>};
registerHooks({load(url,context,next){if(url.startsWith('file:')&&url.endsWith('.json'))return {format:'module',shortCircuit:true,source:`export default ${readFileSync(new URL(url),'utf8')}`};return next(url,context);},resolve(id,context,next){if(id==='@/db')return {url:`data:text/javascript,${encodeURIComponent('export function database(){return globalThis.__profileDB;}')}`,shortCircuit:true};if(id.startsWith('@/'))return next(new URL(`${id.slice(2)}.ts`,root).href,context);try{return next(id,context);}catch(e){if(id.startsWith('.')&&!/\.[a-z]+$/i.test(id))return next(`${id}.ts`,context);throw e;}}});
const api=await import('../app/api/profile/route');const {emptyProfile,validAvatar}=await import('../lib/profile-model');
function memoryDatabase(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('drizzle/',root)).filter(f=>f.endsWith('.sql')))sql.exec(readFileSync(new URL(`drizzle/${f}`,root),'utf8'));return {sql,prepare(query:string){let args:SQLInputValue[]=[];return {bind(...values:unknown[]){args=values as SQLInputValue[];return this;},async first(){return sql.prepare(query).get(...args)||null;},async run(){return {meta:{changes:Number(sql.prepare(query).run(...args).changes)}};}};}};}
function request(body?:unknown,user='owner',origin='https://site.test'){return new Request('https://site.test/api/profile',{method:body===undefined?'GET':'POST',headers:{...(user?{'oai-authenticated-user-id':user}:{}),origin,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});}
async function read(user='owner'){return (await(await api.GET(request(undefined,user))).json() as {profile:Profile}).profile;}
test('profile is private, editable, reloadable and concurrent writes use revisions',async()=>{shared.__profileDB=memoryDatabase();assert.equal((await api.GET(request(undefined,''))).status,401);assert.equal((await api.POST(request(emptyProfile(),'owner','https://evil.test'))).status,403);const input={...emptyProfile(),displayName:'Jonathan',username:'throwbacks',about:'Football history',receptionPoints:.5,reduceMotion:true};const writes=await Promise.all([api.POST(request(input)),api.POST(request({...input,displayName:'Other tab'}))]);assert.deepEqual(writes.map(r=>r.status).sort(),[200,409]);const saved=await read();assert.equal(saved.revision,1);assert.equal(saved.receptionPoints,.5);assert.deepEqual(await read('other'),emptyProfile());assert.equal((await api.POST(request({...saved,displayName:'Updated'}))).status,200);assert.equal((await read()).displayName,'Updated');assert.equal((await api.POST(request({...emptyProfile(),revision:99},'new-user'))).status,409);});
test('avatar validates bounded raster data, rejects SVG, HTML, remote URLs and oversized uploads',async()=>{shared.__profileDB=memoryDatabase();for(const avatar of ['https://evil.test/a.png','data:image/svg+xml;base64,PHN2Zz4=','data:text/html;base64,PGh0bWw+','data:image/jpeg;base64,'+'A'.repeat(200000),'data:image/png;base64,AAAA']){assert.equal(validAvatar(avatar),false);assert.equal((await api.POST(request({...emptyProfile(),avatar}))).status>=400,true);}assert.equal(validAvatar(null),true);const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a0l8AAAAASUVORK5CYII=';assert.equal(validAvatar(png),true);assert.equal((await api.POST(request({...emptyProfile(),avatar:png}))).status,200);assert.equal((await read()).avatar,png);assert.equal((await api.POST(request({...await read(),avatar:null}))).status,200);assert.equal((await read()).avatar,null);});
test('profile fields validate without accepting password or external identity changes',async()=>{shared.__profileDB=memoryDatabase();for(const values of [{username:'x'},{username:'bad name'},{displayName:'A'.repeat(51)},{receptionPoints:2},{reduceMotion:'false'}, {revision:-1}])assert.equal((await api.POST(request({...emptyProfile(),...values}))).status,400);assert.equal((await api.POST(request({...emptyProfile(),password:'never-saved',email:'not-saved',ownerId:'other'}))).status,200);assert.equal(JSON.stringify(await read()).includes('never-saved'),false);assert.deepEqual(await read('other'),emptyProfile());});
