import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {registerHooks} from 'node:module';
import {DatabaseSync,type SQLInputValue} from 'node:sqlite';
import test from 'node:test';
import type {Season,PublicSeason} from '../lib/season-model';
const root=new URL('../',import.meta.url);
type AuditGlobal=typeof globalThis&{__seasonDatabase?:ReturnType<typeof memoryDatabase>};
const audit=globalThis as AuditGlobal;
registerHooks({
 load(url,context,next){if(url.startsWith('file:')&&url.endsWith('.json'))return {format:'module',shortCircuit:true,source:`export default ${readFileSync(new URL(url),'utf8')}`};return next(url,context);},
 resolve(id,context,next){if(id==='@/db')return {url:`data:text/javascript,${encodeURIComponent('export function database(){return globalThis.__seasonDatabase;}')}`,shortCircuit:true};if(id.startsWith('@/'))return next(new URL(`${id.slice(2)}.ts`,root).href,context);try{return next(id,context);}catch(e){if(id.startsWith('.')&&!/\.[a-z]+$/i.test(id))return next(`${id}.ts`,context);throw e;}}
});
const collection=await import('../app/api/leagues/route');
const item=await import('../app/api/leagues/[id]/route');
const {newSeason,joinSeason,seasonAction}=await import('../lib/season-engine');
const auditPlayers=await import('../lib/game-model');
const {inviteHash}=await import('../lib/season-store');
function memoryDatabase(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('drizzle/0001_brainy_gunslinger.sql',root),'utf8'));return {sql,failWrites:false,prepare(query:string){let args:SQLInputValue[]=[];return {bind(...values:unknown[]){args=values as SQLInputValue[];return this;},async first(){return sql.prepare(query).get(...args)||null;},async all(){return {results:sql.prepare(query).all(...args)};},async run(){if(audit.__seasonDatabase?.failWrites)throw new Error('INTERNAL DATABASE SECRET');return {meta:{changes:Number(sql.prepare(query).run(...args).changes)}};}};}};}
function fresh(){audit.__seasonDatabase=memoryDatabase();return audit.__seasonDatabase;}
function request(body?:Record<string,unknown>,user='owner',origin='https://league.test'){return new Request('https://league.test/api/leagues',{method:body?'POST':'GET',headers:{...(user?{'oai-authenticated-user-id':user}:{}),...(origin?{origin}:{}),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});}
const context=(id:string)=>({params:Promise.resolve({id})});
async function json(response:Response):Promise<{league:PublicSeason;leagues?:unknown[];error?:string}>{return response.json();}
async function create(){const r=await collection.POST(request({action:'create',name:'API audit',teamName:'Owner',capacity:2,regularRounds:6}));assert.equal(r.status,201);return (await json(r)).league;}
async function seedActive(){let s=newSeason('owner',{name:'API season',teamName:'Owner',capacity:2,regularRounds:6},'ACTIVE-CODE');s=joinSeason(s,'manager','Visitor');s=seasonAction(s,'owner',{action:'startDraft'});while(s.status==='draft')s=seasonAction(s,'owner',{action:'autopick'});audit.__seasonDatabase!.sql.prepare('INSERT INTO season_leagues (id,owner_id,invite_hash,state,revision,updated_at) VALUES (?,?,?,?,?,?)').run(s.id,s.ownerId,await inviteHash(s.inviteCode),JSON.stringify(s),s.revision,s.createdAt);return s;}

test('anonymous and cross-origin writes denied; malformed requests handled',async()=>{fresh();assert.equal((await collection.GET(request(undefined,''))).status,401);assert.equal((await collection.POST(request({action:'create'},''))).status,401);assert.equal((await collection.POST(request({action:'create'},'owner','https://evil.test'))).status,403);assert.equal((await collection.POST(new Request('https://league.test/api/leagues',{method:'POST',headers:{'oai-authenticated-user-id':'owner'},body:'bad-json'}))).status,400);});
test('join persisted by separate identities and lists never show outsider leagues',async()=>{fresh();const s=await create();assert.ok(s.inviteCode);const r=await collection.POST(request({action:'join',code:s.inviteCode!.toLowerCase().replaceAll('-',' '),teamName:'Visitor'},'manager'));assert.equal(r.status,200);const joined=(await json(r)).league;assert.equal(joined.teams.length,2);assert.ok(!('inviteCode' in joined));const list=await json(await collection.GET(request(undefined,'manager')));assert.equal(list.leagues?.length,1);assert.equal((await json(await collection.GET(request(undefined,'outsider')))).leagues?.length,0);assert.equal((await item.GET(request(undefined,'outsider'),context(s.id))).status,404);assert.equal((await item.POST(request({action:'closeRound',revision:joined.revision},'outsider'),context(s.id))).status,404);assert.ok(!JSON.stringify(joined).includes('userId'));});
test('simultaneous final-seat joins commit only one manager; repeat joining is idempotent',async()=>{fresh();const s=await create();const responses=await Promise.all(['a','b'].map(user=>collection.POST(request({action:'join',code:s.inviteCode,teamName:`Team ${user}`},user))));assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);const canonical=JSON.parse(String(audit.__seasonDatabase!.sql.prepare('SELECT state FROM season_leagues WHERE id=?').get(s.id)!.state)) as Season;assert.equal(canonical.teams.length,2);const winner=canonical.teams[1].userId;const again=await collection.POST(request({action:'join',code:s.inviteCode,teamName:'Changed name'},winner));assert.equal(again.status,200);assert.equal((await json(again)).league.teams[1].name,canonical.teams[1].name);});
test('noncommissioner cannot start draft, rotate code or score; code rotation revokes old code',async()=>{fresh();const s=await create();await collection.POST(request({action:'join',code:s.inviteCode,teamName:'Visitor'},'manager'));let current=(await json(await item.GET(request(),context(s.id)))).league;for(const action of ['startDraft','rotateInvite','closeRound'])assert.equal((await item.POST(request({action,revision:current.revision},'manager'),context(s.id))).status,400);const rotated=await item.POST(request({action:'rotateInvite',revision:current.revision},'owner'),context(s.id));assert.equal(rotated.status,200);current=(await json(rotated)).league;assert.notEqual(current.inviteCode,s.inviteCode);assert.equal((await collection.POST(request({action:'join',code:s.inviteCode,teamName:'Bad code'},'outsider'))).status,404);});
test('revision conflicts prevent duplicate random results under concurrent closes',async()=>{fresh();const s=await seedActive();const results=await Promise.all([item.POST(request({action:'closeRound',revision:s.revision}),context(s.id)),item.POST(request({action:'closeRound',revision:s.revision}),context(s.id))]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const saved=(await json(await item.GET(request(),context(s.id)))).league;assert.equal(saved.history.length,1);assert.equal(saved.used.length,20);assert.equal(saved.history[0].benchDraws,undefined);const canonical=JSON.parse(String(audit.__seasonDatabase!.sql.prepare('SELECT state FROM season_leagues WHERE id=?').get(s.id)!.state)) as Season;assert.equal(Object.values(canonical.history[0].benchDraws!).flat().length,8);assert.equal(new Set(canonical.used).size,20);for(const d of Object.values(canonical.history[0].benchDraws!).flat())assert.ok(canonical.used.includes(d.performance.id!));assert.equal(saved.revision,1);const stale=await item.POST(request({action:'next',revision:0}),context(s.id));assert.equal(stale.status,409);assert.equal((await json(stale)).league.history.length,1);});
test('racing claims to a free agent commit one atomic swap',async()=>{fresh();const s=await seedActive();const {ATHLETES}=await import('../lib/historical-data');const add=ATHLETES.find(a=>a.position==='QB'&&!a.legend&&!s.teams.some(t=>t.roster.includes(a.id)))!.id;const responses=await Promise.all(s.teams.map(t=>item.POST(request({action:'swap',revision:s.revision,drop:t.lineup.QB,add},t.userId),context(s.id))));assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);const saved=(await json(await item.GET(request(),context(s.id)))).league;assert.equal(saved.teams.flatMap(t=>t.roster).filter(id=>id===add).length,1);assert.ok(saved.teams.every(t=>t.roster.length===10));});
test('league details hide opponent starters, game previews require membership',async()=>{fresh();const s=await seedActive();const r=await item.GET(request(undefined,'manager'),context(s.id));assert.equal(r.headers.get('Cache-Control'),'private, no-store');const saved=(await json(r)).league;assert.deepEqual(saved.teams[0].lineup,{});assert.deepEqual(saved.teams[1].lineup,s.teams[1].lineup);const req=new Request(`https://league.test/api/leagues/${s.id}?athlete=${s.teams[0].roster[0]}`,{headers:{'oai-authenticated-user-id':'outsider'}});assert.equal((await item.GET(req,context(s.id))).status,404);});
test('join brute force is rate limited and commit failures return safe errors',async()=>{const db=fresh();const s=await seedActive();for(let n=0;n<8;n++)assert.equal((await collection.POST(request({action:'join',code:'INVALID',teamName:'Guess'},'guesser'))).status,404);assert.equal((await collection.POST(request({action:'join',code:'INVALID',teamName:'Guess'},'guesser'))).status,429);db.failWrites=true;const r=await item.POST(request({action:'closeRound',revision:s.revision}),context(s.id));assert.equal(r.status,503);assert.ok(!(await r.text()).includes('SECRET'));});

test('legacy online D1 rows persist FLEX migration on write and survive refresh',async()=>{
 const db=fresh(),s=await seedActive();delete s.lineupVersion;for(const t of s.teams)delete t.lineup.FLEX;const raw=JSON.stringify(s);db.sql.prepare('UPDATE season_leagues SET state=? WHERE id=?').run(raw,s.id);
 const first=(await json(await item.GET(request(),context(s.id)))).league;assert.equal(first.lineupVersion,2);const mine=first.teams.find(t=>t.id===first.myTeamId)!;assert.equal(new Set(Object.values(mine.lineup)).size,6);assert.equal(db.sql.prepare('SELECT state FROM season_leagues WHERE id=?').get(s.id)!.state,raw);
 const response=await item.POST(request({action:'lineup',revision:first.revision,lineup:mine.lineup}),context(s.id));assert.equal(response.status,200);const saved=(await json(response)).league;assert.deepEqual((await json(await item.GET(request(),context(s.id)))).league,saved);const persisted=JSON.parse(String(db.sql.prepare('SELECT state FROM season_leagues WHERE id=?').get(s.id)!.state)) as Season;assert.equal(persisted.lineupVersion,2);assert.ok(persisted.teams.every(t=>Object.values(t.lineup).length===6));assert.deepEqual(persisted.teams.map(t=>t.roster),s.teams.map(t=>t.roster));
});
test('legacy locked online D1 round saves ten results, then next round persists six starters',async()=>{
 const db=fresh(),s=await seedActive();delete s.lineupVersion;for(const t of s.teams)delete t.lineup.FLEX;s.teams[0].locked=true;db.sql.prepare('UPDATE season_leagues SET state=? WHERE id=?').run(JSON.stringify(s),s.id);
 const before=(await json(await item.GET(request(),context(s.id)))).league;assert.equal(before.lineupVersion,1);const close=await item.POST(request({action:'closeRound',revision:s.revision}),context(s.id));assert.equal(close.status,200);const saved=(await json(close)).league;assert.equal(saved.used.length,20);assert.deepEqual((await json(await item.GET(request(),context(s.id)))).league,saved);const next=await item.POST(request({action:'next',revision:saved.revision}),context(s.id));assert.equal(next.status,200);const opened=(await json(next)).league;assert.equal(opened.lineupVersion,2);assert.deepEqual(opened.history,saved.history);assert.deepEqual(opened.used,saved.used);assert.deepEqual((await json(await item.GET(request(),context(s.id)))).league,opened);
});

test('staged receipt disclosure survives final/skip, repeated actions and reload without changing any draw',async()=>{
 const db=fresh(),s=await seedActive(),ctx=context(s.id);const active=(await json(await item.GET(request(),ctx))).league;assert.equal(active.history.length,0);assert.equal((await item.POST(request({action:'revealReplay',round:1,revision:s.revision}),ctx)).status,400);
 const first=s.teams[0];let response=await item.POST(request({action:'lock',lineup:first.lineup,revision:s.revision},first.userId),ctx);assert.equal(response.status,200);let body=(await json(response)).league;assert.equal(body.history.length,0);assert.equal((await item.POST(request({action:'lineup',lineup:first.lineup,revision:body.revision},first.userId),ctx)).status,400);
 response=await item.POST(request({action:'lock',lineup:s.teams[1].lineup,revision:body.revision},s.teams[1].userId),ctx);assert.equal(response.status,200);const readRaw=()=>JSON.parse(String(db.sql.prepare('SELECT state FROM season_leagues WHERE id=?').get(s.id)!.state)) as Season;const canonical=readRaw(),receipt=canonical.history[0].draws[first.id][0].performance,history=JSON.stringify(canonical.history),used=JSON.stringify(canonical.used);
 body=(await json(await item.GET(request(),ctx))).league;assert.equal(body.history[0].receiptsHidden,true);for(const draws of Object.values(body.history[0].draws))for(const d of draws)assert.deepEqual(Object.keys(d.performance),['season']);const payload=JSON.stringify(body);for(const exact of [receipt.id,receipt.gameId,receipt.sourceUrl,receipt.date])assert.ok(!payload.includes(exact!),`Hidden receipt leaked: ${exact}`);assert.equal(body.used.length,canonical.used.length);assert.ok(body.used.some(id=>id.includes('_reserved_')));assert.deepEqual((await json(await item.GET(request(),ctx))).league,body);
 response=await item.POST(request({action:'revealReplay',round:1,revision:body.revision}),ctx);assert.equal(response.status,200);const revealed=(await json(response)).league;assert.equal(revealed.history[0].receiptsHidden,false);assert.deepEqual(revealed.history[0].draws,canonical.history[0].draws);assert.deepEqual(revealed.revealedRounds,[1]);assert.equal(JSON.stringify(readRaw().history),history);assert.equal(JSON.stringify(readRaw().used),used);assert.deepEqual((await json(await item.GET(request(),ctx))).league,revealed);
 const other=(await json(await item.GET(request(undefined,s.teams[1].userId),ctx))).league;assert.equal(other.history[0].receiptsHidden,true);assert.deepEqual(other.revealedRounds,[]);
 response=await item.POST(request({action:'revealReplay',round:1,revision:revealed.revision}),ctx);assert.equal(response.status,200);assert.deepEqual((await json(response)).league.revealedRounds,[1]);assert.equal(JSON.stringify(readRaw().history),history);assert.equal(JSON.stringify(readRaw().used),used);
});

test('trade acceptance races and stale retries commit one atomic exchange; outsiders cannot answer',async()=>{const db=fresh(),s=await seedActive(),[a,b]=s.teams,ctx=context(s.id);const response=await item.POST(request({action:'offer',to:b.id,give:a.lineup.QB,receive:b.lineup.QB,revision:0},a.userId),ctx);assert.equal(response.status,200);const offered=(await json(response)).league,id=offered.trades[0].id;assert.equal((await item.POST(request({action:'accept',tradeId:id,revision:1},'outsider'),ctx)).status,404);assert.equal((await item.POST(request({action:'accept',tradeId:id,revision:1},a.userId),ctx)).status,400);const responses=await Promise.all([1,2].map(()=>item.POST(request({action:'accept',tradeId:id,revision:1},b.userId),ctx)));assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);const saved=JSON.parse(String(db.sql.prepare('SELECT state FROM season_leagues WHERE id=?').get(s.id)!.state)) as Season;assert.equal(saved.trades[0].status,'accepted');assert.equal(saved.revision,2);assert.equal(new Set(saved.teams.flatMap(t=>t.roster)).size,20);assert.ok(saved.teams[0].roster.includes(b.lineup.QB));assert.deepEqual(saved.used,s.used);assert.equal((await item.POST(request({action:'accept',tradeId:id,revision:2},b.userId),ctx)).status,400);});

test('commissioner manager removal revokes access, preserves locked team, and replacement claims are isolated',async()=>{
 const db=fresh(),s=await seedActive(),target=s.teams[1],ctx=context(s.id);target.locked=true;s.replayReveals={[target.id]:[1]};db.sql.prepare('UPDATE season_leagues SET state=? WHERE id=?').run(JSON.stringify(s),s.id);
 const body={action:'removeManager',teamId:target.id,revision:0,confirm:true};
 assert.equal((await item.POST(request(body,'manager'),ctx)).status,400);assert.equal((await item.POST(request({...body,teamId:s.teams[0].id}),ctx)).status,400);assert.equal((await item.POST(request({...body,confirm:false}),ctx)).status,400);
 const removed=await item.POST(request(body),ctx);assert.equal(removed.status,200);const publicState=(await json(removed)).league;
 const read=()=>JSON.parse(String(db.sql.prepare('SELECT state FROM season_leagues WHERE id=?').get(s.id)!.state)) as Season;const vacancy=read();
 assert.equal(vacancy.teams[1].vacant,true);assert.equal(vacancy.teams[1].userId,'');assert.equal(vacancy.teams[1].locked,true);
 for(const key of ['history','used','byes','schedule','draftOrder','playoffSeeds','champion'] as const)assert.deepEqual(vacancy[key],s[key],key);
 assert.deepEqual(vacancy.teams.map(t=>t.roster),s.teams.map(t=>t.roster));assert.deepEqual(vacancy.teams.map(t=>t.lineup),s.teams.map(t=>t.lineup));assert.ok(!('removedUserIds' in publicState));assert.ok(!JSON.stringify(publicState).includes('userId'));
 assert.equal((await item.GET(request(undefined,'manager'),ctx)).status,404);assert.equal((await item.POST(request({action:'lineup',revision:1,lineup:target.lineup},'manager'),ctx)).status,404);assert.equal((await json(await collection.GET(request(undefined,'manager')))).leagues!.length,0);
 assert.equal((await collection.POST(request({action:'join',code:s.inviteCode,teamName:'Blocked'},'manager'))).status,404);assert.equal((await collection.POST(request({action:'join',code:vacancy.inviteCode,teamId:target.id},'manager'))).status,403);
 const preview=await collection.POST(request({action:'inspectInvite',code:vacancy.inviteCode},'replacement'));assert.equal(preview.status,200);const previewText=await preview.text();assert.ok(previewText.includes(target.id));assert.ok(!previewText.includes('roster'));assert.ok(!previewText.includes('used'));
 const claims=await Promise.all(['replacement','racer'].map(user=>collection.POST(request({action:'join',code:vacancy.inviteCode,teamId:target.id},user))));assert.deepEqual(claims.map(r=>r.status).sort(),[200,409]);const assigned=read(),newUser=assigned.teams[1].userId;
 assert.ok(['replacement','racer'].includes(newUser));assert.equal(assigned.teams[1].id,target.id);assert.equal(assigned.teams[1].name,target.name);assert.equal(assigned.teams[1].locked,true);assert.deepEqual(assigned.teams[1].roster,target.roster);assert.deepEqual(assigned.replayReveals?.[target.id],undefined);
 for(const key of ['history','used','byes','schedule','draftOrder'] as const)assert.deepEqual(assigned[key],s[key]);
 assert.equal((await item.POST(request({action:'lineup',lineup:target.lineup,revision:assigned.revision},newUser),ctx)).status,400);
 assert.equal((await collection.POST(request({action:'join',code:assigned.inviteCode,teamId:target.id},newUser))).status,200);
});

test('lobby resize/remove and manual draft order validate boundaries without changing a started league',async()=>{
 const db=fresh();let s=newSeason('owner',{name:'Lobby controls',teamName:'Owner',capacity:4,format:'seventeen'},'LOBBY');s=joinSeason(s,'manager','Remove me');
 s=seasonAction(s,'owner',{action:'resizeLeague',capacity:2,playoffTeams:4});assert.equal(s.capacity,2);assert.equal(s.regularRounds,16);
 for(const capacity of [0,1,3,17])assert.throws(()=>seasonAction(s,'owner',{action:'resizeLeague',capacity}));
 assert.throws(()=>seasonAction(s,'manager',{action:'resizeLeague',capacity:4}));
 s=seasonAction(s,'owner',{action:'removeManager',teamId:s.teams[1].id,confirm:true,inviteCode:'ROTATED'});assert.equal(s.teams.length,1);assert.equal(s.capacity,2);s=joinSeason(s,'replacement','New manager');
 const order=s.teams.map(t=>t.id).reverse();s=seasonAction(s,'owner',{action:'startDraft',orderMode:'manual',orderIndexes:[1,0]});assert.deepEqual(s.draftOrder,order);assert.equal(s.orderMode,'manual');assert.throws(()=>seasonAction(s,'owner',{action:'resizeLeague',capacity:4}));assert.throws(()=>seasonAction(s,'owner',{action:'startDraft',orderMode:'manual',orderIndexes:[0,1]}));
 db.sql.close();
});

test('caretaker locks only vacant existing rosters and preserves used games until every playing team locks',()=>{
 let s=newSeason('owner',{name:'Caretaker',teamName:'Owner',capacity:2,format:'seventeen'},'CODE');s=joinSeason(s,'manager','Departing');s=seasonAction(s,'owner',{action:'startDraft'});while(s.status==='draft')s=seasonAction(s,'owner',{action:'autopick'});
 const departed=s.teams[1].id;const before=structuredClone(s);s=seasonAction(s,'owner',{action:'removeManager',teamId:departed,confirm:true,inviteCode:'NEW'});s=seasonAction(s,'owner',{action:'caretaker'});assert.equal(s.teams[1].locked,true);assert.equal(s.teams[0].locked,false);assert.deepEqual(s.teams.map(t=>t.roster),before.teams.map(t=>t.roster));assert.deepEqual(s.history,before.history);assert.deepEqual(s.used,before.used);
 const ready=structuredClone(s);assert.throws(()=>seasonAction(s,'owner',{action:'caretaker'}),/No vacant/);assert.deepEqual(s,ready);
 s=seasonAction(s,'owner',{action:'lock',lineup:s.teams[0].lineup,acceptBye:true});assert.equal(s.history.length,1);assert.equal(s.used.length,20);assert.deepEqual(s.history[0].rosterSnapshots,Object.fromEntries(before.teams.map(t=>[t.id,t.roster])));
});

test('caretaker minimizes avoidable bye starters even when one position has an unavoidable bye',()=>{
 let s=newSeason('owner',{name:'Bye coverage',teamName:'Owner',capacity:2,format:'seventeen'},'CODE');s=joinSeason(s,'manager','Vacant');s=seasonAction(s,'owner',{action:'startDraft'});while(s.status==='draft')s=seasonAction(s,'owner',{action:'autopick'});
 const t=s.teams[1],{ATHLETES}=auditPlayers;let backup=t.roster.find(id=>id!==t.lineup.QB&&ATHLETES.find(a=>a.id===id)?.position==='QB');
 if(!backup){const a=ATHLETES.find(a=>a.position==='QB'&&a.gameCount>=17&&!s.teams.some(team=>team.roster.includes(a.id)))!;const bench=t.roster.find(id=>!Object.values(t.lineup).includes(id))!;t.roster=t.roster.map(id=>id===bench?a.id:id);backup=a.id;}
 s.round=5;for(const id of t.roster)s.byes!.weeks[id]=6;s.byes!.weeks[t.lineup.QB]=5;for(const id of t.roster.filter(id=>ATHLETES.find(a=>a.id===id)?.position==='DEF'))s.byes!.weeks[id]=5;
 s=seasonAction(s,'owner',{action:'removeManager',teamId:t.id,confirm:true,inviteCode:'NEW'});s=seasonAction(s,'owner',{action:'caretaker'});assert.equal(s.teams[1].lineup.QB,backup);assert.equal(s.teams[1].lineup.DEF,t.lineup.DEF);
});
