import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {registerHooks} from 'node:module';import test from 'node:test';
registerHooks({load(url,c,n){if(url.startsWith('file:')&&url.endsWith('.json'))return {format:'module',shortCircuit:true,source:`export default ${readFileSync(new URL(url),'utf8')}`};return n(url,c);},resolve(id,c,n){try{return n(id,c);}catch(e){if(id.startsWith('.')&&!/\.[a-z]+$/i.test(id))return n(`${id}.ts`,c);throw e;}}});
const {FIRST_BYE_WEEK,assignByes,normalizeByes,onBye,byeLabel,byeStatus,byeStatusLabel}=await import('../lib/season-byes');const {ATHLETES,POSITIONS}=await import('../lib/game-model');const {newSeason,joinSeason,seasonAction,publicSeason}=await import('../lib/season-engine');const {seasonRecap}=await import('../lib/season-recap');const {draftInsights,draftRankings}=await import('../lib/draft-insights');
function active(){let s=newSeason('a',{name:'Bye QA',teamName:'A',capacity:2,format:'seventeen',hallCap:0},'test');s=joinSeason(s,'b','B');s=seasonAction(s,'a',{action:'startDraft'});while(s.status==='draft')s=seasonAction(s,'a',{action:'autopick'});return s;}
test('one deterministic fictional bye per athlete including defenses; balanced by position and changes across seasons',()=>{const a=assignByes('one',14),b=assignByes('two',14);assert.equal(Object.keys(a.weeks).length,ATHLETES.length);assert.deepEqual(a,assignByes('one',14));assert.notDeepEqual(a,b);for(const w of Object.values(a.weeks))assert.ok(w>=5&&w<14);for(const p of POSITIONS){const counts=Array.from({length:a.lastWeek-a.firstWeek+1},(_,i)=>ATHLETES.filter(x=>x.position===p&&a.weeks[x.id]===i+a.firstWeek).length);assert.ok(Math.max(...counts)-Math.min(...counts)<=1);}});
test('migration leaves current and past rounds untouched; late seasons defer',()=>{const s=active();delete s.byes;s.round=7;const normalized=normalizeByes(s);assert.ok(Object.values(normalized.byes!.weeks).every(w=>w>7));assert.deepEqual(normalizeByes(normalized),normalized);assert.deepEqual(s.history,normalized.history);s.round=17;assert.equal(normalizeByes(s).byes!.legacyDeferred,true);assert.equal(Object.keys(normalizeByes(s).byes!.weeks).length,0);});
test('bye persists across reload, trades, add/drop; zero score consumes no draw; lock requires acknowledgement',()=>{let s=active();const a=s.teams[0],b=s.teams[1],id=a.lineup.QB,bye=s.byes!.weeks[id];s.round=bye;const map=structuredClone(s.byes);assert.throws(()=>seasonAction(s,'a',{action:'lock',lineup:a.lineup}),/simulated BYE/);s=seasonAction(s,'a',{action:'offer',to:b.id,give:id,receive:b.lineup.QB});s=seasonAction(s,'b',{action:'accept',tradeId:s.trades[0].id});assert.deepEqual(s.byes,map);const add=ATHLETES.find(x=>x.position==='QB'&&!x.legend&&x.gameCount>=17&&!s.teams.some(t=>t.roster.includes(x.id)))!.id;s=seasonAction(s,'b',{action:'swap',drop:id,add});s=seasonAction(s,'b',{action:'swap',drop:add,add:id});assert.deepEqual(s.byes,map);s=JSON.parse(JSON.stringify(s));assert.equal(s.byes!.weeks[id],bye);s=seasonAction(s,'a',{action:'closeRound'});const draws=[...Object.values(s.history.at(-1)!.draws).flat(),...Object.values(s.history.at(-1)!.benchDraws||{}).flat()];assert.ok(draws.some(d=>d.simulatedBye));assert.equal(s.used.length,draws.filter(d=>!d.simulatedBye).length);for(const d of draws.filter(d=>d.simulatedBye)){assert.equal(d.points,0);assert.deepEqual(d.performance,{});}const pub=publicSeason(s,'a');assert.equal(seasonRecap(pub,pub.history[0]),null);assert.ok(pub.history[0].draws[b.id].some(d=>d.simulatedBye));assert.throws(()=>seasonAction(s,'a',{action:'closeRound'}));s.round=17;assert.ok(ATHLETES.every(a=>!onBye(s,a.id)));});
test('scouting and ranks unchanged by consumed IDs; recap only after reveal and never changes saved results',()=>{let s=active();s=seasonAction(s,'a',{action:'closeRound'});const before=JSON.stringify(s.history),id=s.teams[0].lineup.QB;assert.deepEqual(draftInsights(id,[]),draftInsights(id,s.used));assert.deepEqual(draftRankings([]),draftRankings(s.used));let pub=publicSeason(s,'a');assert.equal(seasonRecap(pub,pub.history[0]),null);s=seasonAction(s,'a',{action:'revealReplay',round:1});pub=publicSeason(s,'a');const recap=seasonRecap(pub,pub.history[0]);assert.ok(recap?.top);assert.equal(recap.upset,null);assert.equal(JSON.stringify(s.history),before);assert.deepEqual(seasonRecap(pub,pub.history[0]),recap);});
test('recap upset uses prior standings, excludes ties and byes, and exposes no unrevealed recap',()=>{const s=active(),pub=publicSeason(s,'a'),[a,b]=s.teams;pub.history=[{number:1,phase:'regular',resolvedAt:'saved',receiptsHidden:false,matches:[{home:a.id,away:b.id,homeScore:100,awayScore:10,winner:a.id}],draws:{}}];const legend=ATHLETES.find(a=>a.legend)!.id;const round={number:2,phase:'regular' as const,resolvedAt:'saved',receiptsHidden:false,matches:[{home:a.id,away:b.id,homeScore:20,awayScore:50,winner:b.id}],draws:{[a.id]:[{athleteId:legend,points:-2,performance:{}}],[b.id]:[{athleteId:b.lineup.QB,points:50,performance:{}},{athleteId:b.lineup.DEF,points:0,simulatedBye:true as const,performance:{}}]}};const recap=seasonRecap(pub,round)!;assert.equal(recap.upset!.gap,1);assert.equal(recap.top!.points,50);assert.equal(recap.lowestLegend!.points,-2);assert.equal(seasonRecap(pub,{...round,receiptsHidden:true}),null);assert.equal(seasonRecap(pub,{...round,matches:[{...round.matches[0],homeScore:50}]})!.upset,null);});

test('late legacy migration defers rather than putting every player on one, two or three remaining weeks',()=>{for(const remaining of [0,1,2,3]){const s=active();delete s.byes;s.round=s.regularRounds-1-remaining;const n=normalizeByes(s);assert.equal(n.byes!.legacyDeferred,true);assert.equal(Object.keys(n.byes!.weeks).length,0);assert.equal(n.teams.filter(t=>t.roster.some(id=>onBye(n,id))).length,0);}const s=active();delete s.byes;s.round=s.regularRounds-5;assert.equal(normalizeByes(s).byes!.legacyDeferred,undefined);});
test('v18 crowding repair preserves locked/current and historical results; never moves good schedules',()=>{const s=active();s.round=15;s.byes={version:1,firstWeek:15,lastWeek:15,weeks:Object.fromEntries(ATHLETES.map(a=>[a.id,15]))};const before=JSON.stringify(s.history),unlocked=normalizeByes(s);assert.equal(Object.keys(unlocked.byes!.weeks).length,0);assert.equal(unlocked.byes!.repairedCrowdedWindow,true);assert.equal(JSON.stringify(unlocked.history),before);s.teams[0].locked=true;assert.deepEqual(normalizeByes(s).byes!.weeks,s.byes.weeks);s.teams[0].locked=false;s.status='review';assert.deepEqual(normalizeByes(s).byes!.weeks,s.byes.weeks);const good=active();good.byes!.version=1;const saved=JSON.stringify(good.byes);good.round=14;assert.deepEqual(normalizeByes(good).byes!.weeks,JSON.parse(saved).weeks);});
test('future scheduled labels cannot be mistaken for current absences and completed byes are marked separately',()=>{const s=active(),id=s.teams[0].lineup.QB,week=s.byes!.weeks[id];s.round=week-1;assert.match(byeLabel(s,id),/^Scheduled rest week/);assert.equal(onBye(s,id),false);s.round=week;assert.match(byeLabel(s,id),/^BYE this week/);assert.equal(onBye(s,id),true);s.status='review';assert.match(byeLabel(s,id),/^Rest week completed/);});

test('v18 whole-roster collision with a healthy window is balanced once without changing other players or historical games',()=>{const s=active();s.byes!.version=1;s.round=3;const team=s.teams[0],other=s.teams[1];for(const id of team.roster)s.byes!.weeks[id]=6;const otherWeeks=other.roster.map(id=>s.byes!.weeks[id]),history=JSON.stringify(s.history);const fixed=normalizeByes(s);assert.equal(fixed.byes!.repairedRosterCollision,true);for(let week=3;week<s.regularRounds;week++)assert.ok(team.roster.filter(id=>fixed.byes!.weeks[id]===week).length<=2);assert.deepEqual(other.roster.map(id=>fixed.byes!.weeks[id]),otherWeeks);assert.equal(JSON.stringify(fixed.history),history);assert.deepEqual(normalizeByes(fixed),fixed);const traded=structuredClone(fixed);traded.teams[0].roster.reverse();assert.deepEqual(normalizeByes(traded).byes,fixed.byes);});

test('pastel availability states distinguish current, next, later, played and playoff boundaries without changing schedules',()=>{const s=active(),id=s.teams[0].lineup.QB;s.round=5;s.byes!.weeks[id]=5;const before=JSON.stringify(s);assert.equal(byeStatus(s,id),'current');assert.equal(byeStatusLabel(s,id),'BYE THIS WEEK');assert.equal(JSON.stringify(s),before);s.byes!.weeks[id]=6;assert.equal(byeStatus(s,id),'next');assert.equal(byeStatusLabel(s,id),'Available · Bye next week');s.byes!.weeks[id]=7;assert.equal(byeStatus(s,id),'ready');s.byes!.weeks[id]=4;assert.equal(byeStatus(s,id),'ready');s.round=s.regularRounds;s.byes!.weeks[id]=s.round+1;assert.equal(byeStatus(s,id),'ready');s.round++;assert.equal(byeStatus(s,id),'ready');delete s.byes!.weeks[id];assert.equal(byeStatus(s,id),'ready');s.byes!.legacyDeferred=true;assert.equal(byeStatus(s,id),'ready');s.status='complete';s.byes!.weeks[id]=s.round+1;assert.equal(byeStatus(s,id),'ready');});

test('Weeks 1–4 are excluded from new regular-season windows, including earlier explicit firstWeek values',()=>{
 for(const length of [6,10,14,15,16,17,30,60])for(const firstWeek of [undefined,1,0,-10,2]){
  const byes=assignByes('opening-week-'+length,length,firstWeek);assert.equal(byes.firstWeek,FIRST_BYE_WEEK);assert.ok(Object.values(byes.weeks).every(w=>w>=5&&w<length));if(length<9){assert.equal(byes.legacyDeferred,true);assert.equal(Object.keys(byes.weeks).length,0);}else assert.equal(Object.keys(byes.weeks).length,ATHLETES.length);
  assert.ok(ATHLETES.every(a=>!onBye({byes,round:1,regularRounds:length},a.id)));
 }
});
test('unplayed Week 1 legacy maps migrate deterministically, preserve other assignments and locked lineups, and balance rosters',()=>{
 for(const version of [1,2] as const)for(const status of ['lobby','draft','active'] as const){
  const s=active();s.status=status;s.byes!.version=version;s.byes!.firstWeek=1;
  const moved=new Set([...s.teams.flatMap(t=>t.roster),...ATHLETES.filter(a=>a.position==='DEF').map(a=>a.id)]);for(const id of moved)s.byes!.weeks[id]=1;
  s.teams[0].locked=true;const before=structuredClone(s),fixed=normalizeByes(s);assert.ok(fixed.byes!.repairedWeekOne);assert.ok(Object.values(fixed.byes!.weeks).every(w=>w>=5&&w<s.regularRounds));
  for(const id of Object.keys(before.byes!.weeks))if(!moved.has(id))assert.equal(fixed.byes!.weeks[id],before.byes!.weeks[id]);
  for(const team of fixed.teams)for(let w=5;w<s.regularRounds;w++)assert.ok(team.roster.filter(id=>fixed.byes!.weeks[id]===w).length<=2);
  assert.deepEqual(fixed.teams,before.teams);assert.deepEqual(fixed.history,before.history);assert.deepEqual(fixed.used,before.used);assert.deepEqual(normalizeByes(fixed),fixed);assert.deepEqual(normalizeByes(JSON.parse(JSON.stringify(s))).byes,fixed.byes);assert.deepEqual(s,before);
  assert.ok(ATHLETES.every(a=>byeStatus(fixed,a.id)!=='current'));const next=ATHLETES.find(a=>fixed.byes!.weeks[a.id]===5)!;assert.equal(byeStatus({...fixed,round:4},next.id),'next');assert.equal(onBye({...fixed,round:5},next.id),true);
 }
});
test('whole legacy Week 1 pool spreads across later regular weeks without playoff or position pileups',()=>{
 const s=active();s.byes={version:1,firstWeek:1,lastWeek:1,weeks:Object.fromEntries(ATHLETES.map(a=>[a.id,1]))};const fixed=normalizeByes(s);assert.equal(Object.keys(fixed.byes!.weeks).length,ATHLETES.length);for(const p of POSITIONS){const counts=Array.from({length:s.regularRounds-FIRST_BYE_WEEK},(_,i)=>ATHLETES.filter(a=>a.position===p&&fixed.byes!.weeks[a.id]===i+FIRST_BYE_WEEK).length);assert.ok(Math.max(...counts)-Math.min(...counts)<=1,`${p} distribution: ${counts}`);}assert.deepEqual(normalizeByes(fixed),fixed);
});
test('finalized or elapsed Week 1 byes remain historical and never receive a second rest week',()=>{
 const s=active(),id=s.teams[0].lineup.QB;s.byes!.weeks[id]=1;
 for(const fixture of [{...s,round:2},{...s,status:'review' as const},{...s,status:'complete' as const},{...s,history:[{number:1,phase:'regular' as const,matches:[],draws:{[s.teams[0].id]:[{athleteId:id,points:0,simulatedBye:true as const,performance:{}}]},resolvedAt:'saved'}]}]){
  const before=JSON.stringify(fixture),fixed=normalizeByes(fixture);assert.equal(fixed.byes!.weeks[id],1);assert.equal(JSON.stringify(fixture),before);assert.deepEqual(fixed.history,fixture.history);assert.deepEqual(fixed.used,fixture.used);assert.deepEqual(normalizeByes(fixed),fixed);assert.ok(!onBye({...fixed,round:2},id));
 }
});
test('online Week 1 repair scores all starters and bench normally without consuming any premature bye',()=>{
 let s=active();for(const id of Object.keys(s.byes!.weeks))s.byes!.weeks[id]=1;const rosters=structuredClone(s.teams.map(t=>t.roster));s=seasonAction(s,'a',{action:'closeRound'});const round=s.history[0],draws=[...Object.values(round.draws).flat(),...Object.values(round.benchDraws||{}).flat()];assert.equal(draws.length,20);assert.ok(draws.every(d=>!d.simulatedBye));assert.equal(s.used.length,20);assert.deepEqual(s.teams.map(t=>t.roster),rosters);assert.ok(Object.values(s.byes!.weeks).every(w=>w>1));
});
