import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {registerHooks} from 'node:module';import test from 'node:test';
import type {DemoDraft} from '../lib/demo-draft-model';
registerHooks({load(url,c,n){if(url.startsWith('file:')&&url.endsWith('.json'))return {format:'module',shortCircuit:true,source:`export default ${readFileSync(new URL(url),'utf8')}`};return n(url,c);},resolve(id,c,n){try{return n(id,c);}catch(e){if(id.startsWith('.')&&!/\.[a-z]+$/i.test(id))return n(`${id}.ts`,c);throw e;}}});
const {newSeason,joinSeason,seasonAction,tradePreview,repairLineup,publicSeason}=await import('../lib/season-engine');const {demoDraftAction,cpuTradeDecision}=await import('../lib/demo-draft-engine');const {ATHLETES,PERFORMANCES}=await import('../lib/historical-data');
// Trades below consume the original Strict performance ledger.
let seed=newSeason('human',{name:'Trades',teamName:'Human',capacity:2,format:'seventeen',hallCap:2,scoringMode:'strict'},'test');seed=joinSeason(seed,'cpu','Computer');seed=seasonAction(seed,'human',{action:'startDraft'});while(seed.status==='draft')seed=seasonAction(seed,'human',{action:'autopick'});
const [a,b]=seed.teams;
function solo(season=seed):DemoDraft{return {id:season.id,revision:0,createdAt:season.createdAt,status:'complete',rosterSize:10,teams:season.teams.map((t,i)=>({id:t.id,name:t.name,control:i?'computer':'human',strategy:i?0:null,roster:[...t.roster]})),order:season.draftOrder,pick:20,picks:[],humanTeamId:a.id,season:{...structuredClone(season),ownerId:a.id,teams:season.teams.map(t=>({...structuredClone(t),userId:t.id}))}};}
const offer={action:'offer',to:b.id,give:a.lineup.QB,receive:b.lineup.QB};
test('online pending offer, duplicate rejection, owner-only cancel/decline/accept and week expiry',()=>{let s=seasonAction(seed,'human',offer);const id=s.trades[0].id;assert.throws(()=>seasonAction(s,'human',offer),/already pending/);assert.throws(()=>seasonAction(s,'human',{action:'accept',tradeId:id}),/receiving/);assert.throws(()=>seasonAction(s,'cpu',{action:'cancel',tradeId:id}),/sender/);for(const action of ['reject','cancel']){const closed=seasonAction(s,action==='cancel'?'human':'cpu',{action,tradeId:id});assert.throws(()=>seasonAction(closed,'cpu',{action:'accept',tradeId:id}),/no longer pending/);}s=seasonAction(s,'human',{action:'closeRound'});assert.equal(s.trades[0].status,'expired');assert.throws(()=>seasonAction(s,'human',offer),/next week/);s=seasonAction(s,'human',{action:'next'});assert.throws(()=>seasonAction(s,'cpu',{action:'accept',tradeId:id}),/no longer pending/);});
test('invalid player ownership, same team, positional depth and locked/resolved/completed trades fail atomically',()=>{for(const body of [{...offer,to:a.id},{...offer,receive:offer.give},{...offer,give:'unknown'},{...offer,give:a.lineup.DEF,receive:b.lineup.QB}])assert.throws(()=>seasonAction(seed,'human',body));for(const status of ['review','complete','draft'] as const)assert.throws(()=>seasonAction({...seed,status},'human',offer));for(const index of [0,1]){const s=structuredClone(seed);s.teams[index].locked=true;assert.throws(()=>seasonAction(s,'human',offer),/locked/);}const s=structuredClone(seed);s.hallCap=1;const used=new Set(s.teams[1].roster);const roster:string[]=[];for(const [position,count] of [['QB',1],['RB',2],['WR',3],['TE',2],['DEF',2]] as const){const choices=ATHLETES.filter(x=>x.position===position&&!!x.legend===(position==='RB')&&!used.has(x.id)&&x.gameCount>=17);roster.push(...choices.slice(0,count).map(x=>x.id));}s.teams[0].roster=roster;s.teams[0].lineup=repairLineup(s,s.teams[0]);const legendQb=ATHLETES.find(x=>x.position==='QB'&&x.legend&&!roster.includes(x.id))!.id;const outgoing=s.teams[0].lineup.QB;s.teams[1].roster=s.teams[1].roster.map(id=>id===s.teams[1].lineup.QB?legendQb:id);assert.doesNotThrow(()=>tradePreview(s,s.teams[0],s.teams[1],outgoing,legendQb));assert.equal(JSON.stringify(seed),JSON.stringify(structuredClone(seed)));});
test('trade carries byes and consumed games, preserves historical snapshots and hidden receipts',()=>{let s=seasonAction(seed,'human',{action:'closeRound'});s=seasonAction(s,'human',{action:'next'});const history=JSON.stringify(s.history),used=[...s.used],byes=structuredClone(s.byes);s=seasonAction(s,'human',offer);s=seasonAction(s,'cpu',{action:'accept',tradeId:s.trades[0].id});assert.equal(JSON.stringify(s.history),history);assert.deepEqual(s.used,used);assert.deepEqual(s.byes,byes);assert.ok(s.teams[0].roster.includes(offer.receive));assert.equal(new Set(s.teams.flatMap(t=>t.roster)).size,20);assert.equal(publicSeason(s,'human').history[0].benchDraws,undefined);for(const t of s.teams)assert.equal(new Set(Object.values(repairLineup(s,t))).size,6);const pending=seasonAction(s,'human',{...offer,give:offer.receive,receive:offer.give});const bad=structuredClone(pending);bad.used=PERFORMANCES.filter(p=>p.athleteId===offer.receive).map(p=>p.id);const frozen=JSON.stringify(bad);assert.throws(()=>seasonAction(bad,'cpu',{action:'accept',tradeId:bad.trades[0].id}),/enough unused/);assert.equal(JSON.stringify(bad),frozen);});
test('CPU accepts fair improvement, declines value loss, response persists, no hidden draw knowledge',()=>{const d=solo();let accepted=false,rejected=false;for(const give of a.roster)for(const receive of b.roster){try{tradePreview(d.season!,d.season!.teams[0],d.season!.teams[1],give,receive);}catch{continue;}const decision=cpuTradeDecision(d.season!,b.id,give,receive);if(decision.accepted&&accepted||!decision.accepted&&rejected)continue;const before=JSON.stringify(d),result=demoDraftAction(d,{action:'offer',to:b.id,give,receive});assert.equal(JSON.stringify(d),before);const trade=result.season!.trades[0];assert.equal(trade.status,decision.accepted?'accepted':'rejected');assert.match(trade.reason!,decision.accepted?/Accepted/:/Declined/);assert.deepEqual(result.season!.used,d.season!.used);assert.deepEqual(result.season!.byes,d.season!.byes);assert.deepEqual(JSON.parse(JSON.stringify(result)).season.trades,result.season!.trades);if(decision.accepted){accepted=true;assert.ok(result.season!.teams[0].roster.includes(receive));assert.throws(()=>demoDraftAction(result,{action:'offer',to:b.id,give,receive}),/belong/);}else{rejected=true;assert.deepEqual(result.season!.teams,d.season!.teams);}assert.deepEqual(cpuTradeDecision({...d.season!,used:PERFORMANCES.map(p=>p.id)},b.id,give,receive),decision);}assert.ok(accepted,'A legal fair trade is accepted');assert.ok(rejected,'A legal unfavorable trade is declined');assert.throws(()=>demoDraftAction(d,{action:'accept',tradeId:'fake'}),/supported/);assert.throws(()=>demoDraftAction(d,{action:'offer',to:a.id}),/computer team/);});
