import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {registerHooks} from 'node:module';
import {DatabaseSync,type SQLInputValue} from 'node:sqlite';
import test from 'node:test';
import type {DemoDraft} from '../lib/demo-draft-model';
const root=new URL('../',import.meta.url);
let database:ReturnType<typeof memoryDatabase>;
registerHooks({
 load(url,context,next){if(url.startsWith('file:')&&url.endsWith('.json'))return {format:'module',shortCircuit:true,source:`export default ${readFileSync(new URL(url),'utf8')}`};if(url===new URL('../db/index.ts',import.meta.url).href)return {format:'module',shortCircuit:true,source:'export function database(){return globalThis.__unifiedDraftDB;}'};return next(url,context);},
 resolve(id,context,next){if(id==='@/db')return next(new URL('db/index.ts',root).href,context);if(id.startsWith('@/'))return next(new URL(`${id.slice(2)}.ts`,root).href,context);try{return next(id,context);}catch(e){if(id.startsWith('.')&&!/\.[a-z]+$/i.test(id))return next(`${id}.ts`,context);throw e;}}
});
const {newDemoDraft,demoDraftAction}=await import('../lib/demo-draft-engine');
const {unifiedDraftCandidate,unifyUnscoredDraft}=await import('../lib/unified-draft');
const api=await import('../app/api/demo/route');
const {withBatch}=await import('./helpers/memory-d1-batch');
function memoryDatabase(){const sql=new DatabaseSync(':memory:');for(const name of readdirSync(new URL('drizzle/',root)).filter(n=>n.endsWith('.sql')).sort())sql.exec(readFileSync(new URL(`drizzle/${name}`,root),'utf8'));return {sql,prepare(query:string){let values:SQLInputValue[]=[];return {bind(...args:unknown[]){values=args as SQLInputValue[];return this;},async first(){return sql.prepare(query).get(...values)??null;},async all(){return {results:sql.prepare(query).all(...values)};},async run(){return {meta:{changes:Number(sql.prepare(query).run(...values).changes)}};}};}};}
function seed(version=5,begin=false){database=withBatch(memoryDatabase());Object.assign(globalThis,{__unifiedDraftDB:database});let draft=newDemoDraft('Preserve my team',.5,{modern:true,capacity:2,kickers:true,opening:true,orderMode:'manual',orderIndexes:[1,0],scoringMode:'strict'});if(begin)draft=demoDraftAction(draft,{action:'beginDraft'});if(version===4){const rules={...draft.scoring!,version:4 as const};delete rules.mode;draft.scoring=rules;}draft.revision=19;const raw=JSON.stringify(draft,null,2);database.sql.prepare('INSERT INTO demo_drafts(owner_id,id,state,revision,updated_at) VALUES(?,?,?,?,?)').run('owner',draft.id,raw,draft.revision,'original timestamp');return {draft,raw};}
function request(draft:DemoDraft,action='unifyDraft',revision=draft.revision){return new Request('https://unified.test/api/demo',{method:'POST',headers:{'oai-authenticated-user-id':'owner',origin:'https://unified.test','content-type':'application/json'},body:JSON.stringify({action,seasonId:draft.id,revision})});}
function saved(){return JSON.parse(database.sql.prepare('SELECT state FROM demo_drafts').get()!.state as string) as DemoDraft;}
test('unification preserves every pick, roster, identity, order and existing rest date',()=>{const draft=newDemoDraft('Already drafting',1,{modern:true,capacity:2,kickers:true,orderMode:'manual',orderIndexes:[1,0],scoringMode:'strict'});assert.ok(draft.picks.length);const before=structuredClone(draft),next=unifyUnscoredDraft(draft)!;assert.ok(next);assert.deepEqual(draft,before);for(const key of ['id','createdAt','revision','pick','picks','teams','order','orderMode','orderRevealPending','rosterSize','playoffTeams'] as const)assert.deepEqual(next[key],draft[key],key);assert.equal(next.scoring!.mode,'historical');assert.equal(next.scoring!.receptionPoints,1);for(const [id,week] of Object.entries(draft.byes!.weeks))assert.equal(next.byes!.weeks[id],week);assert.equal(Object.keys(next.byes!.weeks).length,1308);});
test('exact raw backup and scoring correction commit atomically, once, with CAS',async()=>{const {draft,raw}=seed();const response=await api.POST(request(draft));assert.equal(response.status,200);const next=saved();assert.equal(next.revision,20);assert.equal(next.scoring!.mode,'historical');assert.deepEqual(next.picks,draft.picks);assert.deepEqual(next.order,draft.order);assert.deepEqual(next.teams,draft.teams);const backup=database.sql.prepare('SELECT * FROM demo_scoring_backups').get()!;assert.equal(backup.state,raw);assert.equal(backup.source_revision,19);assert.equal(backup.source_updated_at,'original timestamp');assert.equal((await api.POST(request(draft))).status,409);assert.equal((await api.POST(request(next))).status,200);assert.equal(database.sql.prepare('SELECT COUNT(*) AS n FROM demo_scoring_backups').get()!.n,1);});
test('missing backup migration never changes a saved draft',async()=>{const {draft,raw}=seed();database.sql.exec('DROP TRIGGER backup_demo_before_scoring_unification');assert.equal((await api.POST(request(draft))).status,503);assert.equal(database.sql.prepare('SELECT state FROM demo_drafts').get()!.state,raw);});
test('backup failure aborts correction and leaves the original saved row untouched',async()=>{const {draft,raw}=seed();database.sql.exec("CREATE TRIGGER reject_backup BEFORE INSERT ON demo_scoring_backups BEGIN SELECT RAISE(ABORT,'backup unavailable'); END");assert.equal((await api.POST(request(draft))).status,503);assert.equal(database.sql.prepare('SELECT state FROM demo_drafts').get()!.state,raw);assert.equal(database.sql.prepare('SELECT COUNT(*) AS n FROM demo_scoring_backups').get()!.n,0);});
test('recovery before subsequent play preserves backup, bumps revision and does not auto-migrate again',async()=>{const {draft}=seed();await api.POST(request(draft));const next=saved();assert.equal((await api.POST(request(next,'undoUnifiedDraft'))).status,200);const restored=saved();assert.equal(restored.revision,21);assert.equal(restored.scoring!.mode,'strict');assert.equal(unifiedDraftCandidate(restored),false);assert.deepEqual(restored.teams,draft.teams);assert.equal(database.sql.prepare('SELECT COUNT(*) AS n FROM demo_scoring_backups').get()!.n,1);});
test('scored seasons, completed/legacy drafts, unknown actors and malformed pick ledgers never qualify',()=>{const {draft}=seed();for(const change of [{status:'complete'},{rosterSize:undefined},{scoring:{...draft.scoring,version:3}},{history:[{}]},{used:['draw']},{season:{history:[],used:[]}},{unificationReverted:true}])assert.equal(unifiedDraftCandidate(Object.assign(structuredClone(draft),change) as DemoDraft),false);const invalid=structuredClone(draft);invalid.teams[0].roster=['unknown'];invalid.pick=1;invalid.picks=[{number:1,round:1,teamId:invalid.teams[0].id,athleteId:'unknown',control:'human',at:'date',reason:''}];assert.equal(unifiedDraftCandidate(invalid),false);const started=demoDraftAction(draft,{action:'beginDraft'});assert.ok(started.picks.length);started.picks[0].athleteId='malformed-ledger';assert.equal(unifiedDraftCandidate(started),false);});
test('reset archives cannot overwrite the separate migration snapshot',async()=>{const {draft,raw}=seed();await api.POST(request(draft));const next=saved();const response=await api.POST(new Request('https://unified.test/api/demo',{method:'POST',headers:{'oai-authenticated-user-id':'owner',origin:'https://unified.test','content-type':'application/json'},body:JSON.stringify({action:'reset',confirm:true,seasonId:next.id,revision:next.revision})}));assert.equal(response.status,200);assert.equal(database.sql.prepare('SELECT state FROM demo_scoring_backups').get()!.state,raw);assert.equal(JSON.parse(database.sql.prepare('SELECT state FROM demo_archives').get()!.state as string).scoring.mode,'historical');});

test('canonical unscored v4 draft joins the mixed pool with an exact backup and preserved picks',async()=>{const {draft,raw}=seed(4,true);assert.ok(draft.picks.length);assert.equal(unifiedDraftCandidate(draft),true);assert.equal((await api.POST(request(draft))).status,200);const next=saved();assert.equal(next.scoring!.mode,'historical');assert.deepEqual(next.teams,draft.teams);assert.deepEqual(next.order,draft.order);assert.deepEqual(next.picks,draft.picks);assert.equal(database.sql.prepare('SELECT state FROM demo_scoring_backups').get()!.state,raw);const custom=structuredClone(draft);custom.scoring={...custom.scoring!,passingTD:6};assert.equal(unifiedDraftCandidate(custom),false);});
test('v4 correction waits for its own backup trigger even when the v5 trigger already exists',async()=>{const {draft,raw}=seed(4);database.sql.exec('DROP TRIGGER backup_demo_v4_before_scoring_unification');assert.equal((await api.POST(request(draft))).status,503);assert.equal(database.sql.prepare('SELECT state FROM demo_drafts').get()!.state,raw);});
