import {ALL_ATHLETES,historicalTeamLabel,statLine,scoringBreakdown} from '@/lib/game-model';
import {fullReceipt,historicalDrawLabel} from '@/lib/fantasy-replay';
import {scoringFor} from '@/lib/scoring-rules';
import type {PublicSeason,PublicSeasonRound} from '@/lib/season-model';
const players=new Map(ALL_ATHLETES.map(a=>[a.id,a]));
/** Only mounted for a completed replay or explicitly revealed saved results. */
export function BenchPoints({league,round,teamIds}:{league:PublicSeason;round:PublicSeasonRound;teamIds?:string[]}){
 if(round.receiptsHidden)return null;
 return <section className="bench-points broadcast-bench-points" aria-label="Bench points"><header className="bench-section-heading"><div><span className="replay-section-kicker">OFF THE SCOREBOARD</span><h3>Bench points</h3></div><span className="bench-excluded-badge">NOT IN TEAM TOTAL</span></header><p>These games are used up, just like starters’ games. Bench points do not count toward team scores or standings.</p>{!round.benchDraws?<p>Bench scores unavailable for this previously saved week. No extra games were drawn.</p>:<div className="season-team-rosters">{Object.entries(round.benchDraws).filter(([id])=>!teamIds||teamIds.includes(id)).map(([id,draws])=>{const complete=draws.every(d=>d.points!==null),total=draws.reduce((sum,d)=>sum+(d.points??0),0);return <section key={id}><h4>{league.teams.find(t=>t.id===id)?.name}</h4><p className="bench-total">Points left on bench: <strong>{complete?total.toFixed(2):'Unavailable'}</strong>{!complete&&<span> · Scored players: {total.toFixed(2)}</span>}</p>{draws.map(d=><article className="draw-card bench-player-card" key={d.athleteId}><div className="draw-top bench-player-heading"><div className="bench-player-identity"><h4 className="bench-player-name">{players.get(d.athleteId)?.name||'Player name unavailable'}</h4><span className="bench-player-position">{players.get(d.athleteId)?.position||'Position unavailable'} · Bench</span><span className="bench-player-game">{d.simulatedBye?'Simulated BYE':d.unavailable?'No unused historical games':historicalDrawLabel(d.performance)}</span></div><strong className="bench-player-score"><small>Bench points</small>{d.points===null?'Unavailable':d.points.toFixed(2)}</strong></div>{fullReceipt(d.performance)?<div className="draw-details"><span className="game-badge">{historicalTeamLabel(d.performance,d.performance.teamAtTime)} vs {historicalTeamLabel(d.performance,d.performance.opponent)}</span><p>{statLine(d.performance)}</p><details className="score-receipt"><summary>How this bench score adds up</summary><dl>{(players.has(d.athleteId)?scoringBreakdown(d.performance.stats,players.get(d.athleteId)!.position,scoringFor(round)):[]).map(item=><div key={item.label}><dt>{item.label}<small>{item.calculation}</small></dt><dd>{item.points.toFixed(2)}</dd></div>)}<div className="receipt-total"><dt>Bench points</dt><dd>{d.points?.toFixed(2)}</dd></div></dl></details><a className="source-link" href={d.performance.sourceUrl} target="_blank" rel="noreferrer">{d.performance.date} · Source provenance</a><span className="consumed">REMOVED FROM THIS SEASON’S POOL · NOT IN TEAM TOTAL</span></div>:<p>{d.simulatedBye?'0 points · No historical game consumed':'Score unavailable · Historical game pool exhausted · No game consumed'}</p>}</article>)}</section>;})}</div>}</section>;
}
