'use client';
import {useState} from 'react';
import {ALL_ATHLETES} from '@/lib/game-model';
import type {DraftBoardPick} from '@/lib/draft-board';
const athletes=new Map(ALL_ATHLETES.map(a=>[a.id,a]));
type Team={id:string;name:string};
type Props={teams:Team[];picks:DraftBoardPick[];onDetails?:(id:string)=>void};
export function DraftRecentPicks({teams,picks,onDetails}:Props){
 const names=new Map(teams.map(t=>[t.id,t.name]));
 return <section className="draft-recent-picks" aria-label="Recent draft picks"><div className="draft-recent-heading"><div><span className="sports-kicker">THE PICK FEED</span><h2>Everyone’s picks</h2></div><span className="draft-rail-hint">Latest first · Scroll to browse</span></div><p role="status">{picks.length?`${picks.length} picks saved · Latest: ${names.get(picks.at(-1)!.teamId)} drafted ${athletes.get(picks.at(-1)!.athleteId)?.name||'a player'}`:'No picks yet. Every selection appears here as it is saved.'}</p><ol tabIndex={picks.length?0:undefined} aria-label="Scroll recent selections">{picks.slice(-8).toReversed().map(p=>{const a=athletes.get(p.athleteId);return <li key={p.number}><span className="draft-pick-tag">#{p.number}<small>RD {p.round}</small></span><div><span className="draft-picking-team">{names.get(p.teamId)||'Team'}</span><b>{a?.name||'Player unavailable'}</b><small>{a?.position||'—'} · {a?.club||'Historical archive'}</small></div>{onDetails&&a&&<button className="player-details-button" aria-label={`View pick ${p.number}: ${a.name}`} onClick={()=>onDetails(a.id)}>Details</button>}</li>;})}</ol></section>;
}
export function DraftRoundBoard({teams,picks,order,pick,rounds,active,myTeamId,onDetails}:{order:string[];pick:number;rounds:number;active:boolean;myTeamId:string}&Props){
 const currentRound=Math.min(rounds,Math.floor(pick/Math.max(1,order.length))+1),[chosen,setChosen]=useState<number|null>(null),round=chosen??currentRound;
 const seats=round%2?[...order]:[...order].reverse(),names=new Map(teams.map(t=>[t.id,t.name]));
 const total=rounds*order.length,currentSeats=currentRound%2?order:[...order].reverse(),clockTeam=active?currentSeats[pick%Math.max(1,order.length)]:null,progress=total?Math.min(100,picks.length/total*100):0;
 return <section className="draft-round-board league-panel" aria-label="Complete draft board"><div className="season-panel-heading"><div><span className="sports-kicker">ROUND BY ROUND · ALL TEAMS</span><h2>The draft board</h2></div><label>Draft round<select value={round} onChange={e=>setChosen(Number(e.target.value))}>{Array.from({length:rounds},(_,i)=><option key={i} value={i+1}>Round {i+1}</option>)}</select></label></div><div className="draft-board-summary"><div><span className={`draft-live-status ${active?'is-live':''}`}>{active?'ON THE CLOCK':'SAVED DRAFT'}</span><strong>{active?(names.get(clockTeam||'')||'Waiting for the next team'):picks.length===total?'Every pick is in':'Your draft record'}</strong><span>{active?`Round ${currentRound} · Pick ${pick+1}`:`${rounds} rounds · ${teams.length} teams`}{active&&clockTeam===myTeamId?' · Your turn':''}</span></div><div className="draft-board-progress"><span><b>{picks.length}</b> / {total} picks saved</span><div aria-hidden="true"><span style={{width:`${progress}%`}}/></div></div></div><div className="draft-board-round-meta"><p>Every card names the drafting team, selected player and position. {active?'The highlighted card is on the clock.':''} <b>{round%2?'Forward':'Reverse'} snake order.</b></p>{chosen!==null&&active&&<button className="season-text-button" onClick={()=>setChosen(null)}>Follow current round</button>}</div><ol>{seats.map((teamId,i)=>{const number=(round-1)*order.length+i+1,p=picks.find(p=>p.number===number),a=p?athletes.get(p.athleteId):null,onClock=active&&number===pick+1;return <li key={teamId} className={`${teamId===myTeamId?'your-team':''} ${onClock?'on-clock':''} ${p?'pick-saved':''}`} aria-current={onClock?'step':undefined}><div className="board-pick-heading"><span>#{number} · ROUND {round}</span>{teamId===myTeamId&&<b>YOU</b>}</div><h3>{names.get(teamId)||'Team'}</h3>{p&&a?<><strong>{a.name}</strong><span className="board-player-position"><b>{a.position}</b> · {a.club}</span>{onDetails&&<button className="player-details-button" aria-label={`View draft pick ${number}: ${a.name}`} onClick={()=>onDetails(a.id)}>Player details</button>}</>:<><span className="board-pick-pending">{onClock?'ON THE CLOCK':number<=pick?'Pick record unavailable':'Awaiting selection'}</span>{onClock&&<small className="board-clock-note">{teamId===myTeamId?'Choose a player from the pool below.':'This team makes the next selection.'}</small>}</>}</li>;})}</ol></section>;
}
