'use client';
import {useEffect,useState} from 'react';
import {ChevronUp,ChevronDown,Play,Pause,SkipForward} from 'lucide-react';
import {demoRosterSize,type DemoDraft} from '@/lib/demo-draft-model';
export function DraftOrderSetup({names,order,onChange}:{names:string[];order:number[];onChange:(next:number[])=>void}){
 function move(index:number,delta:number){const next=[...order];[next[index],next[index+delta]]=[next[index+delta],next[index]];onChange(next);}
 return <ol className="custom-draft-order" aria-label="Commissioner-set draft order">{order.map((team,index)=><li key={team}><strong>{String(index+1).padStart(2,'0')}</strong><span>{names[team]||`Team ${team+1}`}{team===0?' · You':''}</span><button type="button" disabled={index===0} aria-label={`Move ${names[team]||`Team ${team+1}`} earlier`} onClick={()=>move(index,-1)}><ChevronUp size={18}/></button><button type="button" disabled={index===order.length-1} aria-label={`Move ${names[team]||`Team ${team+1}`} later`} onClick={()=>move(index,1)}><ChevronDown size={18}/></button></li>)}</ol>;
}
export function DraftLottery({demo,busy,onBegin}:{demo:DemoDraft;busy:boolean;onBegin:()=>void}){
 const [revealed,setRevealed]=useState(0),[running,setRunning]=useState(true),[reduced,setReduced]=useState(false);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{const reduce=media.matches||document.documentElement.dataset.reduceMotion==='true';setReduced(reduce);if(reduce){setRevealed(demo.order.length);setRunning(false);}};update();media.addEventListener('change',update);const observer=new MutationObserver(update);observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-reduce-motion']});return()=>{media.removeEventListener('change',update);observer.disconnect();};},[demo.order.length]);
 useEffect(()=>{if(!running||reduced||revealed>=demo.order.length)return;const timer=setTimeout(()=>setRevealed(n=>Math.min(n+1,demo.order.length)),850);return()=>clearTimeout(timer);},[running,reduced,revealed,demo.order.length]);
 const complete=revealed===demo.order.length,manual=demo.orderMode==='manual',current=demo.teams.find(t=>t.id===demo.order[Math.max(0,revealed-1)]);
 return <section className={`draft-lottery ${reduced?'lottery-reduced':''}`} aria-label="Draft-order reveal"><div className="lottery-heading"><span className="sports-kicker">{manual?'COMMISSIONER-SET ORDER':'THE DRAFT LOTTERY'}</span><h2>{complete?'The order is set.':manual?'Your order. Your draft.':'Who gets the first pick?'}</h2><p>{manual?'Revealing the exact order you chose.':'The server shuffled every team once and saved the result.'} This reveal never reshuffles. Snake order reverses every round.</p><div className="lottery-meta"><span>{demo.teams.length} teams</span><span>Snake draft</span><span>Saved order</span></div></div><div className="lottery-stage" aria-live="polite" aria-atomic="true"><span>{revealed?`DRAFT POSITION ${revealed}`:'READY TO REVEAL'}</span><strong key={revealed}>{revealed?String(revealed).padStart(2,'0'):'?'}</strong><h3>{revealed?current?.name:'Your league is in the draw'}</h3>{revealed>0&&<p>{current?.control==='human'?'Your team':'Computer-managed team'}</p>}</div><ol className="lottery-results" aria-label="Saved first-round order">{demo.order.map((id,index)=>{const team=demo.teams.find(t=>t.id===id)!;return <li key={id} className={`${index<revealed?'revealed':''} ${team.control==='human'?'your-team':''}`}><strong>{String(index+1).padStart(2,'0')}</strong><span>{index<revealed?team.name:'Waiting for reveal'}</span>{index<revealed&&team.control==='human'&&<b>YOU</b>}</li>;})}</ol><div className="lottery-controls">{!complete&&<><button className="secondary-button" onClick={()=>setRunning(r=>!r)}>{running?<Pause size={17}/>:<Play size={17}/>} {running?'Pause reveal':'Resume reveal'}</button><button className="secondary-button" onClick={()=>{setRunning(false);setRevealed(n=>Math.min(n+1,demo.order.length));}}>Reveal next team</button><button className="secondary-button" onClick={()=>{setRevealed(demo.order.length);setRunning(false);}}><SkipForward size={17}/> Show full order</button></>}<button className="primary-button" disabled={!complete||busy} onClick={onBegin}>{busy?'Opening the draft…':'Enter draft room'}</button></div><p className="lottery-note">No players have been drafted yet. Opening the room begins the saved order; computer teams pick automatically until your turn.</p></section>;
}
export function DraftPickQueue({demo}:{demo:DemoDraft}){
 const total=demoRosterSize(demo)*demo.teams.length,remaining=total-demo.pick;
 return <section className="draft-pick-queue" aria-label="Teams waiting to pick"><div className="draft-queue-heading"><div><span className="sports-kicker">DRAFT NIGHT</span><h2>{remaining?'On the clock & up next':'Every pick is in'}</h2><p>{demo.orderMode==='manual'?'Commissioner-set':'Randomized'} order · Snake draft · {demo.pick}/{total} picks saved</p></div>{remaining>0&&<span className="draft-rail-hint">Next {Math.min(8,remaining)} picks · Scroll to browse</span>}</div><ol tabIndex={remaining?0:undefined} aria-label="Scroll upcoming draft teams">{Array.from({length:Math.min(8,remaining)},(_,offset)=>{const pick=demo.pick+offset,count=demo.teams.length,round=Math.floor(pick/count),seat=pick%count,id=demo.order[round%2?count-1-seat:seat],team=demo.teams.find(t=>t.id===id)!;return <li key={pick} className={`${offset===0?'on-clock':''} ${team.control==='human'?'your-team':''}`} aria-current={offset===0?'step':undefined}><span>{offset===0?'ON THE CLOCK':offset===1?'UP NEXT':`PICK ${pick+1}`}</span><strong>{team.name}</strong><small>Round {round+1} · Pick {pick+1}{team.control==='human'?' · YOU':''}</small></li>;})}</ol></section>;
}
