'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {Play,Pause,SkipForward,RotateCcw,Shield,ArrowRight,Home,Radio,CheckCircle2} from 'lucide-react';
import {BenchPoints} from './bench-points';
import {SeasonRecap} from './season-recap';
import {ALL_ATHLETES,historicalTeamLabel,statLine} from '@/lib/game-model';
import {ScoringContractSummary} from './scoring-mode-picker';
import {scoringFor,scoringContractLabel} from '@/lib/scoring-rules';
import type {PublicSeasonRound,Match,PublicSeason} from '@/lib/season-model';
import {fantasyReplay,replayScore,historicalDrawLabel,historicalSeasonLabel,fullReceipt} from '@/lib/fantasy-replay';
import {ReplaySpeed} from './replay-speed';
import {useReplaySpeed} from '@/hooks/use-replay-speed';
import {schedulePlaybackTick} from '@/lib/replay-playback';
const players=new Map(ALL_ATHLETES.map(a=>[a.id,a]));
type ReplayNavigation={label:string;disabled?:boolean;note:string;error?:string;onHome:()=>void;onContinue:()=>void};
function ReplayNavigationActions({navigation,location}:{navigation:ReplayNavigation;location:'top'|'bottom'}){
 return <nav className="replay-navigation" data-location={location} aria-label={location==='top'?'Replay navigation':'Replay navigation at end'}><div className="replay-navigation-copy"><span className="replay-section-kicker">YOUR NEXT MOVE</span><p className="replay-navigation-note">{navigation.note}</p></div><div className="replay-navigation-actions"><button type="button" className="primary-button" disabled={navigation.disabled} onClick={navigation.onContinue}>{navigation.label}<ArrowRight size={18} aria-hidden="true"/></button><Link className="secondary-button" href="/" onClick={navigation.onHome}><Home size={17} aria-hidden="true"/>Return home</Link></div>{navigation.error&&location==='top'&&<p className="replay-navigation-error" role="alert">{navigation.error}</p>}</nav>;
}
export function FantasyReplay({round,match,league,onFinished,navigation}:{round:PublicSeasonRound;match:Match;league:PublicSeason;onFinished:()=>Promise<boolean>;navigation?:ReplayNavigation}){
 const {speed,changeSpeed}=useReplaySpeed();
 const events=useMemo(()=>fantasyReplay(round,match),[round,match]);
 const [step,setStep]=useState(0),[started,setStarted]=useState(false),[running,setRunning]=useState(false),[avatar,setAvatar]=useState<string|null>(null),[reduced,setReduced]=useState(false);
 const notified=useRef(false),[revealError,setRevealError]=useState(false);
 const final=started&&step>=events.length,current=events[step-1],quarter=current?.quarter||1;
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches||document.documentElement.dataset.reduceMotion==='true');update();media.addEventListener('change',update);const observer=new MutationObserver(update);observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-reduce-motion']});const abort=new AbortController();fetch('/api/profile',{cache:'no-store',signal:abort.signal}).then(async r=>{if(r.ok){const b=await r.json() as {profile:{avatar:string|null;reduceMotion:boolean}};setAvatar(b.profile.avatar);setReduced(media.matches||b.profile.reduceMotion);}}).catch(()=>{});return()=>{abort.abort();observer.disconnect();media.removeEventListener('change',update);};},[]);
 useEffect(()=>{if(!running||final)return;return schedulePlaybackTick(()=>setStep(s=>Math.min(s+1,events.length)),2400,speed);},[running,step,events.length,final,speed]);
 const receiptsVisible=final&&!round.receiptsHidden;
 useEffect(()=>{if(!final||!round.receiptsHidden||notified.current)return;notified.current=true;void onFinished().then(ok=>{if(!ok)setRevealError(true);}).catch(()=>setRevealError(true));},[final,round.receiptsHidden,onFinished]);
 async function retryReveal(){setRevealError(false);try{if(!await onFinished())setRevealError(true);}catch{setRevealError(true);}}

 const name=(id:string)=>league.teams.find(t=>t.id===id)?.name||'Team';
 return <section className={`fantasy-replay broadcast-fantasy-replay ${reduced?'replay-reduced':''} ${final?'replay-final':''} ${started?'replay-started':'replay-preview'}`} aria-label={`Week ${round.number} fantasy replay`}>
  <div className="replay-top"><span><Radio size={16} aria-hidden="true"/>FANTASY REPLAY · LEAGUE WEEK {round.number}</span><b><i aria-hidden="true"/>{!started?'MATCHUP PREVIEW':final?'FINAL':`FICTIONAL QUARTER ${quarter} / 4`}</b></div>
  <div className="replay-scoreboard">{[match.home,match.away].map((id,i)=>{const score=(final?(i===0?match.homeScore:match.awayScore):replayScore(events,step,id)).toFixed(2);return <div className={`replay-team ${id===league.myTeamId?'replay-your-team':''} ${final&&match.winner===id?'replay-winning-team':''}`} key={id}>{id===league.myTeamId&&avatar?<img src={avatar} alt="Your profile"/>:<span className="replay-avatar" aria-hidden="true"><Shield size={26}/>{name(id).split(' ').map(w=>w[0]).slice(0,2).join('')}</span>}<span>{id===league.myTeamId?'YOUR TEAM': 'OPPONENT'}</span><h3>{name(id)}</h3>{started?<strong key={reduced?'score':score}>{score}</strong>:<p className="replay-score-pending">Score hidden until replay</p>}</div>;})}<div className="replay-vs"><span>{!started?'MATCHUP':final?'FINAL':`Q${quarter}`}</span><b>{!started?'VS':final?'FT':'VS'}</b><small>WEEK {round.number} · {scoringContractLabel(scoringFor(round))}</small></div></div>
  {final&&navigation&&<ReplayNavigationActions navigation={navigation} location="top"/>}
  <p className="replay-disclaimer">Simulated presentation of your saved historical draws. Quarters and highlights are fictional, not actual NFL play chronology.</p>
  {started&&<><div className="replay-quarter-heading"><span className="replay-section-kicker">QUARTER SPLITS</span><small>{name(match.home)} / {name(match.away)}</small></div><div className="replay-quarters" aria-label="Four fictional quarters">{[1,2,3,4].map(q=><div key={q} className={`${q===quarter?'active':''} ${final||q<quarter?'complete':''}`}><b>Q{q}</b>{[match.home,match.away].map(id=><span key={id}>{(events.slice(0,step).filter(e=>e.quarter===q&&e.teamId===id).reduce((s,e)=>s+e.delta,0)/100).toFixed(2)}</span>)}</div>)}</div><div className="replay-highlight" aria-live="polite" aria-atomic="true" key={reduced?'still':step}>{final?<><span><CheckCircle2 size={16} aria-hidden="true"/>FINAL WHISTLE</span><h3>{match.winner?`${name(match.winner)} wins`:'Tie game'}</h3><p>{match.tiebreak||'Your original result is saved. No new games were drawn.'}</p></>:current?<><span>Q{quarter} · {name(current.teamId)}</span><h3>{current.athleteId?players.get(current.athleteId)?.name:current.label} <b>{current.delta>0?'+':''}{(current.delta/100).toFixed(2)}</b></h3>{current.athleteId&&<p className="replay-historical-game">{historicalSeasonLabel(round.draws[current.teamId]?.find(d=>d.athleteId===current.athleteId)?.performance)}</p>}<p>{current.label} · fictional scoring highlight</p></>:<><span>KICKOFF</span><h3>The scoreboard is ready</h3><p>Watch your saved draws unfold over four fictional quarters.</p></>}</div></>}
  {!started&&<div className="replay-preview-note"><span className="replay-section-kicker">THE MATCHUP IS SET</span><h3>Your saved game. Ready for kickoff.</h3><p>Watch the scoring unfold, or skip straight to the final result and historical game receipts.</p></div>}
  <div className="replay-control-console"><div className="replay-control-heading"><span className="replay-section-kicker">BROADCAST CONTROLS</span><span>{!started?'Ready when you are':final?'Replay complete':running?'Playing highlights':'Playback paused'}</span></div>{started&&<div className="replay-progress"><progress aria-label="Scoring highlights played" value={step} max={Math.max(1,events.length)}/><span>{step} / {events.length} highlights</span></div>}<div className="replay-controls"><ReplaySpeed speed={speed} onChange={changeSpeed} baseMs={2400}/>{!started?<button className="primary-button" onClick={()=>{setStarted(true);setRunning(true);}}> <Play size={18} aria-hidden="true"/> Watch four quarters</button>:final?<button className="primary-button" onClick={()=>{setStep(0);setRunning(true);}}> <RotateCcw size={18} aria-hidden="true"/> Replay game</button>:<button className="primary-button" onClick={()=>setRunning(r=>!r)}>{running?<Pause size={18} aria-hidden="true"/>:<Play size={18} aria-hidden="true"/>} {running?'Pause':'Resume'}</button>}{!final&&<button className="secondary-button" onClick={()=>{setStarted(true);setRunning(false);setStep(events.length);}}><SkipForward size={18} aria-hidden="true"/> Skip to final</button>}{started&&!final&&<button className="secondary-button" onClick={()=>{setRunning(false);setStep(s=>Math.min(s+1,events.length));}}>Next highlight</button>}</div></div>
  <ScoringContractSummary rules={scoringFor(round)} lockNotice="Saved with this week"/>
  {final&&round.receiptsHidden&&<p className="replay-receipt-status" role="status">{revealError?'Your result is safe. Receipt reveal has not saved yet.':'Saving completion and unlocking historical weeks…'}{revealError&&<button className="secondary-button" onClick={()=>void retryReveal()}>Retry receipt reveal</button>}</p>}
  {!final&&<p className="replay-receipt-status">Season revealed. Exact NFL weeks and game records unlock at the final whistle or Skip to final.</p>}
  {receiptsVisible&&<><h3 className="replay-receipts-heading">Which version did you get?</h3><SeasonRecap league={league} round={round}/></>}<div className="replay-lineups">{[match.home,match.away].map(id=><section key={id}><header className="replay-lineup-heading"><span className="replay-section-kicker">COUNTS TOWARD TEAM TOTAL</span><h4>{name(id)} · Starting lineup</h4></header>{(round.draws[id]||[]).map(d=><div className="replay-starter-card" key={`${d.slot}:${d.athleteId}`}><span className="replay-slot-label">{d.slot||players.get(d.athleteId)?.position}</span><div className="replay-player-receipt"><b>{players.get(d.athleteId)?.name||d.athleteId}</b><span className="replay-historical-game">{d.simulatedBye?'Simulated BYE · No game consumed':receiptsVisible?historicalDrawLabel(d.performance):historicalSeasonLabel(d.performance)}</span>{receiptsVisible&&fullReceipt(d.performance)&&d.performance.opponent&&<small>{historicalTeamLabel(d.performance,d.performance.teamAtTime)} vs {historicalTeamLabel(d.performance,d.performance.opponent)}{d.performance.date?` · ${d.performance.date}`:''}</small>}{receiptsVisible&&fullReceipt(d.performance)&&<small>{statLine(d.performance)}</small>}{receiptsVisible&&d.performance?.sourceUrl&&<a href={d.performance.sourceUrl} target="_blank" rel="noreferrer">Saved game source</a>}</div><strong>{started?replayScore(events.slice(0,step).filter(e=>e.athleteId===d.athleteId),step,id).toFixed(2):'—'}</strong></div>)}</section>)}</div>
  {receiptsVisible&&<BenchPoints league={league} round={round} teamIds={[match.home,match.away]}/>}
  {started&&step>0&&<details className="replay-log"><summary>Scoring highlights ({step})</summary><ol>{events.slice(0,step).map((e,i)=><li key={i}>Q{e.quarter} · {name(e.teamId)} · {e.athleteId?players.get(e.athleteId)?.name:e.label}: {e.delta>0?'+':''}{(e.delta/100).toFixed(2)}{e.athleteId&&<span className="replay-log-history">{receiptsVisible?e.historicalGame:historicalSeasonLabel(round.draws[e.teamId]?.find(d=>d.athleteId===e.athleteId)?.performance)}</span>}</li>)}</ol></details>}
  {final&&navigation&&<ReplayNavigationActions navigation={navigation} location="bottom"/>}
 </section>;
}
