'use client';
import {useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {BookOpen,LockKeyhole} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from './ui/table';
import {REVIEW_PERFORMANCES,REVIEW_PLAYERS,REVIEW_SELECTION_NOTE,reviewScore,reviewReceipt,type ReviewRecord} from '@/lib/historical-game-review';
import type {ReceptionPoints} from '@/lib/scoring-rules';

const sourceFields=[['passingYards','Passing yards'],['passingTD','Passing touchdowns'],['interceptions','Interceptions thrown'],['rushingYards','Rushing yards'],['rushingTD','Rushing touchdowns'],['receptions','Receptions'],['receivingYards','Receiving yards'],['receivingTD','Receiving touchdowns'],['returnTD','Return touchdowns']] as const;
function gameLabel(record:ReviewRecord){
 const week=Number.isInteger(record.week)&&record.week!>0?`NFL Week ${record.week}`:'NFL week unavailable';
 return `${record.season} season · ${record.seasonType==='POST'?`${record.roundLabel||'Playoffs'} · `:''}${week}`;
}
function pointsLabel(ppr:ReceptionPoints){return ppr===0?'Standard':ppr===.5?'Half PPR':'Full PPR';}

export function HistoricalGameReview(){
 const [playerId,setPlayerId]=useState('ALL'),[ppr,setPpr]=useState<ReceptionPoints>(1),[selected,setSelected]=useState<ReviewRecord|null>(null);
 const returnFocus=useRef('');
 const playersById=useMemo(()=>new Map(REVIEW_PLAYERS.map(player=>[player.id,player])),[]);
 const records=useMemo(()=>REVIEW_PERFORMANCES.filter(record=>playerId==='ALL'||record.athleteId===playerId),[playerId]);
 const selectedPlayer=selected?playersById.get(selected.athleteId):undefined;
 return <div className="historical-preview historical-game-review">
  <Link className="profile-source" href="/historical-preview">← Historical player preview</Link>
  <header className="preview-heading"><div><span className="sports-kicker">SELECTED HISTORICAL GAME REVIEW</span><h1>Quarterback shutouts</h1><p>Inspect source facts, scoring inputs and evidence for a limited sample.</p></div><span className="preview-lock"><LockKeyhole size={18}/> Read-only review</span></header>
  <aside className="preview-caution" aria-label="Selected shutout sample limits"><BookOpen size={23} aria-hidden="true"/><div><h2>Selected shutouts only</h2><p><b>{REVIEW_SELECTION_NOTE}</b></p><p>These games produce a biased low-scoring sample. They are not a representative career sample. This page does not add players or performances to normal gameplay.</p></div></aside>
  <section className="preview-coverage" aria-label="Review sample coverage"><div><strong>{REVIEW_PERFORMANCES.length}</strong><span>selected games for review</span></div><div><strong>{REVIEW_PLAYERS.length}</strong><span>reviewed QB identities</span></div><div><strong>0</strong><span>draftable games from this review</span></div></section>
  <section className="preview-filters" aria-label="Game review controls"><label>Quarterback<select aria-label="Review quarterback" value={playerId} onChange={event=>setPlayerId(event.target.value)}><option value="ALL">All quarterbacks · {REVIEW_PERFORMANCES.length} selected games</option>{REVIEW_PLAYERS.map(player=><option key={player.id} value={player.id}>{player.name} · {player.gameCount} selected {player.gameCount===1?'game':'games'}</option>)}</select></label><label>Scoring illustration<select aria-label="Review PPR scoring" value={ppr} onChange={event=>setPpr(Number(event.target.value) as ReceptionPoints)}><option value={0}>Standard · 0 per reception</option><option value={.5}>Half PPR · 0.5 per reception</option><option value={1}>Full PPR · 1 per reception</option></select></label><p className="player-browser-note">Current v4 scoring only. Individual lost-fumble scoring is disabled; unavailable lost-fumble stats remain unknown.</p></section>
  <section className="preview-results" aria-label="Selected historical games"><div className="preview-results-heading"><h2>{playerId==='ALL'?'All selected games':playersById.get(playerId)?.name}</h2><p role="status" aria-live="polite">{records.length} selected games · {pointsLabel(ppr)} illustration · Review only</p></div>
   <div className="ff-panel"><Table className="ff-player-table"><TableHeader><TableRow><TableHead>Quarterback / game</TableHead><TableHead>Historical NFL game</TableHead><TableHead className="ff-number">Illustrated points</TableHead><TableHead><span className="sr-only">Review action</span></TableHead></TableRow></TableHeader><TableBody>{records.map(record=><TableRow key={record.id}><TableCell><b>{playersById.get(record.athleteId)?.name||record.athleteId}</b><p>{record.teamAtTime} vs {record.opponent} · {record.date}</p></TableCell><TableCell>{gameLabel(record)}</TableCell><TableCell className="ff-number" data-review-points={record.id}>{reviewScore(record,ppr).toFixed(2)}</TableCell><TableCell><button type="button" className="secondary-button" id={`review-game-${record.id}`} aria-label={`Review ${playersById.get(record.athleteId)?.name||record.athleteId} game on ${record.date}`} onClick={()=>{returnFocus.current=record.id;setSelected(record);}}>Review game</button></TableCell></TableRow>)}</TableBody></Table></div>
  </section>
  <details className="preview-source-notes"><summary>What this sample verifies</summary><p>The nine displayed source scoring fields were checked against the original dataset snapshot. The selected completed team shutouts provide separate evidence for zero two-point credits and zero offensive fumble-recovery touchdowns. Neither category was supplied in the original dataset. Lost fumbles remain unavailable.</p><p>Provider-sourced fields and selected independent corroboration do not establish complete careers or a balanced game pool. Changing PPR here changes only this scoring illustration. No draft, draw or saved season is changed.</p></details>
  <Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent className="preview-profile-dialog" onCloseAutoFocus={event=>{event.preventDefault();document.getElementById(`review-game-${returnFocus.current}`)?.focus();}}><DialogTitle>{selectedPlayer?.name||'Selected game'}</DialogTitle><DialogDescription>{selected?`${selected.date} · ${gameLabel(selected)}`:'Historical game review'}</DialogDescription>{selected&&<>
   <span className="preview-lock"><LockKeyhole size={17}/> Review only · excluded from drafts, random draws and seasons</span>
   <p>{selected.teamAtTime} vs {selected.opponent}. {selected.sourceWeek!==undefined&&<>Source game ordinal: {selected.sourceWeek}; this is distinct from the NFL week.</>}</p>
   <div className="season-table-scroll"><table className="season-table"><caption>Reviewed provider values and separate derived inputs</caption><thead><tr><th scope="col">Stat</th><th scope="col">Provider value</th><th scope="col">Scoring input</th></tr></thead><tbody>{sourceFields.map(([key,label])=><tr key={key}><th scope="row">{label}</th><td>{selected.stats[key]}</td><td>{selected.stats[key]}</td></tr>)}<tr><th scope="row">Two-point credits</th><td>Unavailable</td><td>0 · derived from completed team shutout</td></tr><tr><th scope="row">Offensive recovery touchdowns</th><td>Unavailable</td><td>0 · derived from completed team shutout</td></tr><tr><th scope="row">Individual lost fumbles</th><td>Unavailable</td><td>Disabled · remains unknown</td></tr></tbody></table></div>
   <section className="profile-coverage"><h3>Completed team shutout proof</h3><p><b>Final: {selected.provenance.derivations.twoPoint.team} 0 – {selected.provenance.derivations.twoPoint.finalScore[1]} {selected.provenance.derivations.twoPoint.opponent}</b> · {selected.provenance.derivations.twoPoint.date}</p><p>A verified final team score of zero supports zero credited two-point conversions and offensive recovery touchdowns for this game. This proof supplies no yardage, reception or lost-fumble values. The original missing categories remain unknown in the source record.</p>{selected.sourceUrls.filter(url=>url!==selected.sourceUrl).map(url=><p key={url}><a href={url} target="_blank" rel="noreferrer">View game evidence ↗</a></p>)}</section>
   <div className="ff-score-detail"><h3>{pointsLabel(ppr)} illustration · current v4 rules</h3><dl>{reviewReceipt(selected,ppr).map(item=><div key={item.label}><dt>{item.label}<small>{item.calculation}</small></dt><dd>{item.points.toFixed(2)}</dd></div>)}<div className="ff-score-total"><dt>Total illustrated points</dt><dd>{reviewScore(selected,ppr).toFixed(2)}</dd></div></dl><p>Individual lost-fumble scoring is disabled. These points are a review illustration, not a saved gameplay result.</p></div>
   {selectedPlayer&&<p><a href={selectedPlayer.hallOfFameSource} target="_blank" rel="noreferrer">Reviewed player identity · Pro Football Hall of Fame ↗</a></p>}<p><a href={selected.sourceUrl} target="_blank" rel="noreferrer">View original dataset ↗</a></p>
  </>}</DialogContent></Dialog>
 </div>;
}
