'use client';
import {JourneyFetchError} from '@/lib/journey-fetch';
import {useAccountSession} from '@/components/account-session';
import {useScopedJourneyFetch} from '@/hooks/use-workspace-location';

import {GameHeader} from './game-header';
import {JourneyStatus,useOffline,sessionExpired} from './journey-status';
import {navigateWorkspace,useLocationQuery} from '@/hooks/use-workspace-location';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Users} from 'lucide-react';
import {SeasonWorkspace} from '@/components/season-workspace';
import {newScoring,kickerScoringNote} from '@/lib/scoring-rules';
import {ScoringPicker} from '@/components/draft-assistant';
import {ScoringContractSummary} from '@/components/scoring-mode-picker';
import {TEAM_COUNTS,modernRegularWeeks} from '@/lib/season-model';
import type {PublicSeason,SeasonSummary} from '@/lib/season-model';

export function OnlineLeague(){const {accountKey}=useAccountSession();return <OnlineLeagueWorkspace key={accountKey??'local-preview'}/>;}
function OnlineLeagueWorkspace(){
 const {fetch:journeyFetch,isActive}=useScopedJourneyFetch();
 const account=useAccountSession(),sessionBlocked=!!account.provided&&account.status!=='authenticated',sharedSignin=!!account.provided&&account.status==='signed-out',sharedStale=!!account.provided&&account.status==='unavailable',sharedLoading=!!account.provided&&account.status==='loading';
 const [leagues,setLeagues]=useState<SeasonSummary[]>([]),[league,setLeague]=useState<PublicSeason|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[signin,setSignin]=useState(false);
 const working=useRef(false),mustCheck=useRef(false),selected=useRef<string|null>(null);
 const [stale,setStale]=useState(false),[pendingCheck,setPendingCheck]=useState(false),[opening,setOpening]=useState(false);
 const offline=useOffline(setStale),selectedQuery=useLocationQuery('league');
 useEffect(()=>{selected.current=selectedQuery;},[selectedQuery]);
 const readOnly=sessionBlocked||busy||stale||pendingCheck||offline||signin||opening;
 const [invitation,setInvitation]=useState<{name:string;status:string;canJoin:boolean;vacancies:{id:string;name:string;locked:boolean}[]}|null>(null),[replacement,setReplacement]=useState('');
 const scoringMode='historical' as const;
 const [receptionPoints,setReceptionPoints]=useState(1),[playoffTeams,setPlayoffTeams]=useState<4|6>(6);
 const [name,setName]=useState(''),[teamName,setTeamName]=useState(''),[joinTeam,setJoinTeam]=useState(''),[code,setCode]=useState(''),[capacity,setCapacity]=useState('8');
 function unauthorized(status:number){if(status===401){setSignin(true);sessionExpired();setLeague(null);setLeagues([]);} }
 function revoke(id:string){setLeague(current=>current?.id===id?null:current);setLeagues(items=>items.filter(l=>l.id!==id));setStale(false);mustCheck.current=false;setPendingCheck(false);setError('Your access to this league is no longer available.');if(selected.current===id)navigateWorkspace({league:null,view:null,replay:null,scope:null},true);}
 function update(saved:PublicSeason){if(selected.current!==saved.id)return;setLeague(current=>current?.id===saved.id&&current.revision>saved.revision?current:saved);}
 const list=useCallback(async()=>{try{const r=await journeyFetch('/api/leagues',{cache:'no-store'});if(!isActive())return;if(r.status===401){setSignin(true);sessionExpired();setLeague(null);setLeagues([]);throw new Error('Sign in again to open your leagues.');}const data=await r.json() as {leagues:SeasonSummary[];error?:string;signin?:boolean};if(!isActive())return;if(!r.ok){if(r.status===401){setSignin(true);sessionExpired();setLeague(null);setLeagues([]);}throw new Error(data.error||'Could not load leagues.');}setLeagues(data.leagues);setSignin(false);if(!selected.current){setStale(false);mustCheck.current=false;setPendingCheck(false);setError('');}}catch(e){if(!isActive())return;setStale(true);setError(e instanceof Error?e.message:'Could not load leagues.');}finally{if(isActive())setLoading(false);}},[journeyFetch,isActive]);
 const readSelected=useCallback(async(id:string,signal?:AbortSignal,background=false)=>{
  try{const r=await journeyFetch(`/api/leagues/${encodeURIComponent(id)}`,{cache:'no-store',signal});if(!isActive()||signal?.aborted||selected.current!==id)return;if(r.status===401){setSignin(true);sessionExpired();setLeague(null);setLeagues([]);throw new Error('Sign in again to open your leagues.');}if(r.status===403||r.status===404){revoke(id);return;}const body=await r.json() as {league:PublicSeason;error?:string;signin?:boolean};if(!isActive()||signal?.aborted||selected.current!==id)return;
   if(!r.ok){if(r.status===401){setSignin(true);sessionExpired();setLeague(null);setLeagues([]);}else if(r.status===403||r.status===404){revoke(id);return;}else setStale(true);throw new Error(body.error||'Could not open league.');}
   update(body.league);setSignin(false);setStale(false);if(!background){mustCheck.current=false;setPendingCheck(false);}setError('');
  }catch(e){if(isActive()&&!signal?.aborted&&selected.current===id){if(e instanceof JourneyFetchError&&(e.status===403||e.status===404)){revoke(id);return;}setStale(true);setError(e instanceof Error?e.message:'Live updates are interrupted. Your last loaded league is still here.');}}
  finally{if(isActive()&&!signal?.aborted&&selected.current===id)setOpening(false);}
 },[journeyFetch,isActive]);
 useEffect(()=>{void Promise.resolve().then(list);},[list]);
 useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(()=>{if(controller.signal.aborted)return;if(!selectedQuery){setLeague(null);setOpening(false);return;}setLeague(current=>current?.id===selectedQuery?current:null);setOpening(true);return readSelected(selectedQuery,controller.signal);});return()=>controller.abort();},[selectedQuery,readSelected]);
 function open(id:string){setError('');navigateWorkspace({league:id,view:null,replay:null,scope:null});}
 useEffect(()=>{
  if(!selectedQuery)return;const controller=new AbortController();
  const refresh=()=>{if(working.current||mustCheck.current||document.visibilityState==='hidden')return;void readSelected(selectedQuery,controller.signal,true);};
  const timer=setInterval(refresh,8000);window.addEventListener('focus',refresh);window.addEventListener('online',refresh);
  return()=>{controller.abort();clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('online',refresh);};
 },[selectedQuery,readSelected]);
 function interrupted(){mustCheck.current=true;setPendingCheck(true);setStale(true);}
 async function act(action:string,extra:Record<string,unknown>={}){
  if(!league||working.current||readOnly)return false;working.current=true;setBusy(true);setError('');let status:number|undefined;
  try{const r=await journeyFetch(`/api/leagues/${encodeURIComponent(league.id)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,revision:league.revision,...extra})});if(!isActive())return false;status=r.status;unauthorized(r.status);if(r.status===401)throw new Error('Sign in again to continue your saved league.');if(r.status===403||r.status===404){revoke(league.id);return false;}const body=await r.json() as {league?:PublicSeason;error?:string};if(!isActive())return false;if(r.status!==401&&selected.current!==league.id)return false;if(body.league&&r.status!==401)update(body.league);if(!r.ok){if(r.status===403||r.status===404){setLeague(null);setLeagues(items=>items.filter(l=>l.id!==league.id));navigateWorkspace({league:null,view:null,replay:null,scope:null},true);}if(r.status>=500)interrupted();throw new Error(body.error||'The action could not be saved.');}return true;
  }catch(e){if(!isActive())return false;if(e instanceof JourneyFetchError||status===undefined||e instanceof SyntaxError)interrupted();setError(e instanceof Error?e.message:'The save response was interrupted.');return false;}finally{working.current=false;setBusy(false);}
 }
 async function submit(e:FormEvent,action:'create'|'join'){e.preventDefault();if(working.current||readOnly)return;working.current=true;setBusy(true);setError('');let status:number|undefined;try{const r=await journeyFetch('/api/leagues',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='create'?{action,name,teamName,capacity:Number(capacity),format:'seventeen',playoffTeams,receptionPoints,scoringMode,kickers:true}:{action,code,teamName:joinTeam,teamId:replacement})});if(!isActive())return;status=r.status;unauthorized(r.status);if(r.status===401)throw new Error('Sign in again to create or join a league.');const body=await r.json() as {league:PublicSeason;error?:string;signin?:boolean};if(!isActive())return;if(!r.ok){if(r.status>=500)interrupted();throw new Error(body.error||'The league could not be saved.');}navigateWorkspace({league:body.league.id,view:null,replay:null,scope:null});setLeague(body.league);void list();}catch(e){if(!isActive())return;if(e instanceof JourneyFetchError||status===undefined||e instanceof SyntaxError)interrupted();setError(e instanceof Error?e.message:'The save response was interrupted.');}finally{working.current=false;setBusy(false);}}
 async function inspectInvitation(){if(working.current||readOnly)return;working.current=true;setBusy(true);setError('');try{const r=await journeyFetch('/api/leagues',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'inspectInvite',code})});if(!isActive())return;unauthorized(r.status);if(r.status===401)throw new Error('Sign in again to check this invitation.');const body=await r.json() as {error?:string;invitation:NonNullable<typeof invitation>};if(!isActive())return;if(!r.ok)throw new Error(body.error||'Could not check the invitation.');setInvitation(body.invitation);setReplacement('');}catch(e){if(!isActive())return;setError(e instanceof Error?e.message:'Could not check the invitation.');}finally{working.current=false;setBusy(false);}}
 function refreshSaved(){void account.refresh();if(selectedQuery)void readSelected(selectedQuery);void list();}
 const savedLeagueList=<section className="league-panel league-list"><h2>My leagues</h2>{loading?<p role="status">Loading your leagues…</p>:leagues.length?leagues.map(s=><button key={s.id} onClick={()=>void open(s.id)} disabled={busy}><div><b>{s.name}</b><span>{s.teamName} · {s.members}/{s.capacity} managers</span></div><span>{s.status==='lobby'?'Lobby':s.status==='draft'?'Draft':s.status==='complete'?'Season complete':`Round ${s.round}`}</span></button>):<p>Create a league or join with an invitation code to start your season.</p>}</section>;

 return <div className="site-shell fantasy-app online-app broadcast-online-app"><GameHeader active="online"/>
 <main id="main-content" tabIndex={-1} className="league-main"><div className="league-page-heading broadcast-clubhouse-heading"><div><span className="eyebrow"><Users size={16}/> THE SEASON CLUBHOUSE</span><h1>{league?league.name:'Online leagues'}</h1><p>{league?`${league.teams.filter(t=>!t.vacant).length} of ${league.capacity} managers · ${league.regularRounds} regular weeks + playoffs`:'Draft older and modern players together. Keep your players and build a league with your friends.'}</p></div><div className="clubhouse-season-pass"><span>THE SEASON CLUB</span><strong>{league?String(league.round).padStart(2,'0'):'17'}</strong><span>{league?'FANTASY WEEK':'WEEKS · DRAFT ONCE'}</span></div></div>
 <JourneyStatus busy={busy} loading={loading||opening||sharedLoading} error={error} signin={signin||sharedSignin} stale={stale||sharedStale} pendingCheck={pendingCheck} onRefresh={refreshSaved}/>
 {opening&&!league?<section className="league-panel"><p role="status">Opening the selected league…</p></section>:league?<SeasonWorkspace key={league.id} league={league} busy={readOnly} onAction={act} onBack={()=>{setError('');navigateWorkspace({league:null,view:null,replay:null,scope:null});void list();}}/>:<>
 {leagues.length>0&&savedLeagueList}<section className="league-panel demo-entry"><div><span className="sports-kicker">THE SOLO PROGRAM</span><h2>Play a season now</h2><p>Draft an eleven-player team against computer managers, then keep it through a 17-week season.</p></div><a className="primary-button" href="/demo">Open my season</a></section><div className="league-entry-grid"><section className="league-panel league-create-panel"><div className="league-desk-heading"><span className="league-desk-number">01</span><div><span className="sports-kicker">COMMISSIONER DESK</span><h2>Create a league</h2><p>Your league. Your friends. One saved season.</p></div></div><form onSubmit={e=>void submit(e,'create')}><label>League name<input required maxLength={50} value={name} onChange={e=>setName(e.target.value)} placeholder="Sunday Time Travelers"/></label><label>Your team name<input required maxLength={50} value={teamName} onChange={e=>setTeamName(e.target.value)} placeholder="The Throwbacks"/></label><div className="league-form-row"><label>Managers<select value={capacity} onChange={e=>{setCapacity(e.target.value);if(Number(e.target.value)<6)setPlayoffTeams(4);}}>{TEAM_COUNTS.map(n=><option key={n}>{n}</option>)}</select></label><label>Playoff teams<select value={playoffTeams} disabled={Number(capacity)===2} onChange={e=>setPlayoffTeams(Number(e.target.value) as 4|6)}><option value={4}>{capacity==='2'?'2 finalists':'4 qualifiers'}</option>{Number(capacity)>=6&&<option value={6}>6 qualifiers</option>}</select></label></div><p>{modernRegularWeeks(Number(capacity),playoffTeams)} regular weeks + {17-modernRegularWeeks(Number(capacity),playoffTeams)} playoff weeks. Championship in Week 17. {playoffTeams===6&&'Top two seeds have first-round byes.'}</p><ScoringContractSummary rules={newScoring(receptionPoints,true,scoringMode)} lockNotice="Reception scoring can be edited in the lobby; it locks at draft start"/><ScoringPicker rules={newScoring(receptionPoints,true,scoringMode)} disabled={readOnly} value={receptionPoints} onChange={setReceptionPoints}/><p>11-player rosters · 7 starters including K + 4 bench. Weeks 1–4 are bye-free; fictional player and defense byes start in Fantasy Week 5 and never fall in the playoffs. Scoring locks when the draft starts. {kickerScoringNote(newScoring(receptionPoints,true,scoringMode))}</p><button className="primary-button" disabled={readOnly}>{busy?'Saving…':'Create league'}</button></form></section>
 <section className="league-panel league-join-panel"><div className="league-desk-heading"><span className="league-desk-number">02</span><div><span className="sports-kicker">INVITATION DESK</span><h2>Join your friends</h2><p>Bring your team into their league.</p></div></div><form onSubmit={e=>void submit(e,'join')}><label>Invitation code<input required maxLength={40} value={code} onChange={e=>{setCode(e.target.value.toUpperCase());setInvitation(null);setReplacement('');}} placeholder="XXXX-XXXX-XXXX-XXXX" autoComplete="off"/></label><button type="button" className="secondary-button" disabled={readOnly||!code} onClick={()=>void inspectInvitation()}>Check invitation</button>{invitation&&<p><b>{invitation.name}</b> · {invitation.status==='lobby'?'League lobby':'Existing teams only'}</p>}{invitation&&invitation.status!=='lobby'?<><label>Team to take over<select required value={replacement} onChange={e=>setReplacement(e.target.value)}><option value="">Choose a vacant team</option>{invitation.vacancies.map(t=><option key={t.id} value={t.id}>{t.name}{t.locked?' · Locked this week':''}</option>)}</select></label><p>You inherit this team’s roster, record, remaining games, schedule and any locked lineup. Team names remain unchanged.</p></>:<label>Your team name<input required maxLength={50} value={joinTeam} onChange={e=>setJoinTeam(e.target.value)} placeholder="Name your team"/></label>}<p>Each manager signs in to their own account and controls one team.</p><button className="primary-button" disabled={readOnly||(!!invitation&&invitation.status!=='lobby'&&!replacement)}>{invitation&&invitation.status!=='lobby'?'Take over selected team':'Join league'}</button></form></section></div>
 {!leagues.length&&savedLeagueList}
 </>}
 <footer className="page-footer"><span>FANTASY FOOTBALL OF THE PAST</span><span>Independent fan project · Free for fun</span></footer></main></div>;
}
