'use client';
import {useId} from 'react';
import type {ScoringRules} from '@/lib/scoring-rules';
import {PLAYER_ERAS,PLAYER_BROWSE_NOTE,historicalPreviewHref,type PlayerBrowsePosition} from '@/lib/player-filters';

const labels:Record<PlayerBrowsePosition,string>={ALL:'All positions',QB:'QB · Quarterbacks',RB:'RB · Running backs',WR:'WR · Wide receivers',TE:'TE · Tight ends',DEF:'D/ST · Team defenses',FLEX:'FLEX · RB, WR or TE',K:'K · Kickers'};
export function PlayerBrowserFilters<P extends PlayerBrowsePosition>({position,positions,era,onPositionChange,onEraChange,onClear,allowAll=false}:{position:P;positions:readonly P[];era:number;onPositionChange:(position:P)=>void;onEraChange:(era:number)=>void;onClear:()=>void;allowAll?:boolean}){
 const noteId=useId();
 return <><div className={`player-browser-filters ${era>0?'player-filters-era-active':''}`}><label>Position<select aria-label="Player position" value={position} onChange={e=>onPositionChange(e.target.value as P)}>{allowAll&&<option value="ALL">All positions</option>}{positions.map(p=><option key={p} value={p}>{labels[p]}</option>)}</select></label><label>Era<select aria-label="Player era" aria-describedby={noteId} value={era} onChange={e=>onEraChange(Number(e.target.value))}><option value={0}>All eras</option>{PLAYER_ERAS.map(year=><option key={year} value={year}>{year}s{year===2020?' · through 2026':''}</option>)}</select></label><button type="button" className="secondary-button" onClick={onClear}>Clear player filters</button></div><p id={noteId} className="player-browser-note">{PLAYER_BROWSE_NOTE}</p></>;
}

export function PlayerBrowserEmpty({position,era,search='',onClear,scoring}:{position:PlayerBrowsePosition;era:number;search?:string;onClear:()=>void;scoring?:ScoringRules}){
 const early=era>0&&era<1990,historical=scoring?.mode==='historical',missingFifties=historical&&era===1950;
 return <div className="player-browser-empty" role="status"><h3>{missingFifties?'1950s game logs need more verified stats':historical?`No available ${position==='ALL'?'':`${position} `}players match these filters`:early?`No playable ${position==='ALL'?'':`${position} `}games from the ${era}s yet`:'No available players match these filters'}</h3><p>{missingFifties?'The 1950s logs do not record return touchdowns, which these rules score. Unknown stats cannot count as zero. These games will become playable when that gap is verified.':historical?'No unused verified games meet this saved scoring contract and current roster requirements. Try another era, position or search.':early?'This saved archive starts in 1999. Earlier career years and source profiles do not supply verified games.':'Try another era, position or search. Owned players and existing availability requirements still apply.'}</p>{!historical&&(early||era===1990)&&<p><a href={historicalPreviewHref(position,era,search)}>Browse historical {position==='DEF'||position==='FLEX'||position==='ALL'?'player':position} names · Preview only</a><br/>These source profiles can be viewed but cannot be drafted from the preview.</p>}<button type="button" className="secondary-button" onClick={onClear}>Clear player filters</button></div>;
}
