import {ALL_ATHLETES} from '@/lib/game-model';
import {seasonRecap} from '@/lib/season-recap';
import {Trophy,TrendingUp,Star} from 'lucide-react';
import type {PublicSeason,PublicSeasonRound} from '@/lib/season-model';
export function SeasonRecap({league,round}:{league:PublicSeason;round:PublicSeasonRound}){
 const recap=seasonRecap(league,round);if(!recap)return null;
 const player=(id:string)=>ALL_ATHLETES.find(a=>a.id===id)?.name||id,team=(id:string)=>league.teams.find(t=>t.id===id)?.name||id;
 return <section className="weekly-recap broadcast-weekly-recap" aria-label={`Week ${round.number} league recap`}><span className="replay-section-kicker">THE WEEK IN REVIEW</span><h3>Week {round.number} · Around the league</h3><div className="draft-stat-grid"><div><p className="recap-card-label"><Trophy size={17} aria-hidden="true"/>TOP SCORER</p><strong>{recap.top?recap.top.points.toFixed(2):'—'}</strong><span>{recap.topTies.length>1?'Joint top scorer':'Top scorer'} · {recap.top?recap.topTies.map(d=>`${player(d.athleteId)} · ${team(d.teamId)}`).join('; '):'No historical games drawn'}</span></div><div><p className="recap-card-label"><TrendingUp size={17} aria-hidden="true"/>UPSET WATCH</p><strong>{recap.upset?team(recap.upset.match.winner!):'No upset'}</strong><span>{recap.upset?`Biggest standings upset · won from ${recap.upset.gap} places lower in the preweek standings`:recap.hasPrior?'No lower-ranked team beat a higher-ranked team':'No prior regular-season standings yet'}</span></div><div><p className="recap-card-label"><Star size={17} aria-hidden="true"/>LEGEND DRAW</p><strong>{recap.lowestLegend?recap.lowestLegend.points.toFixed(2):'—'}</strong><span>{recap.lowestLegend?`${recap.legendTies.length>1?'Joint lowest-scoring legends':'Lowest-scoring legend'} · ${recap.legendTies.map(d=>player(d.athleteId)).join(', ')}`:'No Hall of Fame starters drew games'}</span></div></div><p className="season-pool-note">Saved scores only. Upsets use the full preweek regular-season standings, including their published tiebreakers, not betting odds. Lowest-scoring legend is a comparison within this week, not an expectation or a forecast.</p></section>;
}
